<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array( 'is_obsolete',
'unee_t_area_id',
'unee_t_role_id',
'unee_t_mefe_user_id',
'unee_t_user_type_id',
'propagate_level_2',
'propagate_level_3' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'is_obsolete' => array( 'import_field10' ),
'unee_t_area_id' => array( 'import_field14' ),
'unee_t_role_id' => array( 'import_field16' ),
'unee_t_mefe_user_id' => array( 'import_field' ),
'unee_t_user_type_id' => array( 'import_field1' ),
'propagate_level_2' => array( 'import_field2' ),
'propagate_level_3' => array( 'import_field3' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'import_header' ),
'grid' => array( 'import_field10',
'import_field14',
'import_field16',
'import_field',
'import_field1',
'import_field2',
'import_field3' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'import_header' => 'top',
'import_field10' => 'grid',
'import_field14' => 'grid',
'import_field16' => 'grid',
'import_field' => 'grid',
'import_field1' => 'grid',
'import_field2' => 'grid',
'import_field3' => 'grid' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'import_header' => array( 'import_header' ),
'import_field' => array( 'import_field10',
'import_field14',
'import_field16',
'import_field',
'import_field1',
'import_field2',
'import_field3' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ) ) ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'import',
'type' => 'import',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'import-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'import-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_field10',
'import_field14',
'import_field16',
'import_field',
'import_field1',
'import_field2',
'import_field3' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'import_header' => array( 'type' => 'import_header' ),
'import_field10' => array( 'field' => 'is_obsolete',
'type' => 'import_field' ),
'import_field14' => array( 'field' => 'unee_t_area_id',
'type' => 'import_field' ),
'import_field16' => array( 'field' => 'unee_t_role_id',
'type' => 'import_field' ),
'import_field' => array( 'field' => 'unee_t_mefe_user_id',
'type' => 'import_field' ),
'import_field1' => array( 'field' => 'unee_t_user_type_id',
'type' => 'import_field' ),
'import_field2' => array( 'field' => 'propagate_level_2',
'type' => 'import_field' ),
'import_field3' => array( 'field' => 'propagate_level_3',
'type' => 'import_field' ) ),
'dbProps' => array(  ),
'version' => 2 );
		?>