<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array( 'unee_t_role_id',
'unee_t_user_type_id',
'id_building',
'area_id',
'system_id_unit',
'name',
'country_code',
'unee_t_level_3_id',
'unee_t_mefe_user_id',
'room_name' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'unee_t_role_id' => array( 'integrated_search_field16' ),
'unee_t_user_type_id' => array( 'integrated_search_field15' ),
'id_building' => array( 'integrated_search_field1' ),
'area_id' => array( 'integrated_search_field3' ),
'system_id_unit' => array( 'integrated_search_field6' ),
'name' => array( 'integrated_search_field12' ),
'country_code' => array( 'integrated_search_field10' ),
'unee_t_level_3_id' => array( 'integrated_search_field' ),
'unee_t_mefe_user_id' => array( 'integrated_search_field2' ),
'room_name' => array( 'integrated_search_field4' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array( 'image',
'logo',
'menu' ),
'top' => array( 'search_header' ),
'above-grid' => array( 'breadcrumb' ),
'below-grid' => array( 'search_search',
'search_reset',
'search_back_list' ),
'grid' => array( 'text2',
'integrated_search_field16',
'integrated_search_field15',
'integrated_search_field2',
'integrated_search_field12',
'text1',
'integrated_search_field4',
'text',
'integrated_search_field',
'text3',
'integrated_search_field10',
'integrated_search_field3',
'integrated_search_field1',
'integrated_search_field6' ) ),
'formXtTags' => array( 'above-grid' => array( 'breadcrumb' ) ),
'itemForms' => array( 'image' => 'supertop',
'logo' => 'supertop',
'menu' => 'supertop',
'search_header' => 'top',
'breadcrumb' => 'above-grid',
'search_search' => 'below-grid',
'search_reset' => 'below-grid',
'search_back_list' => 'below-grid',
'text2' => 'grid',
'integrated_search_field16' => 'grid',
'integrated_search_field15' => 'grid',
'integrated_search_field2' => 'grid',
'integrated_search_field12' => 'grid',
'text1' => 'grid',
'integrated_search_field4' => 'grid',
'text' => 'grid',
'integrated_search_field' => 'grid',
'text3' => 'grid',
'integrated_search_field10' => 'grid',
'integrated_search_field3' => 'grid',
'integrated_search_field1' => 'grid',
'integrated_search_field6' => 'grid' ),
'itemLocations' => array( 'text2' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field16' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field15' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field2' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field12' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'text1' => array( 'location' => 'grid',
'cellId' => 'c' ),
'integrated_search_field4' => array( 'location' => 'grid',
'cellId' => 'c' ),
'text' => array( 'location' => 'grid',
'cellId' => 'c' ),
'integrated_search_field' => array( 'location' => 'grid',
'cellId' => 'c' ),
'text3' => array( 'location' => 'grid',
'cellId' => 'c4' ),
'integrated_search_field10' => array( 'location' => 'grid',
'cellId' => 'c4' ),
'integrated_search_field3' => array( 'location' => 'grid',
'cellId' => 'c4' ),
'integrated_search_field1' => array( 'location' => 'grid',
'cellId' => 'c4' ),
'integrated_search_field6' => array( 'location' => 'grid',
'cellId' => 'c4' ) ),
'itemVisiblity' => array( 'menu' => 3 ) ),
'itemsByType' => array( 'search_header' => array( 'search_header' ),
'search_search' => array( 'search_search' ),
'search_reset' => array( 'search_reset' ),
'search_back_list' => array( 'search_back_list' ),
'integrated_search_field' => array( 'integrated_search_field16',
'integrated_search_field15',
'integrated_search_field1',
'integrated_search_field3',
'integrated_search_field6',
'integrated_search_field12',
'integrated_search_field10',
'integrated_search_field',
'integrated_search_field2',
'integrated_search_field4' ),
'breadcrumb' => array( 'breadcrumb' ),
'logo' => array( 'logo' ),
'menu' => array( 'menu' ),
'image' => array( 'image' ),
'text' => array( 'text',
'text1',
'text2',
'text3' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'c3' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'text2',
'integrated_search_field16',
'integrated_search_field15',
'integrated_search_field2',
'integrated_search_field12' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c4' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'text3',
'integrated_search_field10',
'integrated_search_field3',
'integrated_search_field1',
'integrated_search_field6' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'text1',
'integrated_search_field4',
'text',
'integrated_search_field' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 3 ) ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ) ),
'misc' => array( 'type' => 'search',
'breadcrumb' => true ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'search',
'type' => 'search',
'layoutId' => 'topbar',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'topbar-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ),
array( 'cell' => 'c3' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'image',
'logo' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'menu' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c3' => array( 'model' => 'c3',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'search-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'search_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'above-grid' => array( 'modelId' => 'search-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1',
'colspan' => 2 ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'breadcrumb' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'search-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'search_search',
'search_reset',
'search_back_list' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'simple-search',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c3' ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c4' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c' ) ) ) ),
'cells' => array( 'c3' => array( 'model' => 'c3',
'items' => array( 'text2',
'integrated_search_field16',
'integrated_search_field15',
'integrated_search_field2',
'integrated_search_field12' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c' => array( 'model' => 'c3',
'items' => array( 'text1',
'integrated_search_field4',
'text',
'integrated_search_field' ) ),
'c4' => array( 'model' => 'c3',
'items' => array( 'text3',
'integrated_search_field10',
'integrated_search_field3',
'integrated_search_field1',
'integrated_search_field6' ) ) ),
'deferredItems' => array(  ),
'separateLabels' => false ) ),
'items' => array( 'search_header' => array( 'type' => 'search_header' ),
'search_search' => array( 'type' => 'search_search' ),
'search_reset' => array( 'type' => 'search_reset' ),
'search_back_list' => array( 'type' => 'search_back_list' ),
'integrated_search_field16' => array( 'field' => 'unee_t_role_id',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field15' => array( 'field' => 'unee_t_user_type_id',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field1' => array( 'field' => 'id_building',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field3' => array( 'field' => 'area_id',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'breadcrumb' => array( 'type' => 'breadcrumb' ),
'logo' => array( 'type' => 'logo' ),
'menu' => array( 'type' => 'menu' ),
'image' => array( 'type' => 'image',
'imagePath' => 'Unee-T Enterprise160x50.png' ),
'integrated_search_field6' => array( 'field' => 'system_id_unit',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field12' => array( 'field' => 'name',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field10' => array( 'field' => 'country_code',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field' => array( 'field' => 'unee_t_level_3_id',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'text' => array( 'type' => 'text',
'label' => array( 'text' => 'Or search the room directly',
'type' => 0 ),
'bold' => true,
'font-size' => '2em' ),
'text1' => array( 'type' => 'text',
'label' => array( 'text' => 'Or type the name of the Room',
'type' => 0 ),
'bold' => true,
'font-size' => '2em' ),
'text2' => array( 'type' => 'text',
'label' => array( 'text' => 'Search by Users',
'type' => 0 ),
'bold' => true,
'font-size' => '2em' ),
'text3' => array( 'type' => 'text',
'label' => array( 'text' => 'Reduce the list with these criterias',
'type' => 0 ),
'bold' => true,
'font-size' => '2em' ),
'integrated_search_field2' => array( 'field' => 'unee_t_mefe_user_id',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field4' => array( 'field' => 'room_name',
'type' => 'integrated_search_field',
'orientation' => 0 ) ),
'dbProps' => array(  ),
'version' => 4,
'fixedTopbar' => true );
		?>