<?php
			$optionsArray = array( 'totals' => array( 'id_building' => array( 'totalsType' => '' ),
'external_id' => array( 'totalsType' => '' ),
'external_system_id' => array( 'totalsType' => '' ),
'external_table' => array( 'totalsType' => '' ),
'syst_created_datetime' => array( 'totalsType' => '' ),
'creation_system_id' => array( 'totalsType' => '' ),
'created_by_id' => array( 'totalsType' => '' ),
'creation_method' => array( 'totalsType' => '' ),
'syst_updated_datetime' => array( 'totalsType' => '' ),
'update_system_id' => array( 'totalsType' => '' ),
'updated_by_id' => array( 'totalsType' => '' ),
'update_method' => array( 'totalsType' => '' ),
'country_code' => array( 'totalsType' => '' ),
'country_name' => array( 'totalsType' => '' ),
'area_name' => array( 'totalsType' => '' ),
'area_id' => array( 'totalsType' => '' ),
'designation' => array( 'totalsType' => '' ),
'unee_t_unit_type' => array( 'totalsType' => '' ),
'is_creation_needed_in_unee_t' => array( 'totalsType' => '' ),
'tower' => array( 'totalsType' => '' ),
'address_1' => array( 'totalsType' => '' ),
'address_2' => array( 'totalsType' => '' ),
'zip_postal_code' => array( 'totalsType' => '' ),
'state' => array( 'totalsType' => '' ),
'city' => array( 'totalsType' => '' ),
'description' => array( 'totalsType' => '' ),
'is_obsolete' => array( 'totalsType' => '' ),
'order' => array( 'totalsType' => '' ),
'do_not_insert' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'external_id',
'designation',
'tower',
'unee_t_unit_type',
'description',
'is_creation_needed_in_unee_t',
'is_obsolete',
'order',
'area_id',
'address_1',
'address_2',
'zip_postal_code',
'state',
'city',
'country_code',
'id_building',
'country_name',
'area_name' ),
'exportFields' => array( 'country_code',
'country_name',
'area_id',
'area_name',
'id_building',
'external_id',
'designation',
'is_creation_needed_in_unee_t',
'unee_t_unit_type',
'is_obsolete',
'order',
'description',
'tower',
'address_1',
'address_2',
'zip_postal_code',
'city',
'state' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'external_id' => array( 'export_field1' ),
'designation' => array( 'export_field4' ),
'tower' => array( 'export_field5' ),
'unee_t_unit_type' => array( 'export_field6' ),
'description' => array( 'export_field7' ),
'is_creation_needed_in_unee_t' => array( 'export_field8' ),
'is_obsolete' => array( 'export_field12' ),
'order' => array( 'export_field13' ),
'area_id' => array( 'export_field9' ),
'address_1' => array( 'export_field10' ),
'address_2' => array( 'export_field11' ),
'zip_postal_code' => array( 'export_field14' ),
'state' => array( 'export_field15' ),
'city' => array( 'export_field16' ),
'country_code' => array( 'export_field17' ),
'id_building' => array( 'export_field' ),
'country_name' => array( 'export_field2' ),
'area_name' => array( 'export_field3' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'image',
'export_header' ),
'grid' => array( 'export_field17',
'export_field2',
'export_field9',
'export_field3',
'export_field',
'export_field1',
'export_field4',
'export_field8',
'export_field6',
'export_field12',
'export_field13',
'export_field7',
'export_field5',
'export_field10',
'export_field11',
'export_field14',
'export_field16',
'export_field15' ),
'footer' => array( 'export_export',
'export_cancel' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'image' => 'top',
'export_header' => 'top',
'export_field17' => 'grid',
'export_field2' => 'grid',
'export_field9' => 'grid',
'export_field3' => 'grid',
'export_field' => 'grid',
'export_field1' => 'grid',
'export_field4' => 'grid',
'export_field8' => 'grid',
'export_field6' => 'grid',
'export_field12' => 'grid',
'export_field13' => 'grid',
'export_field7' => 'grid',
'export_field5' => 'grid',
'export_field10' => 'grid',
'export_field11' => 'grid',
'export_field14' => 'grid',
'export_field16' => 'grid',
'export_field15' => 'grid',
'export_export' => 'footer',
'export_cancel' => 'footer' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'export_header' => array( 'export_header' ),
'export_export' => array( 'export_export' ),
'export_cancel' => array( 'export_cancel' ),
'export_field' => array( 'export_field1',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field12',
'export_field13',
'export_field9',
'export_field10',
'export_field11',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field',
'export_field2',
'export_field3' ),
'image' => array( 'image' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ) ) ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'export' => array( 'format' => 2,
'selectFields' => false,
'delimiter' => ',',
'selectDelimiter' => false ) );
			$pageArray = array( 'id' => 'export',
'type' => 'export',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'export-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'image',
'export_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'export-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_field17',
'export_field2',
'export_field9',
'export_field3',
'export_field',
'export_field1',
'export_field4',
'export_field8',
'export_field6',
'export_field12',
'export_field13',
'export_field7',
'export_field5',
'export_field10',
'export_field11',
'export_field14',
'export_field16',
'export_field15' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'footer' => array( 'modelId' => 'export-footer',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'export_export',
'export_cancel' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'export_header' => array( 'type' => 'export_header' ),
'export_export' => array( 'type' => 'export_export' ),
'export_cancel' => array( 'type' => 'export_cancel' ),
'export_field1' => array( 'field' => 'external_id',
'type' => 'export_field' ),
'export_field4' => array( 'field' => 'designation',
'type' => 'export_field' ),
'export_field5' => array( 'field' => 'tower',
'type' => 'export_field' ),
'export_field6' => array( 'field' => 'unee_t_unit_type',
'type' => 'export_field' ),
'export_field7' => array( 'field' => 'description',
'type' => 'export_field' ),
'export_field8' => array( 'field' => 'is_creation_needed_in_unee_t',
'type' => 'export_field' ),
'export_field12' => array( 'field' => 'is_obsolete',
'type' => 'export_field' ),
'export_field13' => array( 'field' => 'order',
'type' => 'export_field' ),
'export_field9' => array( 'field' => 'area_id',
'type' => 'export_field' ),
'export_field10' => array( 'field' => 'address_1',
'type' => 'export_field' ),
'export_field11' => array( 'field' => 'address_2',
'type' => 'export_field' ),
'export_field14' => array( 'field' => 'zip_postal_code',
'type' => 'export_field' ),
'export_field15' => array( 'field' => 'state',
'type' => 'export_field' ),
'export_field16' => array( 'field' => 'city',
'type' => 'export_field' ),
'image' => array( 'type' => 'image',
'imagePath' => 'Unee-T Enterprise160x50.png' ),
'export_field17' => array( 'field' => 'country_code',
'type' => 'export_field' ),
'export_field' => array( 'field' => 'id_building',
'type' => 'export_field' ),
'export_field2' => array( 'field' => 'country_name',
'type' => 'export_field' ),
'export_field3' => array( 'field' => 'area_name',
'type' => 'export_field' ) ),
'dbProps' => array(  ),
'version' => 2,
'exportFormat' => 2,
'exportDelimiter' => ',',
'exportSelectDelimiter' => false,
'exportSelectFields' => false );
		?>