<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array( 'order',
'is_obsolete',
'description',
'organization_id',
'designation',
'ut_user_role_type_id',
'is_all_unit',
'is_all_units_in_country',
'is_all_units_in_area',
'is_all_units_in_level_1',
'is_all_units_in_level_2',
'is_occupant',
'is_public',
'is_default_assignee',
'is_default_invited',
'is_dashboard_access',
'can_see_role_contractor',
'can_see_role_mgt_cny',
'can_see_occupant',
'can_see_role_landlord',
'can_see_role_agent',
'can_see_role_tenant',
'is_assigned_to_case',
'is_invited_to_case',
'is_solution_updated',
'is_next_step_updated',
'is_deadline_updated',
'is_case_resolved',
'is_case_critical',
'is_case_blocker',
'is_message_from_contractor',
'is_message_from_mgt_cny',
'is_message_from_agent',
'is_message_from_occupant',
'is_message_from_ll',
'is_message_from_tenant',
'is_any_new_message',
'is_new_ir',
'is_new_inventory',
'is_new_item',
'is_item_moved',
'is_item_removed' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'order' => array( 'import_field7' ),
'is_obsolete' => array( 'import_field8' ),
'description' => array( 'import_field10' ),
'organization_id' => array( 'import_field12' ),
'designation' => array( 'import_field13' ),
'ut_user_role_type_id' => array( 'import_field14' ),
'is_all_unit' => array( 'import_field16' ),
'is_all_units_in_country' => array( 'import_field17' ),
'is_all_units_in_area' => array( 'import_field18' ),
'is_all_units_in_level_1' => array( 'import_field19' ),
'is_all_units_in_level_2' => array( 'import_field20' ),
'is_occupant' => array( 'import_field21' ),
'is_public' => array( 'import_field22' ),
'is_default_assignee' => array( 'import_field23' ),
'is_default_invited' => array( 'import_field24' ),
'is_dashboard_access' => array( 'import_field25' ),
'can_see_role_contractor' => array( 'import_field26' ),
'can_see_role_mgt_cny' => array( 'import_field27' ),
'can_see_occupant' => array( 'import_field28' ),
'can_see_role_landlord' => array( 'import_field29' ),
'can_see_role_agent' => array( 'import_field30' ),
'can_see_role_tenant' => array( 'import_field31' ),
'is_assigned_to_case' => array( 'import_field32' ),
'is_invited_to_case' => array( 'import_field33' ),
'is_solution_updated' => array( 'import_field34' ),
'is_next_step_updated' => array( 'import_field35' ),
'is_deadline_updated' => array( 'import_field36' ),
'is_case_resolved' => array( 'import_field37' ),
'is_case_critical' => array( 'import_field38' ),
'is_case_blocker' => array( 'import_field39' ),
'is_message_from_contractor' => array( 'import_field40' ),
'is_message_from_mgt_cny' => array( 'import_field41' ),
'is_message_from_agent' => array( 'import_field42' ),
'is_message_from_occupant' => array( 'import_field43' ),
'is_message_from_ll' => array( 'import_field44' ),
'is_message_from_tenant' => array( 'import_field45' ),
'is_any_new_message' => array( 'import_field46' ),
'is_new_ir' => array( 'import_field47' ),
'is_new_inventory' => array( 'import_field48' ),
'is_new_item' => array( 'import_field49' ),
'is_item_moved' => array( 'import_field50' ),
'is_item_removed' => array( 'import_field51' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'import_header' ),
'grid' => array( 'import_field13',
'import_field10',
'import_field8',
'import_field14',
'import_field7',
'import_field16',
'import_field17',
'import_field18',
'import_field19',
'import_field20',
'import_field21',
'import_field22',
'import_field23',
'import_field24',
'import_field25',
'import_field26',
'import_field27',
'import_field28',
'import_field29',
'import_field30',
'import_field31',
'import_field32',
'import_field33',
'import_field34',
'import_field35',
'import_field36',
'import_field37',
'import_field38',
'import_field39',
'import_field40',
'import_field41',
'import_field42',
'import_field43',
'import_field44',
'import_field45',
'import_field46',
'import_field47',
'import_field48',
'import_field49',
'import_field50',
'import_field51',
'import_field12' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'import_header' => 'top',
'import_field13' => 'grid',
'import_field10' => 'grid',
'import_field8' => 'grid',
'import_field14' => 'grid',
'import_field7' => 'grid',
'import_field16' => 'grid',
'import_field17' => 'grid',
'import_field18' => 'grid',
'import_field19' => 'grid',
'import_field20' => 'grid',
'import_field21' => 'grid',
'import_field22' => 'grid',
'import_field23' => 'grid',
'import_field24' => 'grid',
'import_field25' => 'grid',
'import_field26' => 'grid',
'import_field27' => 'grid',
'import_field28' => 'grid',
'import_field29' => 'grid',
'import_field30' => 'grid',
'import_field31' => 'grid',
'import_field32' => 'grid',
'import_field33' => 'grid',
'import_field34' => 'grid',
'import_field35' => 'grid',
'import_field36' => 'grid',
'import_field37' => 'grid',
'import_field38' => 'grid',
'import_field39' => 'grid',
'import_field40' => 'grid',
'import_field41' => 'grid',
'import_field42' => 'grid',
'import_field43' => 'grid',
'import_field44' => 'grid',
'import_field45' => 'grid',
'import_field46' => 'grid',
'import_field47' => 'grid',
'import_field48' => 'grid',
'import_field49' => 'grid',
'import_field50' => 'grid',
'import_field51' => 'grid',
'import_field12' => 'grid' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'import_header' => array( 'import_header' ),
'import_field' => array( 'import_field7',
'import_field8',
'import_field10',
'import_field12',
'import_field13',
'import_field14',
'import_field16',
'import_field17',
'import_field18',
'import_field19',
'import_field20',
'import_field21',
'import_field22',
'import_field23',
'import_field24',
'import_field25',
'import_field26',
'import_field27',
'import_field28',
'import_field29',
'import_field30',
'import_field31',
'import_field32',
'import_field33',
'import_field34',
'import_field35',
'import_field36',
'import_field37',
'import_field38',
'import_field39',
'import_field40',
'import_field41',
'import_field42',
'import_field43',
'import_field44',
'import_field45',
'import_field46',
'import_field47',
'import_field48',
'import_field49',
'import_field50',
'import_field51' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ) ) ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'import',
'type' => 'import',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'import-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'import-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_field13',
'import_field10',
'import_field8',
'import_field14',
'import_field7',
'import_field16',
'import_field17',
'import_field18',
'import_field19',
'import_field20',
'import_field21',
'import_field22',
'import_field23',
'import_field24',
'import_field25',
'import_field26',
'import_field27',
'import_field28',
'import_field29',
'import_field30',
'import_field31',
'import_field32',
'import_field33',
'import_field34',
'import_field35',
'import_field36',
'import_field37',
'import_field38',
'import_field39',
'import_field40',
'import_field41',
'import_field42',
'import_field43',
'import_field44',
'import_field45',
'import_field46',
'import_field47',
'import_field48',
'import_field49',
'import_field50',
'import_field51',
'import_field12' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'import_header' => array( 'type' => 'import_header' ),
'import_field7' => array( 'field' => 'order',
'type' => 'import_field' ),
'import_field8' => array( 'field' => 'is_obsolete',
'type' => 'import_field' ),
'import_field10' => array( 'field' => 'description',
'type' => 'import_field' ),
'import_field12' => array( 'field' => 'organization_id',
'type' => 'import_field' ),
'import_field13' => array( 'field' => 'designation',
'type' => 'import_field' ),
'import_field14' => array( 'field' => 'ut_user_role_type_id',
'type' => 'import_field' ),
'import_field16' => array( 'field' => 'is_all_unit',
'type' => 'import_field' ),
'import_field17' => array( 'field' => 'is_all_units_in_country',
'type' => 'import_field' ),
'import_field18' => array( 'field' => 'is_all_units_in_area',
'type' => 'import_field' ),
'import_field19' => array( 'field' => 'is_all_units_in_level_1',
'type' => 'import_field' ),
'import_field20' => array( 'field' => 'is_all_units_in_level_2',
'type' => 'import_field' ),
'import_field21' => array( 'field' => 'is_occupant',
'type' => 'import_field' ),
'import_field22' => array( 'field' => 'is_public',
'type' => 'import_field' ),
'import_field23' => array( 'field' => 'is_default_assignee',
'type' => 'import_field' ),
'import_field24' => array( 'field' => 'is_default_invited',
'type' => 'import_field' ),
'import_field25' => array( 'field' => 'is_dashboard_access',
'type' => 'import_field' ),
'import_field26' => array( 'field' => 'can_see_role_contractor',
'type' => 'import_field' ),
'import_field27' => array( 'field' => 'can_see_role_mgt_cny',
'type' => 'import_field' ),
'import_field28' => array( 'field' => 'can_see_occupant',
'type' => 'import_field' ),
'import_field29' => array( 'field' => 'can_see_role_landlord',
'type' => 'import_field' ),
'import_field30' => array( 'field' => 'can_see_role_agent',
'type' => 'import_field' ),
'import_field31' => array( 'field' => 'can_see_role_tenant',
'type' => 'import_field' ),
'import_field32' => array( 'field' => 'is_assigned_to_case',
'type' => 'import_field' ),
'import_field33' => array( 'field' => 'is_invited_to_case',
'type' => 'import_field' ),
'import_field34' => array( 'field' => 'is_solution_updated',
'type' => 'import_field' ),
'import_field35' => array( 'field' => 'is_next_step_updated',
'type' => 'import_field' ),
'import_field36' => array( 'field' => 'is_deadline_updated',
'type' => 'import_field' ),
'import_field37' => array( 'field' => 'is_case_resolved',
'type' => 'import_field' ),
'import_field38' => array( 'field' => 'is_case_critical',
'type' => 'import_field' ),
'import_field39' => array( 'field' => 'is_case_blocker',
'type' => 'import_field' ),
'import_field40' => array( 'field' => 'is_message_from_contractor',
'type' => 'import_field' ),
'import_field41' => array( 'field' => 'is_message_from_mgt_cny',
'type' => 'import_field' ),
'import_field42' => array( 'field' => 'is_message_from_agent',
'type' => 'import_field' ),
'import_field43' => array( 'field' => 'is_message_from_occupant',
'type' => 'import_field' ),
'import_field44' => array( 'field' => 'is_message_from_ll',
'type' => 'import_field' ),
'import_field45' => array( 'field' => 'is_message_from_tenant',
'type' => 'import_field' ),
'import_field46' => array( 'field' => 'is_any_new_message',
'type' => 'import_field' ),
'import_field47' => array( 'field' => 'is_new_ir',
'type' => 'import_field' ),
'import_field48' => array( 'field' => 'is_new_inventory',
'type' => 'import_field' ),
'import_field49' => array( 'field' => 'is_new_item',
'type' => 'import_field' ),
'import_field50' => array( 'field' => 'is_item_moved',
'type' => 'import_field' ),
'import_field51' => array( 'field' => 'is_item_removed',
'type' => 'import_field' ) ),
'dbProps' => array(  ),
'version' => 2 );
		?>