<?php
			$optionsArray = array( 'totals' => array( 'id_person' => array( 'totalsType' => '' ),
'external_id' => array( 'totalsType' => '' ),
'external_system' => array( 'totalsType' => '' ),
'external_table' => array( 'totalsType' => '' ),
'syst_created_datetime' => array( 'totalsType' => '' ),
'creation_system_id' => array( 'totalsType' => '' ),
'created_by_id' => array( 'totalsType' => '' ),
'creation_method' => array( 'totalsType' => '' ),
'syst_updated_datetime' => array( 'totalsType' => '' ),
'update_system_id' => array( 'totalsType' => '' ),
'updated_by_id' => array( 'totalsType' => '' ),
'update_method' => array( 'totalsType' => '' ),
'person_status_id' => array( 'totalsType' => '' ),
'person_status' => array( 'totalsType' => '' ),
'is_unee_t_account_needed' => array( 'totalsType' => '' ),
'unee_t_user_type_id' => array( 'totalsType' => '' ),
'designation' => array( 'totalsType' => '' ),
'role_type' => array( 'totalsType' => '' ),
'gender' => array( 'totalsType' => '' ),
'person_gender' => array( 'totalsType' => '' ),
'salutation_id' => array( 'totalsType' => '' ),
'salutation' => array( 'totalsType' => '' ),
'given_name' => array( 'totalsType' => '' ),
'middle_name' => array( 'totalsType' => '' ),
'family_name' => array( 'totalsType' => '' ),
'date_of_birth' => array( 'totalsType' => '' ),
'alias' => array( 'totalsType' => '' ),
'job_title' => array( 'totalsType' => '' ),
'organization' => array( 'totalsType' => '' ),
'email' => array( 'totalsType' => '' ),
'tel_1' => array( 'totalsType' => '' ),
'tel_2' => array( 'totalsType' => '' ),
'whatsapp' => array( 'totalsType' => '' ),
'linkedin' => array( 'totalsType' => '' ),
'facebook' => array( 'totalsType' => '' ),
'adr1' => array( 'totalsType' => '' ),
'adr2' => array( 'totalsType' => '' ),
'adr3' => array( 'totalsType' => '' ),
'City' => array( 'totalsType' => '' ),
'zip_postcode' => array( 'totalsType' => '' ),
'region_or_state' => array( 'totalsType' => '' ),
'country_code' => array( 'totalsType' => '' ),
'country' => array( 'totalsType' => '' ),
'dupe_id' => array( 'totalsType' => '' ),
'handler_id' => array( 'totalsType' => '' ),
'uneet_created_datetime' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'external_id',
'external_system',
'external_table',
'is_unee_t_account_needed',
'country_code',
'gender',
'salutation_id',
'given_name',
'middle_name',
'family_name',
'date_of_birth',
'alias',
'job_title',
'organization',
'email',
'tel_1',
'tel_2',
'whatsapp',
'linkedin',
'facebook',
'adr1',
'adr2',
'adr3',
'City',
'zip_postcode',
'region_or_state',
'country',
'unee_t_user_type_id',
'person_status_id',
'created_by_id',
'id_person',
'role_type' ),
'exportFields' => array( 'id_person',
'external_id',
'external_system',
'external_table',
'person_status_id',
'is_unee_t_account_needed',
'unee_t_user_type_id',
'salutation_id',
'given_name',
'middle_name',
'family_name',
'email',
'gender',
'date_of_birth',
'alias',
'job_title',
'organization',
'tel_1',
'tel_2',
'whatsapp',
'linkedin',
'facebook',
'adr1',
'adr2',
'adr3',
'City',
'zip_postcode',
'region_or_state',
'country_code',
'country',
'created_by_id',
'role_type' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'external_id' => array( 'export_field1' ),
'external_system' => array( 'export_field2' ),
'external_table' => array( 'export_field3' ),
'is_unee_t_account_needed' => array( 'export_field13' ),
'country_code' => array( 'export_field15' ),
'gender' => array( 'export_field16' ),
'salutation_id' => array( 'export_field17' ),
'given_name' => array( 'export_field18' ),
'middle_name' => array( 'export_field19' ),
'family_name' => array( 'export_field20' ),
'date_of_birth' => array( 'export_field21' ),
'alias' => array( 'export_field22' ),
'job_title' => array( 'export_field23' ),
'organization' => array( 'export_field24' ),
'email' => array( 'export_field25' ),
'tel_1' => array( 'export_field26' ),
'tel_2' => array( 'export_field27' ),
'whatsapp' => array( 'export_field28' ),
'linkedin' => array( 'export_field29' ),
'facebook' => array( 'export_field30' ),
'adr1' => array( 'export_field31' ),
'adr2' => array( 'export_field32' ),
'adr3' => array( 'export_field33' ),
'City' => array( 'export_field34' ),
'zip_postcode' => array( 'export_field35' ),
'region_or_state' => array( 'export_field36' ),
'country' => array( 'export_field37' ),
'unee_t_user_type_id' => array( 'export_field4' ),
'person_status_id' => array( 'export_field5' ),
'created_by_id' => array( 'export_field6' ),
'id_person' => array( 'export_field' ),
'role_type' => array( 'export_field7' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'export_header' ),
'grid' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field5',
'export_field13',
'export_field4',
'export_field17',
'export_field18',
'export_field19',
'export_field20',
'export_field25',
'export_field16',
'export_field21',
'export_field22',
'export_field23',
'export_field24',
'export_field26',
'export_field27',
'export_field28',
'export_field29',
'export_field30',
'export_field31',
'export_field32',
'export_field33',
'export_field34',
'export_field35',
'export_field36',
'export_field15',
'export_field37',
'export_field6',
'export_field7' ),
'footer' => array( 'export_export',
'export_cancel' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'export_header' => 'top',
'export_field' => 'grid',
'export_field1' => 'grid',
'export_field2' => 'grid',
'export_field3' => 'grid',
'export_field5' => 'grid',
'export_field13' => 'grid',
'export_field4' => 'grid',
'export_field17' => 'grid',
'export_field18' => 'grid',
'export_field19' => 'grid',
'export_field20' => 'grid',
'export_field25' => 'grid',
'export_field16' => 'grid',
'export_field21' => 'grid',
'export_field22' => 'grid',
'export_field23' => 'grid',
'export_field24' => 'grid',
'export_field26' => 'grid',
'export_field27' => 'grid',
'export_field28' => 'grid',
'export_field29' => 'grid',
'export_field30' => 'grid',
'export_field31' => 'grid',
'export_field32' => 'grid',
'export_field33' => 'grid',
'export_field34' => 'grid',
'export_field35' => 'grid',
'export_field36' => 'grid',
'export_field15' => 'grid',
'export_field37' => 'grid',
'export_field6' => 'grid',
'export_field7' => 'grid',
'export_export' => 'footer',
'export_cancel' => 'footer' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'export_header' => array( 'export_header' ),
'export_export' => array( 'export_export' ),
'export_cancel' => array( 'export_cancel' ),
'export_field' => array( 'export_field1',
'export_field2',
'export_field3',
'export_field13',
'export_field15',
'export_field16',
'export_field17',
'export_field18',
'export_field19',
'export_field20',
'export_field21',
'export_field22',
'export_field23',
'export_field24',
'export_field25',
'export_field26',
'export_field27',
'export_field28',
'export_field29',
'export_field30',
'export_field31',
'export_field32',
'export_field33',
'export_field34',
'export_field35',
'export_field36',
'export_field37',
'export_field4',
'export_field5',
'export_field6',
'export_field',
'export_field7' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ) ) ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'export' => array( 'format' => 2,
'selectFields' => false,
'delimiter' => ',',
'selectDelimiter' => false ) );
			$pageArray = array( 'id' => 'export',
'type' => 'export',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'export-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'export-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field5',
'export_field13',
'export_field4',
'export_field17',
'export_field18',
'export_field19',
'export_field20',
'export_field25',
'export_field16',
'export_field21',
'export_field22',
'export_field23',
'export_field24',
'export_field26',
'export_field27',
'export_field28',
'export_field29',
'export_field30',
'export_field31',
'export_field32',
'export_field33',
'export_field34',
'export_field35',
'export_field36',
'export_field15',
'export_field37',
'export_field6',
'export_field7' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'footer' => array( 'modelId' => 'export-footer',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'export_export',
'export_cancel' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'export_header' => array( 'type' => 'export_header' ),
'export_export' => array( 'type' => 'export_export' ),
'export_cancel' => array( 'type' => 'export_cancel' ),
'export_field1' => array( 'field' => 'external_id',
'type' => 'export_field' ),
'export_field2' => array( 'field' => 'external_system',
'type' => 'export_field' ),
'export_field3' => array( 'field' => 'external_table',
'type' => 'export_field' ),
'export_field13' => array( 'field' => 'is_unee_t_account_needed',
'type' => 'export_field' ),
'export_field15' => array( 'field' => 'country_code',
'type' => 'export_field' ),
'export_field16' => array( 'field' => 'gender',
'type' => 'export_field' ),
'export_field17' => array( 'field' => 'salutation_id',
'type' => 'export_field' ),
'export_field18' => array( 'field' => 'given_name',
'type' => 'export_field' ),
'export_field19' => array( 'field' => 'middle_name',
'type' => 'export_field' ),
'export_field20' => array( 'field' => 'family_name',
'type' => 'export_field' ),
'export_field21' => array( 'field' => 'date_of_birth',
'type' => 'export_field' ),
'export_field22' => array( 'field' => 'alias',
'type' => 'export_field' ),
'export_field23' => array( 'field' => 'job_title',
'type' => 'export_field' ),
'export_field24' => array( 'field' => 'organization',
'type' => 'export_field' ),
'export_field25' => array( 'field' => 'email',
'type' => 'export_field' ),
'export_field26' => array( 'field' => 'tel_1',
'type' => 'export_field' ),
'export_field27' => array( 'field' => 'tel_2',
'type' => 'export_field' ),
'export_field28' => array( 'field' => 'whatsapp',
'type' => 'export_field' ),
'export_field29' => array( 'field' => 'linkedin',
'type' => 'export_field' ),
'export_field30' => array( 'field' => 'facebook',
'type' => 'export_field' ),
'export_field31' => array( 'field' => 'adr1',
'type' => 'export_field' ),
'export_field32' => array( 'field' => 'adr2',
'type' => 'export_field' ),
'export_field33' => array( 'field' => 'adr3',
'type' => 'export_field' ),
'export_field34' => array( 'field' => 'City',
'type' => 'export_field' ),
'export_field35' => array( 'field' => 'zip_postcode',
'type' => 'export_field' ),
'export_field36' => array( 'field' => 'region_or_state',
'type' => 'export_field' ),
'export_field37' => array( 'field' => 'country',
'type' => 'export_field' ),
'export_field4' => array( 'field' => 'unee_t_user_type_id',
'type' => 'export_field' ),
'export_field5' => array( 'field' => 'person_status_id',
'type' => 'export_field' ),
'export_field6' => array( 'field' => 'created_by_id',
'type' => 'export_field' ),
'export_field' => array( 'field' => 'id_person',
'type' => 'export_field' ),
'export_field7' => array( 'field' => 'role_type',
'type' => 'export_field' ) ),
'dbProps' => array(  ),
'version' => 2,
'exportFormat' => 2,
'exportDelimiter' => ',',
'exportSelectDelimiter' => false,
'exportSelectFields' => false );
		?>