<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array( 'id_map',
'unee_t_unit_type',
'uneet_name',
'external_property_type_id',
'external_property_id',
'external_system',
'table_in_external_system' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'id_map' => array( 'import_field' ),
'unee_t_unit_type' => array( 'import_field14' ),
'uneet_name' => array( 'import_field15' ),
'external_property_type_id' => array( 'import_field1' ),
'external_property_id' => array( 'import_field2' ),
'external_system' => array( 'import_field3' ),
'table_in_external_system' => array( 'import_field4' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'import_header' ),
'grid' => array( 'import_field',
'import_field14',
'import_field15',
'import_field1',
'import_field2',
'import_field3',
'import_field4' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'import_header' => 'top',
'import_field' => 'grid',
'import_field14' => 'grid',
'import_field15' => 'grid',
'import_field1' => 'grid',
'import_field2' => 'grid',
'import_field3' => 'grid',
'import_field4' => 'grid' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'import_header' => array( 'import_header' ),
'import_field' => array( 'import_field',
'import_field14',
'import_field15',
'import_field1',
'import_field2',
'import_field3',
'import_field4' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ) ) ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'import',
'type' => 'import',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'import-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'import-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_field',
'import_field14',
'import_field15',
'import_field1',
'import_field2',
'import_field3',
'import_field4' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'import_header' => array( 'type' => 'import_header' ),
'import_field' => array( 'field' => 'id_map',
'type' => 'import_field' ),
'import_field14' => array( 'field' => 'unee_t_unit_type',
'type' => 'import_field' ),
'import_field15' => array( 'field' => 'uneet_name',
'type' => 'import_field' ),
'import_field1' => array( 'field' => 'external_property_type_id',
'type' => 'import_field' ),
'import_field2' => array( 'field' => 'external_property_id',
'type' => 'import_field' ),
'import_field3' => array( 'field' => 'external_system',
'type' => 'import_field' ),
'import_field4' => array( 'field' => 'table_in_external_system',
'type' => 'import_field' ) ),
'dbProps' => array(  ),
'version' => 2 );
		?>