<?php
			$optionsArray = array( 'totals' => array( 'system_id_room' => array( 'totalsType' => '' ),
'external_id' => array( 'totalsType' => '' ),
'external_system_id' => array( 'totalsType' => '' ),
'external_table' => array( 'totalsType' => '' ),
'syst_created_datetime' => array( 'totalsType' => '' ),
'creation_system_id' => array( 'totalsType' => '' ),
'created_by_id' => array( 'totalsType' => '' ),
'creation_method' => array( 'totalsType' => '' ),
'syst_updated_datetime' => array( 'totalsType' => '' ),
'update_system_id' => array( 'totalsType' => '' ),
'updated_by_id' => array( 'totalsType' => '' ),
'update_method' => array( 'totalsType' => '' ),
'country_code' => array( 'totalsType' => '' ),
'country_name' => array( 'totalsType' => '' ),
'area_id' => array( 'totalsType' => '' ),
'area_name' => array( 'totalsType' => '' ),
'building_system_id' => array( 'totalsType' => '' ),
'building_name' => array( 'totalsType' => '' ),
'system_id_unit' => array( 'totalsType' => '' ),
'unit_designation' => array( 'totalsType' => '' ),
'room_designation' => array( 'totalsType' => '' ),
'unee_t_unit_type' => array( 'totalsType' => '' ),
'is_obsolete' => array( 'totalsType' => '' ),
'is_creation_needed_in_unee_t' => array( 'totalsType' => '' ),
'number_of_beds' => array( 'totalsType' => '' ),
'surface' => array( 'totalsType' => '' ),
'surface_measurment_unit' => array( 'totalsType' => '' ),
'room_description' => array( 'totalsType' => '' ),
'room_type_id' => array( 'totalsType' => '' ),
'order_area' => array( 'totalsType' => '' ),
'order_building' => array( 'totalsType' => '' ),
'tower' => array( 'totalsType' => '' ),
'do_not_insert' => array( 'totalsType' => '' ),
'uneet_created_datetime' => array( 'totalsType' => '' ),
'unee_t_mefe_unit_id' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'external_id',
'external_system_id',
'external_table',
'unee_t_unit_type',
'room_designation',
'is_obsolete',
'is_creation_needed_in_unee_t',
'number_of_beds',
'surface',
'surface_measurment_unit',
'room_description',
'created_by_id' ),
'exportFields' => array( 'room_designation',
'unee_t_unit_type',
'is_creation_needed_in_unee_t',
'is_obsolete',
'number_of_beds',
'surface',
'surface_measurment_unit',
'room_description',
'external_id',
'external_system_id',
'external_table',
'created_by_id' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'external_id' => array( 'export_field1' ),
'external_system_id' => array( 'export_field2' ),
'external_table' => array( 'export_field3' ),
'unee_t_unit_type' => array( 'export_field' ),
'room_designation' => array( 'export_field4' ),
'is_obsolete' => array( 'export_field5' ),
'is_creation_needed_in_unee_t' => array( 'export_field6' ),
'number_of_beds' => array( 'export_field7' ),
'surface' => array( 'export_field8' ),
'surface_measurment_unit' => array( 'export_field9' ),
'room_description' => array( 'export_field10' ),
'created_by_id' => array( 'export_field11' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'export_header' ),
'grid' => array( 'export_field4',
'export_field',
'export_field6',
'export_field5',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field1',
'export_field2',
'export_field3',
'export_field11' ),
'footer' => array( 'export_export',
'export_cancel' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'export_header' => 'top',
'export_field4' => 'grid',
'export_field' => 'grid',
'export_field6' => 'grid',
'export_field5' => 'grid',
'export_field7' => 'grid',
'export_field8' => 'grid',
'export_field9' => 'grid',
'export_field10' => 'grid',
'export_field1' => 'grid',
'export_field2' => 'grid',
'export_field3' => 'grid',
'export_field11' => 'grid',
'export_export' => 'footer',
'export_cancel' => 'footer' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'export_header' => array( 'export_header' ),
'export_export' => array( 'export_export' ),
'export_cancel' => array( 'export_cancel' ),
'export_field' => array( 'export_field1',
'export_field2',
'export_field3',
'export_field',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ) ) ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'export' => array( 'format' => 2,
'selectFields' => false,
'delimiter' => ',',
'selectDelimiter' => false ) );
			$pageArray = array( 'id' => 'export',
'type' => 'export',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'export-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'export-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_field4',
'export_field',
'export_field6',
'export_field5',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field1',
'export_field2',
'export_field3',
'export_field11' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'footer' => array( 'modelId' => 'export-footer',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'export_export',
'export_cancel' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'export_header' => array( 'type' => 'export_header' ),
'export_export' => array( 'type' => 'export_export' ),
'export_cancel' => array( 'type' => 'export_cancel' ),
'export_field1' => array( 'field' => 'external_id',
'type' => 'export_field' ),
'export_field2' => array( 'field' => 'external_system_id',
'type' => 'export_field' ),
'export_field3' => array( 'field' => 'external_table',
'type' => 'export_field' ),
'export_field' => array( 'field' => 'unee_t_unit_type',
'type' => 'export_field' ),
'export_field4' => array( 'field' => 'room_designation',
'type' => 'export_field' ),
'export_field5' => array( 'field' => 'is_obsolete',
'type' => 'export_field' ),
'export_field6' => array( 'field' => 'is_creation_needed_in_unee_t',
'type' => 'export_field' ),
'export_field7' => array( 'field' => 'number_of_beds',
'type' => 'export_field' ),
'export_field8' => array( 'field' => 'surface',
'type' => 'export_field' ),
'export_field9' => array( 'field' => 'surface_measurment_unit',
'type' => 'export_field' ),
'export_field10' => array( 'field' => 'room_description',
'type' => 'export_field' ),
'export_field11' => array( 'field' => 'created_by_id',
'type' => 'export_field' ) ),
'dbProps' => array(  ),
'version' => 2,
'exportFormat' => 2,
'exportDelimiter' => ',',
'exportSelectDelimiter' => false,
'exportSelectFields' => false );
		?>