<?php
			$optionsArray = array( 'captcha' => array( 'captcha' => false ),
'fields' => array( 'gridFields' => array( 'can_see_role_landlord',
'can_see_occupant',
'can_see_role_mgt_cny',
'can_see_role_contractor',
'is_item_removed',
'is_item_moved',
'is_new_item',
'is_new_inventory',
'is_new_ir',
'is_message_from_tenant',
'is_message_from_ll',
'is_message_from_occupant',
'is_message_from_agent',
'is_message_from_mgt_cny',
'is_message_from_contractor',
'is_case_blocker',
'is_case_critical',
'is_case_resolved',
'is_deadline_updated',
'is_next_step_updated',
'is_solution_updated',
'is_invited_to_case',
'can_see_role_tenant',
'is_assigned_to_case',
'is_dashboard_access',
'is_default_invited',
'is_default_assignee',
'is_public',
'order',
'description',
'ut_user_role_type_id',
'is_occupant',
'designation',
'can_see_role_agent',
'is_obsolete',
'id_unee_t_user_type',
'is_all_unit',
'is_all_units_in_country',
'is_all_units_in_area',
'is_all_units_in_level_1',
'is_all_units_in_level_2',
'syst_created_datetime',
'creation_system_id',
'created_by_id',
'creation_method',
'syst_updated_datetime',
'update_system_id',
'updated_by_id',
'update_method',
'organization_id',
'role_type',
'is_any_new_message' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'updateOnEditFields' => array(  ),
'fieldItems' => array( 'can_see_role_landlord' => array( 'integrated_edit_field12' ),
'can_see_occupant' => array( 'integrated_edit_field11' ),
'can_see_role_mgt_cny' => array( 'integrated_edit_field10' ),
'can_see_role_contractor' => array( 'integrated_edit_field8' ),
'is_item_removed' => array( 'integrated_edit_field34' ),
'is_item_moved' => array( 'integrated_edit_field33' ),
'is_new_item' => array( 'integrated_edit_field32' ),
'is_new_inventory' => array( 'integrated_edit_field31' ),
'is_new_ir' => array( 'integrated_edit_field30' ),
'is_message_from_tenant' => array( 'integrated_edit_field28' ),
'is_message_from_ll' => array( 'integrated_edit_field27' ),
'is_message_from_occupant' => array( 'integrated_edit_field26' ),
'is_message_from_agent' => array( 'integrated_edit_field25' ),
'is_message_from_mgt_cny' => array( 'integrated_edit_field24' ),
'is_message_from_contractor' => array( 'integrated_edit_field23' ),
'is_case_blocker' => array( 'integrated_edit_field22' ),
'is_case_critical' => array( 'integrated_edit_field21' ),
'is_case_resolved' => array( 'integrated_edit_field20' ),
'is_deadline_updated' => array( 'integrated_edit_field19' ),
'is_next_step_updated' => array( 'integrated_edit_field18' ),
'is_solution_updated' => array( 'integrated_edit_field17' ),
'is_invited_to_case' => array( 'integrated_edit_field16' ),
'can_see_role_tenant' => array( 'integrated_edit_field14' ),
'is_assigned_to_case' => array( 'integrated_edit_field15' ),
'is_dashboard_access' => array( 'integrated_edit_field5' ),
'is_default_invited' => array( 'integrated_edit_field4' ),
'is_default_assignee' => array( 'integrated_edit_field3' ),
'is_public' => array( 'integrated_edit_field2' ),
'order' => array( 'integrated_edit_field6' ),
'description' => array( 'integrated_edit_field9' ),
'ut_user_role_type_id' => array( 'integrated_edit_field1' ),
'is_occupant' => array( 'integrated_edit_field7' ),
'designation' => array( 'integrated_edit_field' ),
'can_see_role_agent' => array( 'integrated_edit_field13' ),
'is_obsolete' => array( 'integrated_edit_field29' ),
'id_unee_t_user_type' => array( 'integrated_edit_field35' ),
'is_all_unit' => array( 'integrated_edit_field36' ),
'is_all_units_in_country' => array( 'integrated_edit_field37' ),
'is_all_units_in_area' => array( 'integrated_edit_field38' ),
'is_all_units_in_level_1' => array( 'integrated_edit_field39' ),
'is_all_units_in_level_2' => array( 'integrated_edit_field40' ),
'syst_created_datetime' => array( 'integrated_edit_field41' ),
'creation_system_id' => array( 'integrated_edit_field42' ),
'created_by_id' => array( 'integrated_edit_field43' ),
'creation_method' => array( 'integrated_edit_field44' ),
'syst_updated_datetime' => array( 'integrated_edit_field45' ),
'update_system_id' => array( 'integrated_edit_field46' ),
'updated_by_id' => array( 'integrated_edit_field47' ),
'update_method' => array( 'integrated_edit_field48' ),
'organization_id' => array( 'integrated_edit_field49' ),
'role_type' => array( 'integrated_edit_field50' ),
'is_any_new_message' => array( 'integrated_edit_field51' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => true,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array( 'image',
'logo',
'menu' ),
'top' => array( 'edit_header' ),
'above-grid' => array( 'edit_message',
'breadcrumb' ),
'below-grid' => array( 'edit_save',
'edit_back_list',
'edit_close',
'hamburger' ),
'grid' => array( 'section2',
'section1',
'section',
'section3',
'section4',
'integrated_edit_field41',
'integrated_edit_field42',
'integrated_edit_field43',
'integrated_edit_field44',
'integrated_edit_field45',
'integrated_edit_field46',
'integrated_edit_field47',
'integrated_edit_field48',
'integrated_edit_field49',
'integrated_edit_field50',
'integrated_edit_field51' ),
'section7' => array( 'integrated_edit_field',
'integrated_edit_field7',
'integrated_edit_field9',
'integrated_edit_field2',
'integrated_edit_field3',
'integrated_edit_field4',
'integrated_edit_field1',
'integrated_edit_field35',
'integrated_edit_field5',
'integrated_edit_field6',
'integrated_edit_field29' ),
'section' => array( 'tabs' ),
'section2' => array( 'integrated_edit_field15',
'integrated_edit_field16',
'integrated_edit_field17',
'integrated_edit_field19',
'integrated_edit_field20',
'integrated_edit_field18' ),
'section3' => array( 'integrated_edit_field24',
'integrated_edit_field23',
'integrated_edit_field28',
'integrated_edit_field25',
'integrated_edit_field26',
'integrated_edit_field27' ),
'section4' => array( 'integrated_edit_field30' ),
'section5' => array( 'integrated_edit_field31',
'integrated_edit_field34',
'integrated_edit_field33',
'integrated_edit_field32' ),
'section1' => array( 'integrated_edit_field14',
'integrated_edit_field10',
'integrated_edit_field11',
'integrated_edit_field8',
'integrated_edit_field12',
'integrated_edit_field13' ),
'section6' => array( 'integrated_edit_field21',
'integrated_edit_field22' ),
'section8' => array( 'integrated_edit_field36',
'integrated_edit_field40',
'integrated_edit_field39',
'integrated_edit_field38',
'integrated_edit_field37' ) ),
'formXtTags' => array( 'above-grid' => array( 'message_block',
'breadcrumb' ) ),
'itemForms' => array( 'image' => 'supertop',
'logo' => 'supertop',
'menu' => 'supertop',
'edit_header' => 'top',
'edit_message' => 'above-grid',
'breadcrumb' => 'above-grid',
'edit_save' => 'below-grid',
'edit_back_list' => 'below-grid',
'edit_close' => 'below-grid',
'hamburger' => 'below-grid',
'section2' => 'grid',
'section1' => 'grid',
'section' => 'grid',
'section3' => 'grid',
'section4' => 'grid',
'integrated_edit_field41' => 'grid',
'integrated_edit_field42' => 'grid',
'integrated_edit_field43' => 'grid',
'integrated_edit_field44' => 'grid',
'integrated_edit_field45' => 'grid',
'integrated_edit_field46' => 'grid',
'integrated_edit_field47' => 'grid',
'integrated_edit_field48' => 'grid',
'integrated_edit_field49' => 'grid',
'integrated_edit_field50' => 'grid',
'integrated_edit_field51' => 'grid',
'integrated_edit_field' => 'section7',
'integrated_edit_field7' => 'section7',
'integrated_edit_field9' => 'section7',
'integrated_edit_field2' => 'section7',
'integrated_edit_field3' => 'section7',
'integrated_edit_field4' => 'section7',
'integrated_edit_field1' => 'section7',
'integrated_edit_field35' => 'section7',
'integrated_edit_field5' => 'section7',
'integrated_edit_field6' => 'section7',
'integrated_edit_field29' => 'section7',
'tabs' => 'section',
'integrated_edit_field15' => 'section2',
'integrated_edit_field16' => 'section2',
'integrated_edit_field17' => 'section2',
'integrated_edit_field19' => 'section2',
'integrated_edit_field20' => 'section2',
'integrated_edit_field18' => 'section2',
'integrated_edit_field24' => 'section3',
'integrated_edit_field23' => 'section3',
'integrated_edit_field28' => 'section3',
'integrated_edit_field25' => 'section3',
'integrated_edit_field26' => 'section3',
'integrated_edit_field27' => 'section3',
'integrated_edit_field30' => 'section4',
'integrated_edit_field31' => 'section5',
'integrated_edit_field34' => 'section5',
'integrated_edit_field33' => 'section5',
'integrated_edit_field32' => 'section5',
'integrated_edit_field14' => 'section1',
'integrated_edit_field10' => 'section1',
'integrated_edit_field11' => 'section1',
'integrated_edit_field8' => 'section1',
'integrated_edit_field12' => 'section1',
'integrated_edit_field13' => 'section1',
'integrated_edit_field21' => 'section6',
'integrated_edit_field22' => 'section6',
'integrated_edit_field36' => 'section8',
'integrated_edit_field40' => 'section8',
'integrated_edit_field39' => 'section8',
'integrated_edit_field38' => 'section8',
'integrated_edit_field37' => 'section8' ),
'itemLocations' => array( 'section2' => array( 'location' => 'grid',
'cellId' => 'c6' ),
'section1' => array( 'location' => 'grid',
'cellId' => 'c7' ),
'section' => array( 'location' => 'grid',
'cellId' => 'c9' ),
'section3' => array( 'location' => 'grid',
'cellId' => 'c' ),
'section4' => array( 'location' => 'grid',
'cellId' => 'c8' ),
'integrated_edit_field41' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field42' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field43' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field44' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field45' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field46' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field47' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field48' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field49' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field50' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field51' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field' => array( 'location' => 'section7',
'cellId' => 'c1' ),
'integrated_edit_field7' => array( 'location' => 'section7',
'cellId' => 'c2' ),
'integrated_edit_field9' => array( 'location' => 'section7',
'cellId' => 'c4' ),
'integrated_edit_field2' => array( 'location' => 'section7',
'cellId' => 'c8' ),
'integrated_edit_field3' => array( 'location' => 'section7',
'cellId' => 'c9' ),
'integrated_edit_field4' => array( 'location' => 'section7',
'cellId' => 'c10' ),
'integrated_edit_field1' => array( 'location' => 'section7',
'cellId' => 'c3' ),
'integrated_edit_field35' => array( 'location' => 'section7',
'cellId' => 'c12' ),
'integrated_edit_field5' => array( 'location' => 'section7',
'cellId' => 'c13' ),
'integrated_edit_field6' => array( 'location' => 'section7',
'cellId' => 'c14' ),
'integrated_edit_field29' => array( 'location' => 'section7',
'cellId' => 'c14' ),
'tabs' => array( 'location' => 'section',
'cellId' => 'c1' ),
'integrated_edit_field15' => array( 'location' => 'section2',
'cellId' => 'c1' ),
'integrated_edit_field16' => array( 'location' => 'section2',
'cellId' => 'c' ),
'integrated_edit_field17' => array( 'location' => 'section2',
'cellId' => 'c4' ),
'integrated_edit_field19' => array( 'location' => 'section2',
'cellId' => 'c5' ),
'integrated_edit_field20' => array( 'location' => 'section2',
'cellId' => 'c6' ),
'integrated_edit_field18' => array( 'location' => 'section2',
'cellId' => 'c8' ),
'integrated_edit_field24' => array( 'location' => 'section3',
'cellId' => 'c1' ),
'integrated_edit_field23' => array( 'location' => 'section3',
'cellId' => 'c' ),
'integrated_edit_field28' => array( 'location' => 'section3',
'cellId' => 'c3' ),
'integrated_edit_field25' => array( 'location' => 'section3',
'cellId' => 'c4' ),
'integrated_edit_field26' => array( 'location' => 'section3',
'cellId' => 'c5' ),
'integrated_edit_field27' => array( 'location' => 'section3',
'cellId' => 'c6' ),
'integrated_edit_field30' => array( 'location' => 'section4',
'cellId' => 'c1' ),
'integrated_edit_field31' => array( 'location' => 'section5',
'cellId' => 'c1' ),
'integrated_edit_field34' => array( 'location' => 'section5',
'cellId' => 'c' ),
'integrated_edit_field33' => array( 'location' => 'section5',
'cellId' => 'c2' ),
'integrated_edit_field32' => array( 'location' => 'section5',
'cellId' => 'c3' ),
'integrated_edit_field14' => array( 'location' => 'section1',
'cellId' => 'c1' ),
'integrated_edit_field10' => array( 'location' => 'section1',
'cellId' => 'c' ),
'integrated_edit_field11' => array( 'location' => 'section1',
'cellId' => 'c2' ),
'integrated_edit_field8' => array( 'location' => 'section1',
'cellId' => 'c3' ),
'integrated_edit_field12' => array( 'location' => 'section1',
'cellId' => 'c4' ),
'integrated_edit_field13' => array( 'location' => 'section1',
'cellId' => 'c5' ),
'integrated_edit_field21' => array( 'location' => 'section6',
'cellId' => 'c1' ),
'integrated_edit_field22' => array( 'location' => 'section6',
'cellId' => 'c' ),
'integrated_edit_field36' => array( 'location' => 'section8',
'cellId' => 'c1' ),
'integrated_edit_field40' => array( 'location' => 'section8',
'cellId' => 'c' ),
'integrated_edit_field39' => array( 'location' => 'section8',
'cellId' => 'c2' ),
'integrated_edit_field38' => array( 'location' => 'section8',
'cellId' => 'c3' ),
'integrated_edit_field37' => array( 'location' => 'section8',
'cellId' => 'c4' ) ),
'itemVisiblity' => array( 'menu' => 3 ) ),
'itemsByType' => array( 'edit_header' => array( 'edit_header' ),
'edit_message' => array( 'edit_message' ),
'edit_save' => array( 'edit_save' ),
'edit_back_list' => array( 'edit_back_list' ),
'edit_close' => array( 'edit_close' ),
'hamburger' => array( 'hamburger' ),
'edit_reset' => array( 'edit_reset' ),
'integrated_edit_field' => array( 'integrated_edit_field12',
'integrated_edit_field11',
'integrated_edit_field10',
'integrated_edit_field8',
'integrated_edit_field34',
'integrated_edit_field33',
'integrated_edit_field32',
'integrated_edit_field31',
'integrated_edit_field30',
'integrated_edit_field28',
'integrated_edit_field27',
'integrated_edit_field26',
'integrated_edit_field25',
'integrated_edit_field24',
'integrated_edit_field23',
'integrated_edit_field22',
'integrated_edit_field21',
'integrated_edit_field20',
'integrated_edit_field19',
'integrated_edit_field18',
'integrated_edit_field17',
'integrated_edit_field16',
'integrated_edit_field14',
'integrated_edit_field15',
'integrated_edit_field5',
'integrated_edit_field4',
'integrated_edit_field3',
'integrated_edit_field2',
'integrated_edit_field6',
'integrated_edit_field9',
'integrated_edit_field1',
'integrated_edit_field7',
'integrated_edit_field',
'integrated_edit_field13',
'integrated_edit_field29',
'integrated_edit_field35',
'integrated_edit_field36',
'integrated_edit_field37',
'integrated_edit_field38',
'integrated_edit_field39',
'integrated_edit_field40',
'integrated_edit_field41',
'integrated_edit_field42',
'integrated_edit_field43',
'integrated_edit_field44',
'integrated_edit_field45',
'integrated_edit_field46',
'integrated_edit_field47',
'integrated_edit_field48',
'integrated_edit_field49',
'integrated_edit_field50',
'integrated_edit_field51' ),
'breadcrumb' => array( 'breadcrumb' ),
'logo' => array( 'logo' ),
'menu' => array( 'menu' ),
'section' => array( 'section1',
'section',
'section2',
'section3',
'section4' ),
'tabs' => array( 'tabs' ),
'image' => array( 'image' ),
'edit_view' => array( 'edit_view' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'c6' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'section2' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c8' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'section4' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c7' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'section1' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c9' => array( 'cols' => array( 0 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'section' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 0 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array( 'section3' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c3' => array( 'cols' => array( 0 ),
'rows' => array( 5 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field41',
'integrated_edit_field42',
'integrated_edit_field43',
'integrated_edit_field44',
'integrated_edit_field45',
'integrated_edit_field46',
'integrated_edit_field47',
'integrated_edit_field48',
'integrated_edit_field49',
'integrated_edit_field50',
'integrated_edit_field51' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 6 ),
'section7' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c3' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field1' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c2' => array( 'cols' => array( 2 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field7' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c8' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field2' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c9' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field3' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c10' => array( 'cols' => array( 2 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field4' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c12' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field35' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c13' => array( 'cols' => array( 1 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field5' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c14' => array( 'cols' => array( 2 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field6',
'integrated_edit_field29' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c4' => array( 'cols' => array( 0,
1,
2 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field9' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 3,
'height' => 4 ),
'section' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'tabs' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ),
'section2' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0,
1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field15' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 2,
3 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field16' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c4' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field17' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c8' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field18' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c5' => array( 'cols' => array( 2 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field19' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c6' => array( 'cols' => array( 3 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field20' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 4,
'height' => 2 ),
'section3' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field24' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c5' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field26' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c3' => array( 'cols' => array( 2 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field28' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field23' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c4' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field25' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c6' => array( 'cols' => array( 2 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field27' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 3,
'height' => 2 ),
'section4' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field30' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ),
'section5' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field31' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c3' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field32' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c2' => array( 'cols' => array( 2 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field33' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 3 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field34' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 4,
'height' => 1 ),
'section1' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field14' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c2' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field11' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 2 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field10' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c3' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field8' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c4' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field12' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c5' => array( 'cols' => array( 2 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field13' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 3,
'height' => 2 ),
'section6' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field21' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field22' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 2,
'height' => 1 ),
'section8' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field36' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c4' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field37' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c3' => array( 'cols' => array( 2 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field38' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c2' => array( 'cols' => array( 3 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field39' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 4 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field40' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 5,
'height' => 1 ) ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ) ) ),
'misc' => array( 'type' => 'edit',
'breadcrumb' => true,
'nextPrev' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'edit' => array( 'updateSelected' => false ) );
			$pageArray = array( 'id' => 'edit',
'type' => 'edit',
'layoutId' => 'topbar',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'topbar-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ),
array( 'cell' => 'c3' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'image',
'logo' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'menu' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c3' => array( 'model' => 'c3',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'edit-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'edit_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'above-grid' => array( 'modelId' => 'edit-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'edit_message' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'breadcrumb' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'edit-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'edit_save',
'edit_back_list',
'edit_close' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'hamburger' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c6',
'colspan' => 1 ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c8' ) ) ),
array( 'cells' => array( array( 'cell' => 'c7',
'colspan' => 1 ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c9',
'colspan' => 1 ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c' ) ) ),
array( 'cells' => array( array( 'cell' => 'c3' ) ),
'section' => '' ) ),
'cells' => array( 'c6' => array( 'model' => 'c3',
'items' => array( 'section2' ) ),
'c7' => array( 'model' => 'c3',
'items' => array( 'section1' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c9' => array( 'model' => 'c3',
'items' => array( 'section' ) ),
'c' => array( 'model' => 'c3',
'items' => array( 'section3' ) ),
'c8' => array( 'model' => 'c3',
'items' => array( 'section4' ) ),
'c3' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field41',
'integrated_edit_field42',
'integrated_edit_field43',
'integrated_edit_field44',
'integrated_edit_field45',
'integrated_edit_field46',
'integrated_edit_field47',
'integrated_edit_field48',
'integrated_edit_field49',
'integrated_edit_field50',
'integrated_edit_field51' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section7' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c3' ),
array( 'cell' => 'c2' ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c8' ),
array( 'cell' => 'c9' ),
array( 'cell' => 'c10' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c12' ),
array( 'cell' => 'c13' ),
array( 'cell' => 'c14' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c4',
'colspan' => 3 ) ) ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field7' ),
'align' => 'center' ),
'c4' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field9' ) ),
'c8' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field2' ),
'align' => 'center' ),
'c9' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field3' ),
'align' => 'center' ),
'c10' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field4' ),
'align' => 'center' ),
'c3' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field1' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c12' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field35' ),
'align' => 'center' ),
'c13' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field5' ),
'align' => 'center' ),
'c14' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field6',
'integrated_edit_field29' ),
'align' => 'center' ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'tabs' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section2' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1',
'colspan' => 2 ),
array( 'cell' => 'c',
'colspan' => 2 ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c4' ),
array( 'cell' => 'c8' ),
array( 'cell' => 'c5' ),
array( 'cell' => 'c6' ) ) ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field15' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0,
'align' => 'center' ),
'c' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field16' ),
'align' => 'center' ),
'c4' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field17' ),
'align' => 'center' ),
'c5' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field19' ),
'align' => 'center' ),
'c6' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field20' ),
'align' => 'center' ),
'c8' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field18' ),
'align' => 'center' ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section3' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c5' ),
array( 'cell' => 'c3' ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c' ),
array( 'cell' => 'c4' ),
array( 'cell' => 'c6' ) ) ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field24' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0,
'align' => 'center' ),
'c' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field23' ),
'align' => 'center' ),
'c3' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field28' ),
'align' => 'center' ),
'c4' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field25' ),
'align' => 'center' ),
'c5' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field26' ),
'align' => 'center' ),
'c6' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field27' ),
'align' => 'center' ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section4' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field30' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0,
'align' => 'center' ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section5' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c3' ),
array( 'cell' => 'c2' ),
array( 'cell' => 'c' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field31' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0,
'align' => 'center' ),
'c' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field34' ),
'align' => 'center' ),
'c2' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field33' ),
'align' => 'center' ),
'c3' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field32' ),
'align' => 'center' ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section1' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ),
array( 'cell' => 'c' ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c3' ),
array( 'cell' => 'c4' ),
array( 'cell' => 'c5' ) ) ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field14' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0,
'align' => 'center' ),
'c' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field10' ),
'align' => 'center' ),
'c2' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field11' ),
'align' => 'center' ),
'c3' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field8' ),
'align' => 'center' ),
'c4' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field12' ),
'align' => 'center' ),
'c5' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field13' ),
'align' => 'center' ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section6' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field21' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0,
'align' => 'center' ),
'c' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field22' ),
'align' => 'center' ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section8' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c4' ),
array( 'cell' => 'c3' ),
array( 'cell' => 'c2' ),
array( 'cell' => 'c' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field36' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field40' ) ),
'c2' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field39' ) ),
'c3' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field38' ) ),
'c4' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field37' ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ) ),
'items' => array( 'edit_header' => array( 'type' => 'edit_header' ),
'edit_message' => array( 'type' => 'edit_message' ),
'edit_save' => array( 'type' => 'edit_save' ),
'edit_back_list' => array( 'type' => 'edit_back_list' ),
'edit_close' => array( 'type' => 'edit_close' ),
'hamburger' => array( 'type' => 'hamburger',
'items' => array( 'edit_reset',
'edit_view' ) ),
'edit_reset' => array( 'type' => 'edit_reset' ),
'integrated_edit_field12' => array( 'field' => 'can_see_role_landlord',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field11' => array( 'field' => 'can_see_occupant',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field10' => array( 'field' => 'can_see_role_mgt_cny',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'breadcrumb' => array( 'type' => 'breadcrumb' ),
'logo' => array( 'type' => 'logo' ),
'menu' => array( 'type' => 'menu' ),
'integrated_edit_field8' => array( 'field' => 'can_see_role_contractor',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'section1' => array( 'type' => 'section',
'title' => array( 'text' => 'Ability to Invite other PUBLIC users',
'type' => 0 ),
'location' => 'section1',
'label' => array( 'text' => 'Ability to Invite other PUBLIC users',
'type' => 0 ) ),
'integrated_edit_field34' => array( 'field' => 'is_item_removed',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field33' => array( 'field' => 'is_item_moved',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field32' => array( 'field' => 'is_new_item',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field31' => array( 'field' => 'is_new_inventory',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field30' => array( 'field' => 'is_new_ir',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field28' => array( 'field' => 'is_message_from_tenant',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field27' => array( 'field' => 'is_message_from_ll',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field26' => array( 'field' => 'is_message_from_occupant',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field25' => array( 'field' => 'is_message_from_agent',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field24' => array( 'field' => 'is_message_from_mgt_cny',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field23' => array( 'field' => 'is_message_from_contractor',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field22' => array( 'field' => 'is_case_blocker',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'is_case_blocker',
'table' => 'Manage User Types',
'type' => 3 ),
'updateOnEdit' => false ),
'integrated_edit_field21' => array( 'field' => 'is_case_critical',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'is_case_critical',
'table' => 'Manage User Types',
'type' => 3 ),
'updateOnEdit' => false ),
'integrated_edit_field20' => array( 'field' => 'is_case_resolved',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false,
'label' => array( 'field' => 'is_case_resolved',
'table' => 'Manage User Types',
'type' => 3 ) ),
'integrated_edit_field19' => array( 'field' => 'is_deadline_updated',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false,
'label' => array( 'field' => 'is_deadline_updated',
'table' => 'Manage User Types',
'type' => 3 ) ),
'integrated_edit_field18' => array( 'field' => 'is_next_step_updated',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false,
'label' => array( 'field' => 'is_next_step_updated',
'table' => 'Manage User Types',
'type' => 3 ) ),
'integrated_edit_field17' => array( 'field' => 'is_solution_updated',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false,
'label' => array( 'field' => 'is_solution_updated',
'table' => 'Manage User Types',
'type' => 3 ) ),
'integrated_edit_field16' => array( 'field' => 'is_invited_to_case',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false,
'label' => array( 'field' => 'is_invited_to_case',
'table' => 'Manage User Types',
'type' => 3 ) ),
'integrated_edit_field14' => array( 'field' => 'can_see_role_tenant',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field15' => array( 'field' => 'is_assigned_to_case',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false,
'label' => array( 'field' => 'is_assigned_to_case',
'table' => 'Manage User Types',
'type' => 3 ) ),
'tabs' => array( 'type' => 'tabs',
'titles' => array( array( 'text' => 'The Case has changed',
'type' => 0 ),
array( 'text' => 'New Messages',
'type' => 0 ),
array( 'text' => 'Inspection Reports',
'type' => 0 ),
array( 'text' => 'Inventories and Items',
'type' => 0 ) ),
'locations' => array( 'section2',
'section3',
'section4',
'section5' ) ),
'section' => array( 'type' => 'section',
'title' => array( 'text' => 'Notifications',
'type' => 0 ),
'location' => 'section',
'label' => array( 'text' => 'Notifications',
'type' => 0 ) ),
'integrated_edit_field5' => array( 'field' => 'is_dashboard_access',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field4' => array( 'field' => 'is_default_invited',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field3' => array( 'field' => 'is_default_assignee',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field2' => array( 'field' => 'is_public',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field6' => array( 'field' => 'order',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field9' => array( 'field' => 'description',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field1' => array( 'field' => 'ut_user_role_type_id',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field7' => array( 'field' => 'is_occupant',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field' => array( 'field' => 'designation',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'section2' => array( 'type' => 'section',
'title' => array( 'text' => 'About this User Role',
'type' => 0 ),
'location' => 'section7',
'label' => array( 'text' => 'About this User Role',
'type' => 0 ) ),
'integrated_edit_field13' => array( 'field' => 'can_see_role_agent',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field29' => array( 'field' => 'is_obsolete',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'section3' => array( 'type' => 'section',
'title' => array( 'text' => 'Override - Notify me of everything if the case is',
'type' => 0 ),
'location' => 'section6',
'label' => array( 'text' => 'Override - Notify me of everything if the case is',
'type' => 0 ) ),
'integrated_edit_field35' => array( 'field' => 'id_unee_t_user_type',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'id_unee_t_user_type',
'table' => 'Manage User Types',
'type' => 3 ) ),
'image' => array( 'type' => 'image',
'imagePath' => 'Unee-T Enterprise160x50.png' ),
'integrated_edit_field36' => array( 'field' => 'is_all_unit',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false,
'tooltip' => array( 'field' => 'is_all_unit',
'table' => 'Manage User Types',
'type' => 4 ) ),
'integrated_edit_field37' => array( 'field' => 'is_all_units_in_country',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field38' => array( 'field' => 'is_all_units_in_area',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field39' => array( 'field' => 'is_all_units_in_level_1',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field40' => array( 'field' => 'is_all_units_in_level_2',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'section4' => array( 'type' => 'section',
'title' => array( 'text' => 'Automatically assign to',
'type' => 0 ),
'location' => 'section8',
'label' => array( 'text' => 'Automatically assign to',
'type' => 0 ) ),
'integrated_edit_field41' => array( 'field' => 'syst_created_datetime',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field42' => array( 'field' => 'creation_system_id',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field43' => array( 'field' => 'created_by_id',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field44' => array( 'field' => 'creation_method',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field45' => array( 'field' => 'syst_updated_datetime',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field46' => array( 'field' => 'update_system_id',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field47' => array( 'field' => 'updated_by_id',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field48' => array( 'field' => 'update_method',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field49' => array( 'field' => 'organization_id',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field50' => array( 'field' => 'role_type',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field51' => array( 'field' => 'is_any_new_message',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'edit_view' => array( 'type' => 'edit_view' ) ),
'dbProps' => array(  ),
'version' => 2,
'fixedTopbar' => true );
		?>