<?php
			$optionsArray = array( 'captcha' => array( 'captcha' => false ),
'fields' => array( 'gridFields' => array( 'is_occupant',
'ut_user_role_type_id',
'description',
'order',
'is_public',
'is_case_critical',
'is_new_item',
'is_item_moved',
'is_item_removed',
'is_new_inventory',
'is_new_ir',
'is_message_from_ll',
'is_message_from_occupant',
'is_message_from_agent',
'is_message_from_tenant',
'is_message_from_contractor',
'is_message_from_mgt_cny',
'is_next_step_updated',
'is_case_resolved',
'is_deadline_updated',
'is_solution_updated',
'is_invited_to_case',
'is_assigned_to_case',
'can_see_role_agent',
'can_see_role_landlord',
'can_see_role_contractor',
'can_see_occupant',
'is_default_assignee',
'can_see_role_mgt_cny',
'can_see_role_tenant',
'is_obsolete',
'is_dashboard_access',
'is_invited_all_cases',
'designation',
'is_case_blocker' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'is_occupant' => array( 'integrated_edit_field7' ),
'ut_user_role_type_id' => array( 'integrated_edit_field1' ),
'description' => array( 'integrated_edit_field9' ),
'order' => array( 'integrated_edit_field6' ),
'is_public' => array( 'integrated_edit_field2' ),
'is_case_critical' => array( 'integrated_edit_field21' ),
'is_new_item' => array( 'integrated_edit_field32' ),
'is_item_moved' => array( 'integrated_edit_field33' ),
'is_item_removed' => array( 'integrated_edit_field34' ),
'is_new_inventory' => array( 'integrated_edit_field31' ),
'is_new_ir' => array( 'integrated_edit_field30' ),
'is_message_from_ll' => array( 'integrated_edit_field27' ),
'is_message_from_occupant' => array( 'integrated_edit_field26' ),
'is_message_from_agent' => array( 'integrated_edit_field25' ),
'is_message_from_tenant' => array( 'integrated_edit_field28' ),
'is_message_from_contractor' => array( 'integrated_edit_field23' ),
'is_message_from_mgt_cny' => array( 'integrated_edit_field24' ),
'is_next_step_updated' => array( 'integrated_edit_field18' ),
'is_case_resolved' => array( 'integrated_edit_field20' ),
'is_deadline_updated' => array( 'integrated_edit_field19' ),
'is_solution_updated' => array( 'integrated_edit_field17' ),
'is_invited_to_case' => array( 'integrated_edit_field16' ),
'is_assigned_to_case' => array( 'integrated_edit_field15' ),
'can_see_role_agent' => array( 'integrated_edit_field13' ),
'can_see_role_landlord' => array( 'integrated_edit_field12' ),
'can_see_role_contractor' => array( 'integrated_edit_field8' ),
'can_see_occupant' => array( 'integrated_edit_field11' ),
'is_default_assignee' => array( 'integrated_edit_field3' ),
'can_see_role_mgt_cny' => array( 'integrated_edit_field10' ),
'can_see_role_tenant' => array( 'integrated_edit_field14' ),
'is_obsolete' => array( 'integrated_edit_field29' ),
'is_dashboard_access' => array( 'integrated_edit_field5' ),
'is_invited_all_cases' => array( 'integrated_edit_field4' ),
'designation' => array( 'integrated_edit_field' ),
'is_case_blocker' => array( 'integrated_edit_field22' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array( 'logo',
'menu' ),
'top' => array( 'add_header' ),
'above-grid' => array( 'add_message',
'breadcrumb' ),
'below-grid' => array( 'add_save',
'add_back_list',
'add_cancel' ),
'grid' => array( 'section2',
'section1',
'section',
'section3' ),
'section' => array( 'tabs' ),
'section1' => array( 'integrated_edit_field14',
'integrated_edit_field10',
'integrated_edit_field11',
'integrated_edit_field8',
'integrated_edit_field12',
'integrated_edit_field13' ),
'section2' => array( 'integrated_edit_field15',
'integrated_edit_field16',
'integrated_edit_field17',
'integrated_edit_field19',
'integrated_edit_field20',
'integrated_edit_field18' ),
'section3' => array( 'integrated_edit_field24',
'integrated_edit_field23',
'integrated_edit_field28',
'integrated_edit_field25',
'integrated_edit_field26',
'integrated_edit_field27' ),
'section4' => array( 'integrated_edit_field30' ),
'section5' => array( 'integrated_edit_field31',
'integrated_edit_field34',
'integrated_edit_field33',
'integrated_edit_field32' ),
'section7' => array( 'integrated_edit_field',
'integrated_edit_field7',
'integrated_edit_field1',
'integrated_edit_field9',
'integrated_edit_field6',
'integrated_edit_field2',
'integrated_edit_field3',
'integrated_edit_field4',
'integrated_edit_field5',
'integrated_edit_field29' ),
'section6' => array( 'integrated_edit_field21',
'integrated_edit_field22' ) ),
'formXtTags' => array( 'above-grid' => array( 'message_block',
'breadcrumb' ) ),
'itemForms' => array( 'logo' => 'supertop',
'menu' => 'supertop',
'add_header' => 'top',
'add_message' => 'above-grid',
'breadcrumb' => 'above-grid',
'add_save' => 'below-grid',
'add_back_list' => 'below-grid',
'add_cancel' => 'below-grid',
'section2' => 'grid',
'section1' => 'grid',
'section' => 'grid',
'section3' => 'grid',
'tabs' => 'section',
'integrated_edit_field14' => 'section1',
'integrated_edit_field10' => 'section1',
'integrated_edit_field11' => 'section1',
'integrated_edit_field8' => 'section1',
'integrated_edit_field12' => 'section1',
'integrated_edit_field13' => 'section1',
'integrated_edit_field15' => 'section2',
'integrated_edit_field16' => 'section2',
'integrated_edit_field17' => 'section2',
'integrated_edit_field19' => 'section2',
'integrated_edit_field20' => 'section2',
'integrated_edit_field18' => 'section2',
'integrated_edit_field24' => 'section3',
'integrated_edit_field23' => 'section3',
'integrated_edit_field28' => 'section3',
'integrated_edit_field25' => 'section3',
'integrated_edit_field26' => 'section3',
'integrated_edit_field27' => 'section3',
'integrated_edit_field30' => 'section4',
'integrated_edit_field31' => 'section5',
'integrated_edit_field34' => 'section5',
'integrated_edit_field33' => 'section5',
'integrated_edit_field32' => 'section5',
'integrated_edit_field' => 'section7',
'integrated_edit_field7' => 'section7',
'integrated_edit_field1' => 'section7',
'integrated_edit_field9' => 'section7',
'integrated_edit_field6' => 'section7',
'integrated_edit_field2' => 'section7',
'integrated_edit_field3' => 'section7',
'integrated_edit_field4' => 'section7',
'integrated_edit_field5' => 'section7',
'integrated_edit_field29' => 'section7',
'integrated_edit_field21' => 'section6',
'integrated_edit_field22' => 'section6' ),
'itemLocations' => array( 'section2' => array( 'location' => 'grid',
'cellId' => 'c6' ),
'section1' => array( 'location' => 'grid',
'cellId' => 'c7' ),
'section' => array( 'location' => 'grid',
'cellId' => 'c9' ),
'section3' => array( 'location' => 'grid',
'cellId' => 'c' ),
'tabs' => array( 'location' => 'section',
'cellId' => 'c1' ),
'integrated_edit_field14' => array( 'location' => 'section1',
'cellId' => 'c1' ),
'integrated_edit_field10' => array( 'location' => 'section1',
'cellId' => 'c' ),
'integrated_edit_field11' => array( 'location' => 'section1',
'cellId' => 'c2' ),
'integrated_edit_field8' => array( 'location' => 'section1',
'cellId' => 'c3' ),
'integrated_edit_field12' => array( 'location' => 'section1',
'cellId' => 'c4' ),
'integrated_edit_field13' => array( 'location' => 'section1',
'cellId' => 'c5' ),
'integrated_edit_field15' => array( 'location' => 'section2',
'cellId' => 'c1' ),
'integrated_edit_field16' => array( 'location' => 'section2',
'cellId' => 'c' ),
'integrated_edit_field17' => array( 'location' => 'section2',
'cellId' => 'c4' ),
'integrated_edit_field19' => array( 'location' => 'section2',
'cellId' => 'c5' ),
'integrated_edit_field20' => array( 'location' => 'section2',
'cellId' => 'c6' ),
'integrated_edit_field18' => array( 'location' => 'section2',
'cellId' => 'c8' ),
'integrated_edit_field24' => array( 'location' => 'section3',
'cellId' => 'c1' ),
'integrated_edit_field23' => array( 'location' => 'section3',
'cellId' => 'c' ),
'integrated_edit_field28' => array( 'location' => 'section3',
'cellId' => 'c3' ),
'integrated_edit_field25' => array( 'location' => 'section3',
'cellId' => 'c4' ),
'integrated_edit_field26' => array( 'location' => 'section3',
'cellId' => 'c5' ),
'integrated_edit_field27' => array( 'location' => 'section3',
'cellId' => 'c6' ),
'integrated_edit_field30' => array( 'location' => 'section4',
'cellId' => 'c1' ),
'integrated_edit_field31' => array( 'location' => 'section5',
'cellId' => 'c1' ),
'integrated_edit_field34' => array( 'location' => 'section5',
'cellId' => 'c' ),
'integrated_edit_field33' => array( 'location' => 'section5',
'cellId' => 'c2' ),
'integrated_edit_field32' => array( 'location' => 'section5',
'cellId' => 'c3' ),
'integrated_edit_field' => array( 'location' => 'section7',
'cellId' => 'c1' ),
'integrated_edit_field7' => array( 'location' => 'section7',
'cellId' => 'c' ),
'integrated_edit_field1' => array( 'location' => 'section7',
'cellId' => 'c2' ),
'integrated_edit_field9' => array( 'location' => 'section7',
'cellId' => 'c4' ),
'integrated_edit_field6' => array( 'location' => 'section7',
'cellId' => 'c6' ),
'integrated_edit_field2' => array( 'location' => 'section7',
'cellId' => 'c8' ),
'integrated_edit_field3' => array( 'location' => 'section7',
'cellId' => 'c9' ),
'integrated_edit_field4' => array( 'location' => 'section7',
'cellId' => 'c10' ),
'integrated_edit_field5' => array( 'location' => 'section7',
'cellId' => 'c11' ),
'integrated_edit_field29' => array( 'location' => 'section7',
'cellId' => 'c7' ),
'integrated_edit_field21' => array( 'location' => 'section6',
'cellId' => 'c1' ),
'integrated_edit_field22' => array( 'location' => 'section6',
'cellId' => 'c' ) ),
'itemVisiblity' => array( 'menu' => 3 ) ),
'itemsByType' => array( 'add_header' => array( 'add_header' ),
'add_message' => array( 'add_message' ),
'add_save' => array( 'add_save' ),
'add_back_list' => array( 'add_back_list' ),
'add_cancel' => array( 'add_cancel' ),
'integrated_edit_field' => array( 'integrated_edit_field7',
'integrated_edit_field1',
'integrated_edit_field9',
'integrated_edit_field6',
'integrated_edit_field2',
'integrated_edit_field21',
'integrated_edit_field32',
'integrated_edit_field33',
'integrated_edit_field34',
'integrated_edit_field31',
'integrated_edit_field30',
'integrated_edit_field27',
'integrated_edit_field26',
'integrated_edit_field25',
'integrated_edit_field28',
'integrated_edit_field23',
'integrated_edit_field24',
'integrated_edit_field18',
'integrated_edit_field20',
'integrated_edit_field19',
'integrated_edit_field17',
'integrated_edit_field16',
'integrated_edit_field15',
'integrated_edit_field13',
'integrated_edit_field12',
'integrated_edit_field8',
'integrated_edit_field11',
'integrated_edit_field3',
'integrated_edit_field10',
'integrated_edit_field14',
'integrated_edit_field29',
'integrated_edit_field5',
'integrated_edit_field4',
'integrated_edit_field',
'integrated_edit_field22' ),
'breadcrumb' => array( 'breadcrumb' ),
'logo' => array( 'logo' ),
'menu' => array( 'menu' ),
'section' => array( 'section2',
'section3',
'section',
'section1' ),
'tabs' => array( 'tabs' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'c6' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'section2' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c7' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'section1' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c9' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'section' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 0 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'section3' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 4 ),
'section' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'tabs' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ),
'section1' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field14' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c2' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field11' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 2 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field10' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c3' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field8' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c4' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field12' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c5' => array( 'cols' => array( 2 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field13' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 3,
'height' => 2 ),
'section2' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0,
1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field15' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 2,
3 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field16' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c4' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field17' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c8' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field18' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c5' => array( 'cols' => array( 2 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field19' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c6' => array( 'cols' => array( 3 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field20' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 4,
'height' => 2 ),
'section3' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field24' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c5' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field26' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c3' => array( 'cols' => array( 2 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field28' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field23' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c4' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field25' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c6' => array( 'cols' => array( 2 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field27' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 3,
'height' => 2 ),
'section4' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field30' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ),
'section5' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field31' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c3' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field32' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c2' => array( 'cols' => array( 2 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field33' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 3 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field34' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 4,
'height' => 1 ),
'section7' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0,
1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c2' => array( 'cols' => array( 2 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field1' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 3 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field7' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c8' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field2' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c9' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field3' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c10' => array( 'cols' => array( 2 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field4' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c11' => array( 'cols' => array( 3 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field5' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c4' => array( 'cols' => array( 0,
1 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field9' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c6' => array( 'cols' => array( 2 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field6' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c7' => array( 'cols' => array( 3 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field29' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 4,
'height' => 3 ),
'section6' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field21' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field22' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 2,
'height' => 1 ) ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ) ) ),
'misc' => array( 'type' => 'add',
'breadcrumb' => true ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'add',
'type' => 'add',
'layoutId' => 'topbar',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'topbar-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ),
array( 'cell' => 'c3' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'logo' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'menu' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c3' => array( 'model' => 'c3',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'add-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'add_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'above-grid' => array( 'modelId' => 'add-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'add_message' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'breadcrumb' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'add-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'add_save',
'add_back_list',
'add_cancel' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c6',
'colspan' => 1 ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c7',
'colspan' => 1 ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c9',
'colspan' => 1 ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c' ) ) ) ),
'cells' => array( 'c6' => array( 'model' => 'c3',
'items' => array( 'section2' ) ),
'c7' => array( 'model' => 'c3',
'items' => array( 'section1' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c9' => array( 'model' => 'c3',
'items' => array( 'section' ) ),
'c' => array( 'model' => 'c3',
'items' => array( 'section3' ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'tabs' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section1' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ),
array( 'cell' => 'c' ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c3' ),
array( 'cell' => 'c4' ),
array( 'cell' => 'c5' ) ) ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field14' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field10' ) ),
'c2' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field11' ) ),
'c3' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field8' ) ),
'c4' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field12' ) ),
'c5' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field13' ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section2' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1',
'colspan' => 2 ),
array( 'cell' => 'c',
'colspan' => 2 ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c4' ),
array( 'cell' => 'c8' ),
array( 'cell' => 'c5' ),
array( 'cell' => 'c6' ) ) ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field15' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0,
'align' => 'center' ),
'c' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field16' ),
'align' => 'center' ),
'c4' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field17' ),
'align' => 'center' ),
'c5' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field19' ),
'align' => 'center' ),
'c6' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field20' ),
'align' => 'center' ),
'c8' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field18' ),
'align' => 'center' ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section3' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c5' ),
array( 'cell' => 'c3' ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c' ),
array( 'cell' => 'c4' ),
array( 'cell' => 'c6' ) ) ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field24' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field23' ) ),
'c3' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field28' ) ),
'c4' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field25' ) ),
'c5' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field26' ) ),
'c6' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field27' ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section4' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field30' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0,
'align' => 'center' ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section5' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c3' ),
array( 'cell' => 'c2' ),
array( 'cell' => 'c' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field31' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0,
'align' => 'center' ),
'c' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field34' ),
'align' => 'center' ),
'c2' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field33' ),
'align' => 'center' ),
'c3' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field32' ),
'align' => 'center' ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section7' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1',
'colspan' => 2 ),
array( 'cell' => 'c2' ),
array( 'cell' => 'c' ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c8' ),
array( 'cell' => 'c9' ),
array( 'cell' => 'c10' ),
array( 'cell' => 'c11' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c4',
'colspan' => 2 ),
array( 'cell' => 'c6' ),
array( 'cell' => 'c7' ) ) ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field7' ),
'align' => 'center' ),
'c2' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field1' ) ),
'c4' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field9' ) ),
'c6' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field6' ),
'align' => 'center' ),
'c8' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field2' ),
'align' => 'center' ),
'c9' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field3' ),
'align' => 'center' ),
'c10' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field4' ),
'align' => 'center' ),
'c11' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field5' ),
'align' => 'center' ),
'c7' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field29' ),
'align' => 'center' ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section6' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field21' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field22' ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ) ),
'items' => array( 'add_header' => array( 'type' => 'add_header' ),
'add_message' => array( 'type' => 'add_message' ),
'add_save' => array( 'type' => 'add_save' ),
'add_back_list' => array( 'type' => 'add_back_list' ),
'add_cancel' => array( 'type' => 'add_cancel' ),
'integrated_edit_field7' => array( 'field' => 'is_occupant',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field1' => array( 'field' => 'ut_user_role_type_id',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'breadcrumb' => array( 'type' => 'breadcrumb' ),
'logo' => array( 'type' => 'logo' ),
'menu' => array( 'type' => 'menu' ),
'integrated_edit_field9' => array( 'field' => 'description',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field6' => array( 'field' => 'order',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field2' => array( 'field' => 'is_public',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'section2' => array( 'type' => 'section',
'title' => array( 'text' => 'About this User Role',
'type' => 0 ),
'location' => 'section7',
'label' => array( 'text' => 'About this User Role',
'type' => 0 ) ),
'integrated_edit_field21' => array( 'field' => 'is_case_critical',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'is_case_critical',
'table' => 'Manage User Types',
'type' => 3 ) ),
'section3' => array( 'type' => 'section',
'title' => array( 'text' => 'Override - Notify me of everything if the case is',
'type' => 0 ),
'location' => 'section6',
'label' => array( 'text' => 'Override - Notify me of everything if the case is',
'type' => 0 ) ),
'integrated_edit_field32' => array( 'field' => 'is_new_item',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field33' => array( 'field' => 'is_item_moved',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field34' => array( 'field' => 'is_item_removed',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field31' => array( 'field' => 'is_new_inventory',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field30' => array( 'field' => 'is_new_ir',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field27' => array( 'field' => 'is_message_from_ll',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field26' => array( 'field' => 'is_message_from_occupant',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field25' => array( 'field' => 'is_message_from_agent',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field28' => array( 'field' => 'is_message_from_tenant',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field23' => array( 'field' => 'is_message_from_contractor',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field24' => array( 'field' => 'is_message_from_mgt_cny',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field18' => array( 'field' => 'is_next_step_updated',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false,
'label' => array( 'field' => 'is_next_step_updated',
'table' => 'Manage User Types',
'type' => 3 ) ),
'integrated_edit_field20' => array( 'field' => 'is_case_resolved',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false,
'label' => array( 'field' => 'is_case_resolved',
'table' => 'Manage User Types',
'type' => 3 ) ),
'integrated_edit_field19' => array( 'field' => 'is_deadline_updated',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false,
'label' => array( 'field' => 'is_deadline_updated',
'table' => 'Manage User Types',
'type' => 3 ) ),
'integrated_edit_field17' => array( 'field' => 'is_solution_updated',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false,
'label' => array( 'field' => 'is_solution_updated',
'table' => 'Manage User Types',
'type' => 3 ) ),
'integrated_edit_field16' => array( 'field' => 'is_invited_to_case',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false,
'label' => array( 'field' => 'is_invited_to_case',
'table' => 'Manage User Types',
'type' => 3 ) ),
'integrated_edit_field15' => array( 'field' => 'is_assigned_to_case',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false,
'label' => array( 'field' => 'is_assigned_to_case',
'table' => 'Manage User Types',
'type' => 3 ) ),
'tabs' => array( 'type' => 'tabs',
'titles' => array( array( 'text' => 'The Case has changed',
'type' => 0 ),
array( 'text' => 'New Messages',
'type' => 0 ),
array( 'text' => 'Inspection Reports',
'type' => 0 ),
array( 'text' => 'Inventories and Items',
'type' => 0 ) ),
'locations' => array( 'section2',
'section3',
'section4',
'section5' ) ),
'section' => array( 'type' => 'section',
'title' => array( 'text' => 'Notifications',
'type' => 0 ),
'location' => 'section',
'label' => array( 'text' => 'Notifications',
'type' => 0 ) ),
'integrated_edit_field13' => array( 'field' => 'can_see_role_agent',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field12' => array( 'field' => 'can_see_role_landlord',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field8' => array( 'field' => 'can_see_role_contractor',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field11' => array( 'field' => 'can_see_occupant',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field3' => array( 'field' => 'is_default_assignee',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field10' => array( 'field' => 'can_see_role_mgt_cny',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field14' => array( 'field' => 'can_see_role_tenant',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'section1' => array( 'type' => 'section',
'title' => array( 'text' => 'Ability to Invite other',
'type' => 0 ),
'location' => 'section1',
'label' => array( 'text' => 'Ability to Invite other',
'type' => 0 ) ),
'integrated_edit_field29' => array( 'field' => 'is_obsolete',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field5' => array( 'field' => 'is_dashboard_access',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field4' => array( 'field' => 'is_invited_all_cases',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field' => array( 'field' => 'designation',
'type' => 'integrated_edit_field',
'orientation' => 0,
'bold' => true,
'font-size' => '1.5em' ),
'integrated_edit_field22' => array( 'field' => 'is_case_blocker',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'is_case_blocker',
'table' => 'Manage User Types',
'type' => 3 ) ) ),
'dbProps' => array(  ),
'version' => 2,
'fixedTopbar' => true );
		?>