<?php
			$optionsArray = array( 'captcha' => array( 'captcha' => false ),
'fields' => array( 'gridFields' => array( 'is_case_resolved',
'is_case_critical',
'is_case_blocker',
'is_message_from_contractor',
'is_message_from_mgt_cny',
'is_message_from_agent',
'designation',
'is_assigned_to_case',
'is_invited_to_case',
'is_solution_updated',
'is_next_step_updated',
'is_deadline_updated',
'is_message_from_occupant',
'is_message_from_ll',
'is_message_from_tenant' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'updateOnEditFields' => array(  ),
'fieldItems' => array( 'is_case_resolved' => array( 'integrated_edit_field6' ),
'is_case_critical' => array( 'integrated_edit_field7' ),
'is_case_blocker' => array( 'integrated_edit_field8' ),
'is_message_from_contractor' => array( 'integrated_edit_field9' ),
'is_message_from_mgt_cny' => array( 'integrated_edit_field10' ),
'is_message_from_agent' => array( 'integrated_edit_field11' ),
'designation' => array( 'integrated_edit_field' ),
'is_assigned_to_case' => array( 'integrated_edit_field1' ),
'is_invited_to_case' => array( 'integrated_edit_field2' ),
'is_solution_updated' => array( 'integrated_edit_field3' ),
'is_next_step_updated' => array( 'integrated_edit_field4' ),
'is_deadline_updated' => array( 'integrated_edit_field5' ),
'is_message_from_occupant' => array( 'integrated_edit_field12' ),
'is_message_from_ll' => array( 'integrated_edit_field13' ),
'is_message_from_tenant' => array( 'integrated_edit_field15' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array( 'logo',
'menu' ),
'top' => array( 'edit_header' ),
'above-grid' => array( 'edit_message',
'breadcrumb' ),
'below-grid' => array( 'edit_save',
'edit_back_list',
'edit_close',
'hamburger' ),
'grid' => array( 'section',
'section1',
'integrated_edit_field',
'section2',
'section3' ),
'section' => array( 'integrated_edit_field10',
'integrated_edit_field15',
'integrated_edit_field12',
'integrated_edit_field11',
'integrated_edit_field9',
'integrated_edit_field13' ),
'section1' => array( 'integrated_edit_field3',
'integrated_edit_field6',
'integrated_edit_field4',
'integrated_edit_field5' ),
'section2' => array( 'integrated_edit_field1',
'integrated_edit_field2' ),
'section3' => array( 'integrated_edit_field7',
'integrated_edit_field8' ) ),
'formXtTags' => array( 'above-grid' => array( 'message_block',
'breadcrumb' ) ),
'itemForms' => array( 'logo' => 'supertop',
'menu' => 'supertop',
'edit_header' => 'top',
'edit_message' => 'above-grid',
'breadcrumb' => 'above-grid',
'edit_save' => 'below-grid',
'edit_back_list' => 'below-grid',
'edit_close' => 'below-grid',
'hamburger' => 'below-grid',
'section' => 'grid',
'section1' => 'grid',
'integrated_edit_field' => 'grid',
'section2' => 'grid',
'section3' => 'grid',
'integrated_edit_field10' => 'section',
'integrated_edit_field15' => 'section',
'integrated_edit_field12' => 'section',
'integrated_edit_field11' => 'section',
'integrated_edit_field9' => 'section',
'integrated_edit_field13' => 'section',
'integrated_edit_field3' => 'section1',
'integrated_edit_field6' => 'section1',
'integrated_edit_field4' => 'section1',
'integrated_edit_field5' => 'section1',
'integrated_edit_field1' => 'section2',
'integrated_edit_field2' => 'section2',
'integrated_edit_field7' => 'section3',
'integrated_edit_field8' => 'section3' ),
'itemLocations' => array( 'section' => array( 'location' => 'grid',
'cellId' => 'c11' ),
'section1' => array( 'location' => 'grid',
'cellId' => 'c13' ),
'integrated_edit_field' => array( 'location' => 'grid',
'cellId' => 'c14' ),
'section2' => array( 'location' => 'grid',
'cellId' => 'c15' ),
'section3' => array( 'location' => 'grid',
'cellId' => 'c16' ),
'integrated_edit_field10' => array( 'location' => 'section',
'cellId' => 'c1' ),
'integrated_edit_field15' => array( 'location' => 'section',
'cellId' => 'c3' ),
'integrated_edit_field12' => array( 'location' => 'section',
'cellId' => 'c4' ),
'integrated_edit_field11' => array( 'location' => 'section',
'cellId' => 'c6' ),
'integrated_edit_field9' => array( 'location' => 'section',
'cellId' => 'c7' ),
'integrated_edit_field13' => array( 'location' => 'section',
'cellId' => 'c8' ),
'integrated_edit_field3' => array( 'location' => 'section1',
'cellId' => 'c1' ),
'integrated_edit_field6' => array( 'location' => 'section1',
'cellId' => 'c2' ),
'integrated_edit_field4' => array( 'location' => 'section1',
'cellId' => 'c3' ),
'integrated_edit_field5' => array( 'location' => 'section1',
'cellId' => 'c4' ),
'integrated_edit_field1' => array( 'location' => 'section2',
'cellId' => 'c1' ),
'integrated_edit_field2' => array( 'location' => 'section2',
'cellId' => 'c' ),
'integrated_edit_field7' => array( 'location' => 'section3',
'cellId' => 'c1' ),
'integrated_edit_field8' => array( 'location' => 'section3',
'cellId' => 'c' ) ),
'itemVisiblity' => array( 'menu' => 3 ) ),
'itemsByType' => array( 'edit_header' => array( 'edit_header' ),
'edit_message' => array( 'edit_message' ),
'edit_save' => array( 'edit_save' ),
'edit_back_list' => array( 'edit_back_list' ),
'edit_close' => array( 'edit_close' ),
'hamburger' => array( 'hamburger' ),
'edit_reset' => array( 'edit_reset' ),
'integrated_edit_field' => array( 'integrated_edit_field6',
'integrated_edit_field7',
'integrated_edit_field8',
'integrated_edit_field9',
'integrated_edit_field10',
'integrated_edit_field11',
'integrated_edit_field',
'integrated_edit_field1',
'integrated_edit_field2',
'integrated_edit_field3',
'integrated_edit_field4',
'integrated_edit_field5',
'integrated_edit_field12',
'integrated_edit_field13',
'integrated_edit_field15' ),
'breadcrumb' => array( 'breadcrumb' ),
'logo' => array( 'logo' ),
'menu' => array( 'menu' ),
'section' => array( 'section',
'section1',
'section2',
'section3' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'c10' => array( 'cols' => array( 0,
1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c14' => array( 'cols' => array( 0,
1 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c13' => array( 'cols' => array( 0,
1 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'section1' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c15' => array( 'cols' => array( 0 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'section2' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c16' => array( 'cols' => array( 1 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'section3' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c11' => array( 'cols' => array( 0,
1 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array( 'section' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 2,
'height' => 5 ),
'section' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field10' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c4' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field12' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c3' => array( 'cols' => array( 2 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field15' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c6' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field11' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c7' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field9' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c8' => array( 'cols' => array( 2 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field13' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 3,
'height' => 2 ),
'section1' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field3' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c4' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field5' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c3' => array( 'cols' => array( 2 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field4' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c2' => array( 'cols' => array( 3 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field6' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 4,
'height' => 1 ),
'section2' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field1' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field2' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 2,
'height' => 1 ),
'section3' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field7' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field8' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 2,
'height' => 1 ) ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ) ) ),
'misc' => array( 'type' => 'edit',
'breadcrumb' => true,
'nextPrev' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'edit' => array( 'updateSelected' => false ) );
			$pageArray = array( 'id' => 'edit',
'type' => 'edit',
'layoutId' => 'topbar',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'topbar-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ),
array( 'cell' => 'c3' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'logo' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'menu' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c3' => array( 'model' => 'c3',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'edit-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'edit_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'above-grid' => array( 'modelId' => 'edit-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'edit_message' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'breadcrumb' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'edit-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'edit_save',
'edit_back_list',
'edit_close' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'hamburger' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'section' => '',
'cells' => array( array( 'cell' => 'c10',
'colspan' => 2 ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c14',
'colspan' => 2 ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c13',
'colspan' => 2 ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c15',
'colspan' => 1 ),
array( 'cell' => 'c16',
'colspan' => 1 ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c11',
'colspan' => 2 ) ) ) ),
'cells' => array( 'c10' => array( 'model' => 'c3',
'items' => array(  ) ),
'c11' => array( 'model' => 'c3',
'items' => array( 'section' ) ),
'c13' => array( 'model' => 'c3',
'items' => array( 'section1' ) ),
'c14' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field' ) ),
'c15' => array( 'model' => 'c3',
'items' => array( 'section2' ) ),
'c16' => array( 'model' => 'c3',
'items' => array( 'section3' ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c4' ),
array( 'cell' => 'c3' ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c6' ),
array( 'cell' => 'c7' ),
array( 'cell' => 'c8' ) ) ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field10' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0,
'align' => 'center' ),
'c3' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field15' ),
'align' => 'center' ),
'c4' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field12' ),
'align' => 'center' ),
'c6' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field11' ),
'align' => 'center' ),
'c7' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field9' ),
'align' => 'center' ),
'c8' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field13' ),
'align' => 'center' ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section1' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c4' ),
array( 'cell' => 'c3' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field3' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0,
'align' => 'center' ),
'c2' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field6' ),
'align' => 'center' ),
'c3' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field4' ),
'align' => 'center' ),
'c4' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field5' ),
'align' => 'center' ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section2' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field1' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0,
'align' => 'center' ),
'c' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field2' ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section3' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field7' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0,
'align' => 'center' ),
'c' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field8' ),
'align' => 'center' ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ) ),
'items' => array( 'edit_header' => array( 'type' => 'edit_header' ),
'edit_message' => array( 'type' => 'edit_message' ),
'edit_save' => array( 'type' => 'edit_save' ),
'edit_back_list' => array( 'type' => 'edit_back_list' ),
'edit_close' => array( 'type' => 'edit_close' ),
'hamburger' => array( 'type' => 'hamburger',
'items' => array( 'edit_reset' ) ),
'edit_reset' => array( 'type' => 'edit_reset' ),
'integrated_edit_field6' => array( 'field' => 'is_case_resolved',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false,
'label' => array( 'field' => 'is_case_resolved',
'table' => 'Manage User Default Notifications',
'type' => 3 ) ),
'integrated_edit_field7' => array( 'field' => 'is_case_critical',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false,
'label' => array( 'field' => 'is_case_critical',
'table' => 'Manage User Default Notifications',
'type' => 3 ) ),
'integrated_edit_field8' => array( 'field' => 'is_case_blocker',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false,
'label' => array( 'field' => 'is_case_blocker',
'table' => 'Manage User Default Notifications',
'type' => 3 ) ),
'integrated_edit_field9' => array( 'field' => 'is_message_from_contractor',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false,
'label' => array( 'field' => 'is_message_from_contractor',
'table' => 'Manage User Default Notifications',
'type' => 3 ) ),
'integrated_edit_field10' => array( 'field' => 'is_message_from_mgt_cny',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false,
'label' => array( 'field' => 'is_message_from_mgt_cny',
'table' => 'Manage User Default Notifications',
'type' => 3 ) ),
'integrated_edit_field11' => array( 'field' => 'is_message_from_agent',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false,
'label' => array( 'field' => 'is_message_from_agent',
'table' => 'Manage User Default Notifications',
'type' => 3 ) ),
'breadcrumb' => array( 'type' => 'breadcrumb' ),
'logo' => array( 'type' => 'logo' ),
'menu' => array( 'type' => 'menu' ),
'integrated_edit_field' => array( 'field' => 'designation',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false,
'font-size' => '1.5em',
'bold' => true ),
'integrated_edit_field1' => array( 'field' => 'is_assigned_to_case',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false,
'label' => array( 'field' => 'is_assigned_to_case',
'table' => 'Manage User Default Notifications',
'type' => 3 ) ),
'integrated_edit_field2' => array( 'field' => 'is_invited_to_case',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false,
'label' => array( 'field' => 'is_invited_to_case',
'table' => 'Manage User Default Notifications',
'type' => 3 ) ),
'integrated_edit_field3' => array( 'field' => 'is_solution_updated',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false,
'label' => array( 'field' => 'is_solution_updated',
'table' => 'Manage User Default Notifications',
'type' => 3 ) ),
'integrated_edit_field4' => array( 'field' => 'is_next_step_updated',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false,
'label' => array( 'field' => 'is_next_step_updated',
'table' => 'Manage User Default Notifications',
'type' => 3 ) ),
'integrated_edit_field5' => array( 'field' => 'is_deadline_updated',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false,
'label' => array( 'field' => 'is_deadline_updated',
'table' => 'Manage User Default Notifications',
'type' => 3 ) ),
'integrated_edit_field12' => array( 'field' => 'is_message_from_occupant',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false,
'label' => array( 'field' => 'is_message_from_occupant',
'table' => 'Manage User Default Notifications',
'type' => 3 ) ),
'integrated_edit_field13' => array( 'field' => 'is_message_from_ll',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false,
'label' => array( 'field' => 'is_message_from_ll',
'table' => 'Manage User Default Notifications',
'type' => 3 ) ),
'integrated_edit_field15' => array( 'field' => 'is_message_from_tenant',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false,
'label' => array( 'field' => 'is_message_from_tenant',
'table' => 'Manage User Default Notifications',
'type' => 3 ) ),
'section' => array( 'type' => 'section',
'title' => array( 'text' => 'Notify the user if a message is from',
'type' => 0 ),
'location' => 'section',
'label' => array( 'text' => 'Notify the user if a message is from',
'type' => 0 ) ),
'section1' => array( 'type' => 'section',
'title' => array( 'text' => 'The Case has changed. Notify the user if',
'type' => 0 ),
'location' => 'section1',
'label' => array( 'text' => 'The Case has changed. Notify the user if',
'type' => 0 ) ),
'section2' => array( 'type' => 'section',
'title' => array( 'text' => 'Notify the user when the user is:',
'type' => 0 ),
'location' => 'section2',
'label' => array( 'text' => 'Notify the user when the user is:',
'type' => 0 ) ),
'section3' => array( 'type' => 'section',
'title' => array( 'text' => 'Overrides - Send everything if',
'type' => 0 ),
'location' => 'section3',
'label' => array( 'text' => 'Overrides - Send everything if',
'type' => 0 ) ) ),
'dbProps' => array(  ),
'version' => 2,
'fixedTopbar' => true );
		?>