<?php
			$optionsArray = array( 'pdf' => array( 'pdfView' => false ),
'fields' => array( 'gridFields' => array( 'order',
'is_obsolete',
'id_unee_t_user_type',
'ut_user_role_type_id',
'description',
'designation',
'syst_created_datetime',
'creation_system_id',
'created_by_id',
'creation_method',
'syst_updated_datetime',
'update_system_id',
'updated_by_id',
'update_method',
'organization_id',
'role_type' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'order' => array( 'integrated_edit_field6' ),
'is_obsolete' => array( 'integrated_edit_field29' ),
'id_unee_t_user_type' => array( 'integrated_edit_field35' ),
'ut_user_role_type_id' => array( 'integrated_edit_field1' ),
'description' => array( 'integrated_edit_field9' ),
'designation' => array( 'integrated_edit_field' ),
'syst_created_datetime' => array( 'integrated_edit_field41' ),
'creation_system_id' => array( 'integrated_edit_field42' ),
'created_by_id' => array( 'integrated_edit_field43' ),
'creation_method' => array( 'integrated_edit_field44' ),
'syst_updated_datetime' => array( 'integrated_edit_field45' ),
'update_system_id' => array( 'integrated_edit_field46' ),
'updated_by_id' => array( 'integrated_edit_field47' ),
'update_method' => array( 'integrated_edit_field48' ),
'organization_id' => array( 'integrated_edit_field49' ),
'role_type' => array( 'integrated_edit_field50' ) ) ),
'pageLinks' => array( 'edit' => true,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array( 'image',
'logo',
'menu' ),
'top' => array( 'view_header' ),
'above-grid' => array( 'breadcrumb' ),
'below-grid' => array( 'view_back_list',
'view_close',
'hamburger' ),
'grid' => array( 'section2',
'section1',
'section',
'section3',
'section4',
'integrated_edit_field41',
'integrated_edit_field42',
'integrated_edit_field43',
'integrated_edit_field44',
'integrated_edit_field45',
'integrated_edit_field46',
'integrated_edit_field47',
'integrated_edit_field48',
'integrated_edit_field49',
'integrated_edit_field50' ),
'section7' => array( 'integrated_edit_field',
'integrated_edit_field9',
'integrated_edit_field1',
'integrated_edit_field35',
'integrated_edit_field6',
'integrated_edit_field29' ),
'section1' => array(  ),
'section' => array( 'tabs' ),
'section2' => array(  ),
'section3' => array(  ),
'section4' => array(  ),
'section5' => array(  ),
'section6' => array(  ),
'section8' => array(  ) ),
'formXtTags' => array( 'above-grid' => array( 'breadcrumb' ) ),
'itemForms' => array( 'image' => 'supertop',
'logo' => 'supertop',
'menu' => 'supertop',
'view_header' => 'top',
'breadcrumb' => 'above-grid',
'view_back_list' => 'below-grid',
'view_close' => 'below-grid',
'hamburger' => 'below-grid',
'section2' => 'grid',
'section1' => 'grid',
'section' => 'grid',
'section3' => 'grid',
'section4' => 'grid',
'integrated_edit_field41' => 'grid',
'integrated_edit_field42' => 'grid',
'integrated_edit_field43' => 'grid',
'integrated_edit_field44' => 'grid',
'integrated_edit_field45' => 'grid',
'integrated_edit_field46' => 'grid',
'integrated_edit_field47' => 'grid',
'integrated_edit_field48' => 'grid',
'integrated_edit_field49' => 'grid',
'integrated_edit_field50' => 'grid',
'integrated_edit_field' => 'section7',
'integrated_edit_field9' => 'section7',
'integrated_edit_field1' => 'section7',
'integrated_edit_field35' => 'section7',
'integrated_edit_field6' => 'section7',
'integrated_edit_field29' => 'section7',
'tabs' => 'section' ),
'itemLocations' => array( 'section2' => array( 'location' => 'grid',
'cellId' => 'c6' ),
'section1' => array( 'location' => 'grid',
'cellId' => 'c7' ),
'section' => array( 'location' => 'grid',
'cellId' => 'c9' ),
'section3' => array( 'location' => 'grid',
'cellId' => 'c' ),
'section4' => array( 'location' => 'grid',
'cellId' => 'c8' ),
'integrated_edit_field41' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field42' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field43' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field44' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field45' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field46' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field47' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field48' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field49' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field50' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field' => array( 'location' => 'section7',
'cellId' => 'c1' ),
'integrated_edit_field9' => array( 'location' => 'section7',
'cellId' => 'c4' ),
'integrated_edit_field1' => array( 'location' => 'section7',
'cellId' => 'c3' ),
'integrated_edit_field35' => array( 'location' => 'section7',
'cellId' => 'c12' ),
'integrated_edit_field6' => array( 'location' => 'section7',
'cellId' => 'c14' ),
'integrated_edit_field29' => array( 'location' => 'section7',
'cellId' => 'c14' ),
'tabs' => array( 'location' => 'section',
'cellId' => 'c1' ) ),
'itemVisiblity' => array( 'menu' => 3 ) ),
'itemsByType' => array( 'view_header' => array( 'view_header' ),
'view_back_list' => array( 'view_back_list' ),
'view_close' => array( 'view_close' ),
'hamburger' => array( 'hamburger' ),
'breadcrumb' => array( 'breadcrumb' ),
'logo' => array( 'logo' ),
'menu' => array( 'menu' ),
'image' => array( 'image' ),
'integrated_edit_field' => array( 'integrated_edit_field6',
'integrated_edit_field29',
'integrated_edit_field35',
'integrated_edit_field1',
'integrated_edit_field9',
'integrated_edit_field',
'integrated_edit_field41',
'integrated_edit_field42',
'integrated_edit_field43',
'integrated_edit_field44',
'integrated_edit_field45',
'integrated_edit_field46',
'integrated_edit_field47',
'integrated_edit_field48',
'integrated_edit_field49',
'integrated_edit_field50' ),
'section' => array( 'section1',
'section4',
'section3',
'section',
'section2' ),
'tabs' => array( 'tabs' ),
'view_edit' => array( 'view_edit' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'c6' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'section2' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c8' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'section4' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c7' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'section1' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c9' => array( 'cols' => array( 0 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'section' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 0 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array( 'section3' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c3' => array( 'cols' => array( 0 ),
'rows' => array( 5 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field41',
'integrated_edit_field42',
'integrated_edit_field43',
'integrated_edit_field44',
'integrated_edit_field45',
'integrated_edit_field46',
'integrated_edit_field47',
'integrated_edit_field48',
'integrated_edit_field49',
'integrated_edit_field50' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 6 ),
'section7' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c3' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field1' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c2' => array( 'cols' => array( 2 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c12' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field35' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c13' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c14' => array( 'cols' => array( 2 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field6',
'integrated_edit_field29' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c4' => array( 'cols' => array( 0,
1,
2 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field9' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 3,
'height' => 3 ),
'section1' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c2' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 2 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ) ),
'width' => 3,
'height' => 1 ),
'section' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'tabs' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ),
'section2' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ) ),
'width' => 2,
'height' => 1 ),
'section3' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c5' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c3' => array( 'cols' => array( 2 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ) ),
'width' => 3,
'height' => 1 ),
'section4' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ),
'section5' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c3' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c2' => array( 'cols' => array( 2 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 3 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ) ),
'width' => 4,
'height' => 1 ),
'section6' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ) ),
'width' => 2,
'height' => 1 ),
'section8' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c4' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c3' => array( 'cols' => array( 2 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c2' => array( 'cols' => array( 3 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 4 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ) ),
'width' => 5,
'height' => 1 ) ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ) ),
'misc' => array( 'type' => 'view',
'breadcrumb' => true,
'nextPrev' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'view',
'type' => 'view',
'layoutId' => 'topbar',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'topbar-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ),
array( 'cell' => 'c3' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'image',
'logo' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'menu' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c3' => array( 'model' => 'c3',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'view-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'view_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'above-grid' => array( 'modelId' => 'view-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1',
'colspan' => 2 ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'breadcrumb' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'view-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'view_back_list',
'view_close' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'hamburger' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c6',
'colspan' => 1 ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c8' ) ) ),
array( 'cells' => array( array( 'cell' => 'c7',
'colspan' => 1 ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c9',
'colspan' => 1 ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c' ) ) ),
array( 'cells' => array( array( 'cell' => 'c3' ) ),
'section' => '' ) ),
'cells' => array( 'c6' => array( 'model' => 'c3',
'items' => array( 'section2' ) ),
'c7' => array( 'model' => 'c3',
'items' => array( 'section1' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c9' => array( 'model' => 'c3',
'items' => array( 'section' ) ),
'c' => array( 'model' => 'c3',
'items' => array( 'section3' ) ),
'c8' => array( 'model' => 'c3',
'items' => array( 'section4' ) ),
'c3' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field41',
'integrated_edit_field42',
'integrated_edit_field43',
'integrated_edit_field44',
'integrated_edit_field45',
'integrated_edit_field46',
'integrated_edit_field47',
'integrated_edit_field48',
'integrated_edit_field49',
'integrated_edit_field50' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section7' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c3' ),
array( 'cell' => 'c2' ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c12' ),
array( 'cell' => 'c13' ),
array( 'cell' => 'c14' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c4',
'colspan' => 3 ) ) ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c1',
'items' => array(  ),
'align' => 'center' ),
'c4' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field9' ) ),
'c3' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field1' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c12' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field35' ),
'align' => 'center' ),
'c13' => array( 'model' => 'c1',
'items' => array(  ),
'align' => 'center' ),
'c14' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field6',
'integrated_edit_field29' ),
'align' => 'center' ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section1' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ),
array( 'cell' => 'c' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0,
'align' => 'center' ),
'c' => array( 'model' => 'c1',
'items' => array(  ),
'align' => 'center' ),
'c2' => array( 'model' => 'c1',
'items' => array(  ),
'align' => 'center' ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'tabs' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section2' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1',
'colspan' => 1 ),
array( 'cell' => 'c',
'colspan' => 1 ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0,
'align' => 'center' ),
'c' => array( 'model' => 'c1',
'items' => array(  ),
'align' => 'center' ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section3' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c5' ),
array( 'cell' => 'c3' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0,
'align' => 'center' ),
'c3' => array( 'model' => 'c1',
'items' => array(  ),
'align' => 'center' ),
'c5' => array( 'model' => 'c1',
'items' => array(  ),
'align' => 'center' ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section4' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0,
'align' => 'center' ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section5' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c3' ),
array( 'cell' => 'c2' ),
array( 'cell' => 'c' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0,
'align' => 'center' ),
'c' => array( 'model' => 'c1',
'items' => array(  ),
'align' => 'center' ),
'c2' => array( 'model' => 'c1',
'items' => array(  ),
'align' => 'center' ),
'c3' => array( 'model' => 'c1',
'items' => array(  ),
'align' => 'center' ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section6' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0,
'align' => 'center' ),
'c' => array( 'model' => 'c1',
'items' => array(  ),
'align' => 'center' ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section8' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c4' ),
array( 'cell' => 'c3' ),
array( 'cell' => 'c2' ),
array( 'cell' => 'c' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c' => array( 'model' => 'c1',
'items' => array(  ) ),
'c2' => array( 'model' => 'c1',
'items' => array(  ) ),
'c3' => array( 'model' => 'c1',
'items' => array(  ) ),
'c4' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ) ),
'items' => array( 'view_header' => array( 'type' => 'view_header' ),
'view_back_list' => array( 'type' => 'view_back_list' ),
'view_close' => array( 'type' => 'view_close' ),
'hamburger' => array( 'type' => 'hamburger',
'items' => array( 'view_edit' ) ),
'breadcrumb' => array( 'type' => 'breadcrumb' ),
'logo' => array( 'type' => 'logo' ),
'menu' => array( 'type' => 'menu' ),
'image' => array( 'type' => 'image',
'imagePath' => 'Unee-T Enterprise160x50.png' ),
'integrated_edit_field6' => array( 'field' => 'order',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field29' => array( 'field' => 'is_obsolete',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'section1' => array( 'type' => 'section',
'title' => array( 'text' => 'Ability to Invite other PUBLIC users',
'type' => 0 ),
'location' => 'section1',
'label' => array( 'text' => 'Ability to Invite other PUBLIC users',
'type' => 0 ) ),
'section4' => array( 'type' => 'section',
'title' => array( 'text' => 'Automatically assign to',
'type' => 0 ),
'location' => 'section8',
'label' => array( 'text' => 'Automatically assign to',
'type' => 0 ) ),
'section3' => array( 'type' => 'section',
'title' => array( 'text' => 'Override - Notify me of everything if the case is',
'type' => 0 ),
'location' => 'section6',
'label' => array( 'text' => 'Override - Notify me of everything if the case is',
'type' => 0 ) ),
'integrated_edit_field35' => array( 'field' => 'id_unee_t_user_type',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'id_unee_t_user_type',
'table' => 'Manage User Types',
'type' => 3 ) ),
'integrated_edit_field1' => array( 'field' => 'ut_user_role_type_id',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'tabs' => array( 'type' => 'tabs',
'titles' => array( array( 'text' => 'The Case has changed',
'type' => 0 ),
array( 'text' => 'New Messages',
'type' => 0 ),
array( 'text' => 'Inspection Reports',
'type' => 0 ),
array( 'text' => 'Inventories and Items',
'type' => 0 ) ),
'locations' => array( 'section2',
'section3',
'section4',
'section5' ) ),
'section' => array( 'type' => 'section',
'title' => array( 'text' => 'Notifications',
'type' => 0 ),
'location' => 'section',
'label' => array( 'text' => 'Notifications',
'type' => 0 ) ),
'integrated_edit_field9' => array( 'field' => 'description',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field' => array( 'field' => 'designation',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'section2' => array( 'type' => 'section',
'title' => array( 'text' => 'About this User Role',
'type' => 0 ),
'location' => 'section7',
'label' => array( 'text' => 'About this User Role',
'type' => 0 ) ),
'view_edit' => array( 'type' => 'view_edit' ),
'integrated_edit_field41' => array( 'field' => 'syst_created_datetime',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field42' => array( 'field' => 'creation_system_id',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field43' => array( 'field' => 'created_by_id',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field44' => array( 'field' => 'creation_method',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field45' => array( 'field' => 'syst_updated_datetime',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field46' => array( 'field' => 'update_system_id',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field47' => array( 'field' => 'updated_by_id',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field48' => array( 'field' => 'update_method',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field49' => array( 'field' => 'organization_id',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field50' => array( 'field' => 'role_type',
'type' => 'integrated_edit_field',
'orientation' => 0 ) ),
'dbProps' => array(  ),
'version' => 4,
'fixedTopbar' => true );
		?>