<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array( 'id_unee_t_user_type',
'syst_created_datetime',
'creation_system_id',
'created_by_id',
'creation_method',
'syst_updated_datetime',
'update_system_id',
'updated_by_id',
'update_method',
'organization_id',
'order',
'is_obsolete',
'description',
'ut_user_role_type_id',
'designation',
'is_assigned_to_case',
'is_invited_to_case',
'is_next_step_updated',
'is_deadline_updated',
'is_dashboard_access',
'is_default_assignee',
'can_see_role_contractor',
'can_see_role_mgt_cny',
'can_see_role_agent',
'can_see_occupant',
'can_see_role_landlord',
'can_see_role_tenant',
'is_public',
'is_item_moved',
'is_item_removed',
'is_new_item',
'is_new_ir',
'is_message_from_contractor',
'is_message_from_mgt_cny',
'is_message_from_agent',
'is_message_from_occupant',
'is_message_from_ll',
'is_message_from_tenant',
'is_any_new_message',
'is_case_critical',
'is_case_blocker',
'is_case_resolved',
'is_solution_updated',
'is_new_inventory',
'is_occupant',
'is_unit_owner',
'is_default_invited',
'is_all_unit',
'is_all_units_in_country',
'is_all_units_in_area',
'is_all_units_in_level_1',
'is_all_units_in_level_2' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'id_unee_t_user_type' => array( 'simple_grid_field',
'simple_grid_field52' ),
'syst_created_datetime' => array( 'simple_grid_field1',
'simple_grid_field53' ),
'creation_system_id' => array( 'simple_grid_field2',
'simple_grid_field54' ),
'created_by_id' => array( 'simple_grid_field3',
'simple_grid_field55' ),
'creation_method' => array( 'simple_grid_field4',
'simple_grid_field56' ),
'syst_updated_datetime' => array( 'simple_grid_field5',
'simple_grid_field57' ),
'update_system_id' => array( 'simple_grid_field6',
'simple_grid_field58' ),
'updated_by_id' => array( 'simple_grid_field7',
'simple_grid_field59' ),
'update_method' => array( 'simple_grid_field8',
'simple_grid_field60' ),
'organization_id' => array( 'simple_grid_field9',
'simple_grid_field61' ),
'order' => array( 'simple_grid_field10',
'simple_grid_field62' ),
'is_obsolete' => array( 'simple_grid_field11',
'simple_grid_field63' ),
'description' => array( 'simple_grid_field13',
'simple_grid_field64' ),
'ut_user_role_type_id' => array( 'simple_grid_field12',
'simple_grid_field65' ),
'designation' => array( 'simple_grid_field14',
'simple_grid_field66' ),
'is_assigned_to_case' => array( 'simple_grid_field15',
'simple_grid_field67' ),
'is_invited_to_case' => array( 'simple_grid_field16',
'simple_grid_field68' ),
'is_next_step_updated' => array( 'simple_grid_field17',
'simple_grid_field69' ),
'is_deadline_updated' => array( 'simple_grid_field18',
'simple_grid_field70' ),
'is_dashboard_access' => array( 'simple_grid_field19',
'simple_grid_field71' ),
'is_default_assignee' => array( 'simple_grid_field21',
'simple_grid_field72' ),
'can_see_role_contractor' => array( 'simple_grid_field22',
'simple_grid_field73' ),
'can_see_role_mgt_cny' => array( 'simple_grid_field23',
'simple_grid_field74' ),
'can_see_role_agent' => array( 'simple_grid_field24',
'simple_grid_field75' ),
'can_see_occupant' => array( 'simple_grid_field25',
'simple_grid_field76' ),
'can_see_role_landlord' => array( 'simple_grid_field26',
'simple_grid_field77' ),
'can_see_role_tenant' => array( 'simple_grid_field27',
'simple_grid_field78' ),
'is_public' => array( 'simple_grid_field28',
'simple_grid_field79' ),
'is_item_moved' => array( 'simple_grid_field29',
'simple_grid_field80' ),
'is_item_removed' => array( 'simple_grid_field30',
'simple_grid_field81' ),
'is_new_item' => array( 'simple_grid_field31',
'simple_grid_field82' ),
'is_new_ir' => array( 'simple_grid_field32',
'simple_grid_field83' ),
'is_message_from_contractor' => array( 'simple_grid_field33',
'simple_grid_field84' ),
'is_message_from_mgt_cny' => array( 'simple_grid_field34',
'simple_grid_field85' ),
'is_message_from_agent' => array( 'simple_grid_field35',
'simple_grid_field86' ),
'is_message_from_occupant' => array( 'simple_grid_field36',
'simple_grid_field87' ),
'is_message_from_ll' => array( 'simple_grid_field37',
'simple_grid_field88' ),
'is_message_from_tenant' => array( 'simple_grid_field38',
'simple_grid_field89' ),
'is_any_new_message' => array( 'simple_grid_field39',
'simple_grid_field90' ),
'is_case_critical' => array( 'simple_grid_field40',
'simple_grid_field91' ),
'is_case_blocker' => array( 'simple_grid_field41',
'simple_grid_field92' ),
'is_case_resolved' => array( 'simple_grid_field42',
'simple_grid_field93' ),
'is_solution_updated' => array( 'simple_grid_field43',
'simple_grid_field94' ),
'is_new_inventory' => array( 'simple_grid_field44',
'simple_grid_field95' ),
'is_occupant' => array( 'simple_grid_field45',
'simple_grid_field96' ),
'is_unit_owner' => array( 'simple_grid_field46',
'simple_grid_field97' ),
'is_default_invited' => array( 'simple_grid_field20',
'simple_grid_field98' ),
'is_all_unit' => array( 'simple_grid_field47',
'simple_grid_field99' ),
'is_all_units_in_country' => array( 'simple_grid_field48',
'simple_grid_field100' ),
'is_all_units_in_area' => array( 'simple_grid_field49',
'simple_grid_field101' ),
'is_all_units_in_level_1' => array( 'simple_grid_field50',
'simple_grid_field102' ),
'is_all_units_in_level_2' => array( 'simple_grid_field51',
'simple_grid_field103' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'top' => array( 'masterprint_header' ),
'above-grid' => array(  ),
'below-grid' => array(  ),
'grid' => array( 'simple_grid_field52',
'simple_grid_field',
'simple_grid_field53',
'simple_grid_field1',
'simple_grid_field54',
'simple_grid_field2',
'simple_grid_field55',
'simple_grid_field3',
'simple_grid_field56',
'simple_grid_field4',
'simple_grid_field57',
'simple_grid_field5',
'simple_grid_field58',
'simple_grid_field6',
'simple_grid_field59',
'simple_grid_field7',
'simple_grid_field60',
'simple_grid_field8',
'simple_grid_field61',
'simple_grid_field9',
'simple_grid_field62',
'simple_grid_field10',
'simple_grid_field63',
'simple_grid_field11',
'simple_grid_field64',
'simple_grid_field13',
'simple_grid_field65',
'simple_grid_field12',
'simple_grid_field66',
'simple_grid_field14',
'simple_grid_field67',
'simple_grid_field15',
'simple_grid_field68',
'simple_grid_field16',
'simple_grid_field69',
'simple_grid_field17',
'simple_grid_field70',
'simple_grid_field18',
'simple_grid_field71',
'simple_grid_field19',
'simple_grid_field72',
'simple_grid_field21',
'simple_grid_field73',
'simple_grid_field22',
'simple_grid_field74',
'simple_grid_field23',
'simple_grid_field75',
'simple_grid_field24',
'simple_grid_field76',
'simple_grid_field25',
'simple_grid_field77',
'simple_grid_field26',
'simple_grid_field78',
'simple_grid_field27',
'simple_grid_field79',
'simple_grid_field28',
'simple_grid_field80',
'simple_grid_field29',
'simple_grid_field81',
'simple_grid_field30',
'simple_grid_field82',
'simple_grid_field31',
'simple_grid_field83',
'simple_grid_field32',
'simple_grid_field84',
'simple_grid_field33',
'simple_grid_field85',
'simple_grid_field34',
'simple_grid_field86',
'simple_grid_field35',
'simple_grid_field87',
'simple_grid_field36',
'simple_grid_field88',
'simple_grid_field37',
'simple_grid_field89',
'simple_grid_field38',
'simple_grid_field90',
'simple_grid_field39',
'simple_grid_field91',
'simple_grid_field40',
'simple_grid_field92',
'simple_grid_field41',
'simple_grid_field93',
'simple_grid_field42',
'simple_grid_field94',
'simple_grid_field43',
'simple_grid_field95',
'simple_grid_field44',
'simple_grid_field96',
'simple_grid_field45',
'simple_grid_field97',
'simple_grid_field46',
'simple_grid_field98',
'simple_grid_field20',
'simple_grid_field99',
'simple_grid_field47',
'simple_grid_field100',
'simple_grid_field48',
'simple_grid_field101',
'simple_grid_field49',
'simple_grid_field102',
'simple_grid_field50',
'simple_grid_field103',
'simple_grid_field51' ) ),
'formXtTags' => array( 'above-grid' => array(  ),
'below-grid' => array(  ) ),
'itemForms' => array( 'masterprint_header' => 'top',
'simple_grid_field52' => 'grid',
'simple_grid_field' => 'grid',
'simple_grid_field53' => 'grid',
'simple_grid_field1' => 'grid',
'simple_grid_field54' => 'grid',
'simple_grid_field2' => 'grid',
'simple_grid_field55' => 'grid',
'simple_grid_field3' => 'grid',
'simple_grid_field56' => 'grid',
'simple_grid_field4' => 'grid',
'simple_grid_field57' => 'grid',
'simple_grid_field5' => 'grid',
'simple_grid_field58' => 'grid',
'simple_grid_field6' => 'grid',
'simple_grid_field59' => 'grid',
'simple_grid_field7' => 'grid',
'simple_grid_field60' => 'grid',
'simple_grid_field8' => 'grid',
'simple_grid_field61' => 'grid',
'simple_grid_field9' => 'grid',
'simple_grid_field62' => 'grid',
'simple_grid_field10' => 'grid',
'simple_grid_field63' => 'grid',
'simple_grid_field11' => 'grid',
'simple_grid_field64' => 'grid',
'simple_grid_field13' => 'grid',
'simple_grid_field65' => 'grid',
'simple_grid_field12' => 'grid',
'simple_grid_field66' => 'grid',
'simple_grid_field14' => 'grid',
'simple_grid_field67' => 'grid',
'simple_grid_field15' => 'grid',
'simple_grid_field68' => 'grid',
'simple_grid_field16' => 'grid',
'simple_grid_field69' => 'grid',
'simple_grid_field17' => 'grid',
'simple_grid_field70' => 'grid',
'simple_grid_field18' => 'grid',
'simple_grid_field71' => 'grid',
'simple_grid_field19' => 'grid',
'simple_grid_field72' => 'grid',
'simple_grid_field21' => 'grid',
'simple_grid_field73' => 'grid',
'simple_grid_field22' => 'grid',
'simple_grid_field74' => 'grid',
'simple_grid_field23' => 'grid',
'simple_grid_field75' => 'grid',
'simple_grid_field24' => 'grid',
'simple_grid_field76' => 'grid',
'simple_grid_field25' => 'grid',
'simple_grid_field77' => 'grid',
'simple_grid_field26' => 'grid',
'simple_grid_field78' => 'grid',
'simple_grid_field27' => 'grid',
'simple_grid_field79' => 'grid',
'simple_grid_field28' => 'grid',
'simple_grid_field80' => 'grid',
'simple_grid_field29' => 'grid',
'simple_grid_field81' => 'grid',
'simple_grid_field30' => 'grid',
'simple_grid_field82' => 'grid',
'simple_grid_field31' => 'grid',
'simple_grid_field83' => 'grid',
'simple_grid_field32' => 'grid',
'simple_grid_field84' => 'grid',
'simple_grid_field33' => 'grid',
'simple_grid_field85' => 'grid',
'simple_grid_field34' => 'grid',
'simple_grid_field86' => 'grid',
'simple_grid_field35' => 'grid',
'simple_grid_field87' => 'grid',
'simple_grid_field36' => 'grid',
'simple_grid_field88' => 'grid',
'simple_grid_field37' => 'grid',
'simple_grid_field89' => 'grid',
'simple_grid_field38' => 'grid',
'simple_grid_field90' => 'grid',
'simple_grid_field39' => 'grid',
'simple_grid_field91' => 'grid',
'simple_grid_field40' => 'grid',
'simple_grid_field92' => 'grid',
'simple_grid_field41' => 'grid',
'simple_grid_field93' => 'grid',
'simple_grid_field42' => 'grid',
'simple_grid_field94' => 'grid',
'simple_grid_field43' => 'grid',
'simple_grid_field95' => 'grid',
'simple_grid_field44' => 'grid',
'simple_grid_field96' => 'grid',
'simple_grid_field45' => 'grid',
'simple_grid_field97' => 'grid',
'simple_grid_field46' => 'grid',
'simple_grid_field98' => 'grid',
'simple_grid_field20' => 'grid',
'simple_grid_field99' => 'grid',
'simple_grid_field47' => 'grid',
'simple_grid_field100' => 'grid',
'simple_grid_field48' => 'grid',
'simple_grid_field101' => 'grid',
'simple_grid_field49' => 'grid',
'simple_grid_field102' => 'grid',
'simple_grid_field50' => 'grid',
'simple_grid_field103' => 'grid',
'simple_grid_field51' => 'grid' ),
'itemLocations' => array( 'simple_grid_field52' => array( 'location' => 'grid',
'cellId' => 'headcell_field' ),
'simple_grid_field' => array( 'location' => 'grid',
'cellId' => 'cell_field' ),
'simple_grid_field53' => array( 'location' => 'grid',
'cellId' => 'headcell_field1' ),
'simple_grid_field1' => array( 'location' => 'grid',
'cellId' => 'cell_field1' ),
'simple_grid_field54' => array( 'location' => 'grid',
'cellId' => 'headcell_field2' ),
'simple_grid_field2' => array( 'location' => 'grid',
'cellId' => 'cell_field2' ),
'simple_grid_field55' => array( 'location' => 'grid',
'cellId' => 'headcell_field3' ),
'simple_grid_field3' => array( 'location' => 'grid',
'cellId' => 'cell_field3' ),
'simple_grid_field56' => array( 'location' => 'grid',
'cellId' => 'headcell_field4' ),
'simple_grid_field4' => array( 'location' => 'grid',
'cellId' => 'cell_field4' ),
'simple_grid_field57' => array( 'location' => 'grid',
'cellId' => 'headcell_field5' ),
'simple_grid_field5' => array( 'location' => 'grid',
'cellId' => 'cell_field5' ),
'simple_grid_field58' => array( 'location' => 'grid',
'cellId' => 'headcell_field6' ),
'simple_grid_field6' => array( 'location' => 'grid',
'cellId' => 'cell_field6' ),
'simple_grid_field59' => array( 'location' => 'grid',
'cellId' => 'headcell_field7' ),
'simple_grid_field7' => array( 'location' => 'grid',
'cellId' => 'cell_field7' ),
'simple_grid_field60' => array( 'location' => 'grid',
'cellId' => 'headcell_field8' ),
'simple_grid_field8' => array( 'location' => 'grid',
'cellId' => 'cell_field8' ),
'simple_grid_field61' => array( 'location' => 'grid',
'cellId' => 'headcell_field9' ),
'simple_grid_field9' => array( 'location' => 'grid',
'cellId' => 'cell_field9' ),
'simple_grid_field62' => array( 'location' => 'grid',
'cellId' => 'headcell_field10' ),
'simple_grid_field10' => array( 'location' => 'grid',
'cellId' => 'cell_field10' ),
'simple_grid_field63' => array( 'location' => 'grid',
'cellId' => 'headcell_field11' ),
'simple_grid_field11' => array( 'location' => 'grid',
'cellId' => 'cell_field11' ),
'simple_grid_field64' => array( 'location' => 'grid',
'cellId' => 'headcell_field12' ),
'simple_grid_field13' => array( 'location' => 'grid',
'cellId' => 'cell_field12' ),
'simple_grid_field65' => array( 'location' => 'grid',
'cellId' => 'headcell_field13' ),
'simple_grid_field12' => array( 'location' => 'grid',
'cellId' => 'cell_field13' ),
'simple_grid_field66' => array( 'location' => 'grid',
'cellId' => 'headcell_field14' ),
'simple_grid_field14' => array( 'location' => 'grid',
'cellId' => 'cell_field14' ),
'simple_grid_field67' => array( 'location' => 'grid',
'cellId' => 'headcell_field15' ),
'simple_grid_field15' => array( 'location' => 'grid',
'cellId' => 'cell_field15' ),
'simple_grid_field68' => array( 'location' => 'grid',
'cellId' => 'headcell_field16' ),
'simple_grid_field16' => array( 'location' => 'grid',
'cellId' => 'cell_field16' ),
'simple_grid_field69' => array( 'location' => 'grid',
'cellId' => 'headcell_field17' ),
'simple_grid_field17' => array( 'location' => 'grid',
'cellId' => 'cell_field17' ),
'simple_grid_field70' => array( 'location' => 'grid',
'cellId' => 'headcell_field18' ),
'simple_grid_field18' => array( 'location' => 'grid',
'cellId' => 'cell_field18' ),
'simple_grid_field71' => array( 'location' => 'grid',
'cellId' => 'headcell_field19' ),
'simple_grid_field19' => array( 'location' => 'grid',
'cellId' => 'cell_field19' ),
'simple_grid_field72' => array( 'location' => 'grid',
'cellId' => 'headcell_field20' ),
'simple_grid_field21' => array( 'location' => 'grid',
'cellId' => 'cell_field20' ),
'simple_grid_field73' => array( 'location' => 'grid',
'cellId' => 'headcell_field21' ),
'simple_grid_field22' => array( 'location' => 'grid',
'cellId' => 'cell_field21' ),
'simple_grid_field74' => array( 'location' => 'grid',
'cellId' => 'headcell_field22' ),
'simple_grid_field23' => array( 'location' => 'grid',
'cellId' => 'cell_field22' ),
'simple_grid_field75' => array( 'location' => 'grid',
'cellId' => 'headcell_field23' ),
'simple_grid_field24' => array( 'location' => 'grid',
'cellId' => 'cell_field23' ),
'simple_grid_field76' => array( 'location' => 'grid',
'cellId' => 'headcell_field24' ),
'simple_grid_field25' => array( 'location' => 'grid',
'cellId' => 'cell_field24' ),
'simple_grid_field77' => array( 'location' => 'grid',
'cellId' => 'headcell_field25' ),
'simple_grid_field26' => array( 'location' => 'grid',
'cellId' => 'cell_field25' ),
'simple_grid_field78' => array( 'location' => 'grid',
'cellId' => 'headcell_field26' ),
'simple_grid_field27' => array( 'location' => 'grid',
'cellId' => 'cell_field26' ),
'simple_grid_field79' => array( 'location' => 'grid',
'cellId' => 'headcell_field27' ),
'simple_grid_field28' => array( 'location' => 'grid',
'cellId' => 'cell_field27' ),
'simple_grid_field80' => array( 'location' => 'grid',
'cellId' => 'headcell_field28' ),
'simple_grid_field29' => array( 'location' => 'grid',
'cellId' => 'cell_field28' ),
'simple_grid_field81' => array( 'location' => 'grid',
'cellId' => 'headcell_field29' ),
'simple_grid_field30' => array( 'location' => 'grid',
'cellId' => 'cell_field29' ),
'simple_grid_field82' => array( 'location' => 'grid',
'cellId' => 'headcell_field30' ),
'simple_grid_field31' => array( 'location' => 'grid',
'cellId' => 'cell_field30' ),
'simple_grid_field83' => array( 'location' => 'grid',
'cellId' => 'headcell_field31' ),
'simple_grid_field32' => array( 'location' => 'grid',
'cellId' => 'cell_field31' ),
'simple_grid_field84' => array( 'location' => 'grid',
'cellId' => 'headcell_field32' ),
'simple_grid_field33' => array( 'location' => 'grid',
'cellId' => 'cell_field32' ),
'simple_grid_field85' => array( 'location' => 'grid',
'cellId' => 'headcell_field33' ),
'simple_grid_field34' => array( 'location' => 'grid',
'cellId' => 'cell_field33' ),
'simple_grid_field86' => array( 'location' => 'grid',
'cellId' => 'headcell_field34' ),
'simple_grid_field35' => array( 'location' => 'grid',
'cellId' => 'cell_field34' ),
'simple_grid_field87' => array( 'location' => 'grid',
'cellId' => 'headcell_field35' ),
'simple_grid_field36' => array( 'location' => 'grid',
'cellId' => 'cell_field35' ),
'simple_grid_field88' => array( 'location' => 'grid',
'cellId' => 'headcell_field36' ),
'simple_grid_field37' => array( 'location' => 'grid',
'cellId' => 'cell_field36' ),
'simple_grid_field89' => array( 'location' => 'grid',
'cellId' => 'headcell_field37' ),
'simple_grid_field38' => array( 'location' => 'grid',
'cellId' => 'cell_field37' ),
'simple_grid_field90' => array( 'location' => 'grid',
'cellId' => 'headcell_field38' ),
'simple_grid_field39' => array( 'location' => 'grid',
'cellId' => 'cell_field38' ),
'simple_grid_field91' => array( 'location' => 'grid',
'cellId' => 'headcell_field39' ),
'simple_grid_field40' => array( 'location' => 'grid',
'cellId' => 'cell_field39' ),
'simple_grid_field92' => array( 'location' => 'grid',
'cellId' => 'headcell_field40' ),
'simple_grid_field41' => array( 'location' => 'grid',
'cellId' => 'cell_field40' ),
'simple_grid_field93' => array( 'location' => 'grid',
'cellId' => 'headcell_field41' ),
'simple_grid_field42' => array( 'location' => 'grid',
'cellId' => 'cell_field41' ),
'simple_grid_field94' => array( 'location' => 'grid',
'cellId' => 'headcell_field42' ),
'simple_grid_field43' => array( 'location' => 'grid',
'cellId' => 'cell_field42' ),
'simple_grid_field95' => array( 'location' => 'grid',
'cellId' => 'headcell_field43' ),
'simple_grid_field44' => array( 'location' => 'grid',
'cellId' => 'cell_field43' ),
'simple_grid_field96' => array( 'location' => 'grid',
'cellId' => 'headcell_field44' ),
'simple_grid_field45' => array( 'location' => 'grid',
'cellId' => 'cell_field44' ),
'simple_grid_field97' => array( 'location' => 'grid',
'cellId' => 'headcell_field45' ),
'simple_grid_field46' => array( 'location' => 'grid',
'cellId' => 'cell_field45' ),
'simple_grid_field98' => array( 'location' => 'grid',
'cellId' => 'headcell_field46' ),
'simple_grid_field20' => array( 'location' => 'grid',
'cellId' => 'cell_field46' ),
'simple_grid_field99' => array( 'location' => 'grid',
'cellId' => 'headcell_field47' ),
'simple_grid_field47' => array( 'location' => 'grid',
'cellId' => 'cell_field47' ),
'simple_grid_field100' => array( 'location' => 'grid',
'cellId' => 'headcell_field48' ),
'simple_grid_field48' => array( 'location' => 'grid',
'cellId' => 'cell_field48' ),
'simple_grid_field101' => array( 'location' => 'grid',
'cellId' => 'headcell_field49' ),
'simple_grid_field49' => array( 'location' => 'grid',
'cellId' => 'cell_field49' ),
'simple_grid_field102' => array( 'location' => 'grid',
'cellId' => 'headcell_field50' ),
'simple_grid_field50' => array( 'location' => 'grid',
'cellId' => 'cell_field50' ),
'simple_grid_field103' => array( 'location' => 'grid',
'cellId' => 'headcell_field51' ),
'simple_grid_field51' => array( 'location' => 'grid',
'cellId' => 'cell_field51' ) ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'masterprint_header' => array( 'masterprint_header' ),
'grid_field' => array( 'simple_grid_field',
'simple_grid_field1',
'simple_grid_field2',
'simple_grid_field3',
'simple_grid_field4',
'simple_grid_field5',
'simple_grid_field6',
'simple_grid_field7',
'simple_grid_field8',
'simple_grid_field9',
'simple_grid_field10',
'simple_grid_field11',
'simple_grid_field13',
'simple_grid_field12',
'simple_grid_field14',
'simple_grid_field15',
'simple_grid_field16',
'simple_grid_field17',
'simple_grid_field18',
'simple_grid_field19',
'simple_grid_field21',
'simple_grid_field22',
'simple_grid_field23',
'simple_grid_field24',
'simple_grid_field25',
'simple_grid_field26',
'simple_grid_field27',
'simple_grid_field28',
'simple_grid_field29',
'simple_grid_field30',
'simple_grid_field31',
'simple_grid_field32',
'simple_grid_field33',
'simple_grid_field34',
'simple_grid_field35',
'simple_grid_field36',
'simple_grid_field37',
'simple_grid_field38',
'simple_grid_field39',
'simple_grid_field40',
'simple_grid_field41',
'simple_grid_field42',
'simple_grid_field43',
'simple_grid_field44',
'simple_grid_field45',
'simple_grid_field46',
'simple_grid_field20',
'simple_grid_field47',
'simple_grid_field48',
'simple_grid_field49',
'simple_grid_field50',
'simple_grid_field51' ),
'grid_field_label' => array( 'simple_grid_field52',
'simple_grid_field53',
'simple_grid_field54',
'simple_grid_field55',
'simple_grid_field56',
'simple_grid_field57',
'simple_grid_field58',
'simple_grid_field59',
'simple_grid_field60',
'simple_grid_field61',
'simple_grid_field62',
'simple_grid_field63',
'simple_grid_field64',
'simple_grid_field65',
'simple_grid_field66',
'simple_grid_field67',
'simple_grid_field68',
'simple_grid_field69',
'simple_grid_field70',
'simple_grid_field71',
'simple_grid_field72',
'simple_grid_field73',
'simple_grid_field74',
'simple_grid_field75',
'simple_grid_field76',
'simple_grid_field77',
'simple_grid_field78',
'simple_grid_field79',
'simple_grid_field80',
'simple_grid_field81',
'simple_grid_field82',
'simple_grid_field83',
'simple_grid_field84',
'simple_grid_field85',
'simple_grid_field86',
'simple_grid_field87',
'simple_grid_field88',
'simple_grid_field89',
'simple_grid_field90',
'simple_grid_field91',
'simple_grid_field92',
'simple_grid_field93',
'simple_grid_field94',
'simple_grid_field95',
'simple_grid_field96',
'simple_grid_field97',
'simple_grid_field98',
'simple_grid_field99',
'simple_grid_field100',
'simple_grid_field101',
'simple_grid_field102',
'simple_grid_field103' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'headcell_field' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array( 'id_unee_t_user_type_fieldheadercolumn' ),
'items' => array( 'simple_grid_field52' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field1' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array( 'syst_created_datetime_fieldheadercolumn' ),
'items' => array( 'simple_grid_field53' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field2' => array( 'cols' => array( 2 ),
'rows' => array( 0 ),
'tags' => array( 'creation_system_id_fieldheadercolumn' ),
'items' => array( 'simple_grid_field54' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field3' => array( 'cols' => array( 3 ),
'rows' => array( 0 ),
'tags' => array( 'created_by_id_fieldheadercolumn' ),
'items' => array( 'simple_grid_field55' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field4' => array( 'cols' => array( 4 ),
'rows' => array( 0 ),
'tags' => array( 'creation_method_fieldheadercolumn' ),
'items' => array( 'simple_grid_field56' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field5' => array( 'cols' => array( 5 ),
'rows' => array( 0 ),
'tags' => array( 'syst_updated_datetime_fieldheadercolumn' ),
'items' => array( 'simple_grid_field57' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field6' => array( 'cols' => array( 6 ),
'rows' => array( 0 ),
'tags' => array( 'update_system_id_fieldheadercolumn' ),
'items' => array( 'simple_grid_field58' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field7' => array( 'cols' => array( 7 ),
'rows' => array( 0 ),
'tags' => array( 'updated_by_id_fieldheadercolumn' ),
'items' => array( 'simple_grid_field59' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field8' => array( 'cols' => array( 8 ),
'rows' => array( 0 ),
'tags' => array( 'update_method_fieldheadercolumn' ),
'items' => array( 'simple_grid_field60' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field9' => array( 'cols' => array( 9 ),
'rows' => array( 0 ),
'tags' => array( 'organization_id_fieldheadercolumn' ),
'items' => array( 'simple_grid_field61' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field10' => array( 'cols' => array( 10 ),
'rows' => array( 0 ),
'tags' => array( 'order_fieldheadercolumn' ),
'items' => array( 'simple_grid_field62' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field11' => array( 'cols' => array( 11 ),
'rows' => array( 0 ),
'tags' => array( 'is_obsolete_fieldheadercolumn' ),
'items' => array( 'simple_grid_field63' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field12' => array( 'cols' => array( 12 ),
'rows' => array( 0 ),
'tags' => array( 'description_fieldheadercolumn' ),
'items' => array( 'simple_grid_field64' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field13' => array( 'cols' => array( 13 ),
'rows' => array( 0 ),
'tags' => array( 'ut_user_role_type_id_fieldheadercolumn' ),
'items' => array( 'simple_grid_field65' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field14' => array( 'cols' => array( 14 ),
'rows' => array( 0 ),
'tags' => array( 'designation_fieldheadercolumn' ),
'items' => array( 'simple_grid_field66' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field15' => array( 'cols' => array( 15 ),
'rows' => array( 0 ),
'tags' => array( 'is_assigned_to_case_fieldheadercolumn' ),
'items' => array( 'simple_grid_field67' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field16' => array( 'cols' => array( 16 ),
'rows' => array( 0 ),
'tags' => array( 'is_invited_to_case_fieldheadercolumn' ),
'items' => array( 'simple_grid_field68' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field17' => array( 'cols' => array( 17 ),
'rows' => array( 0 ),
'tags' => array( 'is_next_step_updated_fieldheadercolumn' ),
'items' => array( 'simple_grid_field69' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field18' => array( 'cols' => array( 18 ),
'rows' => array( 0 ),
'tags' => array( 'is_deadline_updated_fieldheadercolumn' ),
'items' => array( 'simple_grid_field70' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field19' => array( 'cols' => array( 19 ),
'rows' => array( 0 ),
'tags' => array( 'is_dashboard_access_fieldheadercolumn' ),
'items' => array( 'simple_grid_field71' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field20' => array( 'cols' => array( 20 ),
'rows' => array( 0 ),
'tags' => array( 'is_default_assignee_fieldheadercolumn' ),
'items' => array( 'simple_grid_field72' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field21' => array( 'cols' => array( 21 ),
'rows' => array( 0 ),
'tags' => array( 'can_see_role_contractor_fieldheadercolumn' ),
'items' => array( 'simple_grid_field73' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field22' => array( 'cols' => array( 22 ),
'rows' => array( 0 ),
'tags' => array( 'can_see_role_mgt_cny_fieldheadercolumn' ),
'items' => array( 'simple_grid_field74' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field23' => array( 'cols' => array( 23 ),
'rows' => array( 0 ),
'tags' => array( 'can_see_role_agent_fieldheadercolumn' ),
'items' => array( 'simple_grid_field75' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field24' => array( 'cols' => array( 24 ),
'rows' => array( 0 ),
'tags' => array( 'can_see_occupant_fieldheadercolumn' ),
'items' => array( 'simple_grid_field76' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field25' => array( 'cols' => array( 25 ),
'rows' => array( 0 ),
'tags' => array( 'can_see_role_landlord_fieldheadercolumn' ),
'items' => array( 'simple_grid_field77' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field26' => array( 'cols' => array( 26 ),
'rows' => array( 0 ),
'tags' => array( 'can_see_role_tenant_fieldheadercolumn' ),
'items' => array( 'simple_grid_field78' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field27' => array( 'cols' => array( 27 ),
'rows' => array( 0 ),
'tags' => array( 'is_public_fieldheadercolumn' ),
'items' => array( 'simple_grid_field79' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field28' => array( 'cols' => array( 28 ),
'rows' => array( 0 ),
'tags' => array( 'is_item_moved_fieldheadercolumn' ),
'items' => array( 'simple_grid_field80' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field29' => array( 'cols' => array( 29 ),
'rows' => array( 0 ),
'tags' => array( 'is_item_removed_fieldheadercolumn' ),
'items' => array( 'simple_grid_field81' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field30' => array( 'cols' => array( 30 ),
'rows' => array( 0 ),
'tags' => array( 'is_new_item_fieldheadercolumn' ),
'items' => array( 'simple_grid_field82' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field31' => array( 'cols' => array( 31 ),
'rows' => array( 0 ),
'tags' => array( 'is_new_ir_fieldheadercolumn' ),
'items' => array( 'simple_grid_field83' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field32' => array( 'cols' => array( 32 ),
'rows' => array( 0 ),
'tags' => array( 'is_message_from_contractor_fieldheadercolumn' ),
'items' => array( 'simple_grid_field84' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field33' => array( 'cols' => array( 33 ),
'rows' => array( 0 ),
'tags' => array( 'is_message_from_mgt_cny_fieldheadercolumn' ),
'items' => array( 'simple_grid_field85' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field34' => array( 'cols' => array( 34 ),
'rows' => array( 0 ),
'tags' => array( 'is_message_from_agent_fieldheadercolumn' ),
'items' => array( 'simple_grid_field86' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field35' => array( 'cols' => array( 35 ),
'rows' => array( 0 ),
'tags' => array( 'is_message_from_occupant_fieldheadercolumn' ),
'items' => array( 'simple_grid_field87' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field36' => array( 'cols' => array( 36 ),
'rows' => array( 0 ),
'tags' => array( 'is_message_from_ll_fieldheadercolumn' ),
'items' => array( 'simple_grid_field88' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field37' => array( 'cols' => array( 37 ),
'rows' => array( 0 ),
'tags' => array( 'is_message_from_tenant_fieldheadercolumn' ),
'items' => array( 'simple_grid_field89' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field38' => array( 'cols' => array( 38 ),
'rows' => array( 0 ),
'tags' => array( 'is_any_new_message_fieldheadercolumn' ),
'items' => array( 'simple_grid_field90' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field39' => array( 'cols' => array( 39 ),
'rows' => array( 0 ),
'tags' => array( 'is_case_critical_fieldheadercolumn' ),
'items' => array( 'simple_grid_field91' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field40' => array( 'cols' => array( 40 ),
'rows' => array( 0 ),
'tags' => array( 'is_case_blocker_fieldheadercolumn' ),
'items' => array( 'simple_grid_field92' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field41' => array( 'cols' => array( 41 ),
'rows' => array( 0 ),
'tags' => array( 'is_case_resolved_fieldheadercolumn' ),
'items' => array( 'simple_grid_field93' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field42' => array( 'cols' => array( 42 ),
'rows' => array( 0 ),
'tags' => array( 'is_solution_updated_fieldheadercolumn' ),
'items' => array( 'simple_grid_field94' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field43' => array( 'cols' => array( 43 ),
'rows' => array( 0 ),
'tags' => array( 'is_new_inventory_fieldheadercolumn' ),
'items' => array( 'simple_grid_field95' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field44' => array( 'cols' => array( 44 ),
'rows' => array( 0 ),
'tags' => array( 'is_occupant_fieldheadercolumn' ),
'items' => array( 'simple_grid_field96' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field45' => array( 'cols' => array( 45 ),
'rows' => array( 0 ),
'tags' => array( 'is_unit_owner_fieldheadercolumn' ),
'items' => array( 'simple_grid_field97' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field46' => array( 'cols' => array( 46 ),
'rows' => array( 0 ),
'tags' => array( 'is_default_invited_fieldheadercolumn' ),
'items' => array( 'simple_grid_field98' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field47' => array( 'cols' => array( 47 ),
'rows' => array( 0 ),
'tags' => array( 'is_all_unit_fieldheadercolumn' ),
'items' => array( 'simple_grid_field99' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field48' => array( 'cols' => array( 48 ),
'rows' => array( 0 ),
'tags' => array( 'is_all_units_in_country_fieldheadercolumn' ),
'items' => array( 'simple_grid_field100' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field49' => array( 'cols' => array( 49 ),
'rows' => array( 0 ),
'tags' => array( 'is_all_units_in_area_fieldheadercolumn' ),
'items' => array( 'simple_grid_field101' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field50' => array( 'cols' => array( 50 ),
'rows' => array( 0 ),
'tags' => array( 'is_all_units_in_level_1_fieldheadercolumn' ),
'items' => array( 'simple_grid_field102' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field51' => array( 'cols' => array( 51 ),
'rows' => array( 0 ),
'tags' => array( 'is_all_units_in_level_2_fieldheadercolumn' ),
'items' => array( 'simple_grid_field103' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array( 'id_unee_t_user_type_fieldcolumn' ),
'items' => array( 'simple_grid_field' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field1' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array( 'syst_created_datetime_fieldcolumn' ),
'items' => array( 'simple_grid_field1' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field2' => array( 'cols' => array( 2 ),
'rows' => array( 1 ),
'tags' => array( 'creation_system_id_fieldcolumn' ),
'items' => array( 'simple_grid_field2' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field3' => array( 'cols' => array( 3 ),
'rows' => array( 1 ),
'tags' => array( 'created_by_id_fieldcolumn' ),
'items' => array( 'simple_grid_field3' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field4' => array( 'cols' => array( 4 ),
'rows' => array( 1 ),
'tags' => array( 'creation_method_fieldcolumn' ),
'items' => array( 'simple_grid_field4' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field5' => array( 'cols' => array( 5 ),
'rows' => array( 1 ),
'tags' => array( 'syst_updated_datetime_fieldcolumn' ),
'items' => array( 'simple_grid_field5' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field6' => array( 'cols' => array( 6 ),
'rows' => array( 1 ),
'tags' => array( 'update_system_id_fieldcolumn' ),
'items' => array( 'simple_grid_field6' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field7' => array( 'cols' => array( 7 ),
'rows' => array( 1 ),
'tags' => array( 'updated_by_id_fieldcolumn' ),
'items' => array( 'simple_grid_field7' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field8' => array( 'cols' => array( 8 ),
'rows' => array( 1 ),
'tags' => array( 'update_method_fieldcolumn' ),
'items' => array( 'simple_grid_field8' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field9' => array( 'cols' => array( 9 ),
'rows' => array( 1 ),
'tags' => array( 'organization_id_fieldcolumn' ),
'items' => array( 'simple_grid_field9' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field10' => array( 'cols' => array( 10 ),
'rows' => array( 1 ),
'tags' => array( 'order_fieldcolumn' ),
'items' => array( 'simple_grid_field10' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field11' => array( 'cols' => array( 11 ),
'rows' => array( 1 ),
'tags' => array( 'is_obsolete_fieldcolumn' ),
'items' => array( 'simple_grid_field11' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field12' => array( 'cols' => array( 12 ),
'rows' => array( 1 ),
'tags' => array( 'description_fieldcolumn' ),
'items' => array( 'simple_grid_field13' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field13' => array( 'cols' => array( 13 ),
'rows' => array( 1 ),
'tags' => array( 'ut_user_role_type_id_fieldcolumn' ),
'items' => array( 'simple_grid_field12' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field14' => array( 'cols' => array( 14 ),
'rows' => array( 1 ),
'tags' => array( 'designation_fieldcolumn' ),
'items' => array( 'simple_grid_field14' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field15' => array( 'cols' => array( 15 ),
'rows' => array( 1 ),
'tags' => array( 'is_assigned_to_case_fieldcolumn' ),
'items' => array( 'simple_grid_field15' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field16' => array( 'cols' => array( 16 ),
'rows' => array( 1 ),
'tags' => array( 'is_invited_to_case_fieldcolumn' ),
'items' => array( 'simple_grid_field16' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field17' => array( 'cols' => array( 17 ),
'rows' => array( 1 ),
'tags' => array( 'is_next_step_updated_fieldcolumn' ),
'items' => array( 'simple_grid_field17' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field18' => array( 'cols' => array( 18 ),
'rows' => array( 1 ),
'tags' => array( 'is_deadline_updated_fieldcolumn' ),
'items' => array( 'simple_grid_field18' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field19' => array( 'cols' => array( 19 ),
'rows' => array( 1 ),
'tags' => array( 'is_dashboard_access_fieldcolumn' ),
'items' => array( 'simple_grid_field19' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field20' => array( 'cols' => array( 20 ),
'rows' => array( 1 ),
'tags' => array( 'is_default_assignee_fieldcolumn' ),
'items' => array( 'simple_grid_field21' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field21' => array( 'cols' => array( 21 ),
'rows' => array( 1 ),
'tags' => array( 'can_see_role_contractor_fieldcolumn' ),
'items' => array( 'simple_grid_field22' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field22' => array( 'cols' => array( 22 ),
'rows' => array( 1 ),
'tags' => array( 'can_see_role_mgt_cny_fieldcolumn' ),
'items' => array( 'simple_grid_field23' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field23' => array( 'cols' => array( 23 ),
'rows' => array( 1 ),
'tags' => array( 'can_see_role_agent_fieldcolumn' ),
'items' => array( 'simple_grid_field24' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field24' => array( 'cols' => array( 24 ),
'rows' => array( 1 ),
'tags' => array( 'can_see_occupant_fieldcolumn' ),
'items' => array( 'simple_grid_field25' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field25' => array( 'cols' => array( 25 ),
'rows' => array( 1 ),
'tags' => array( 'can_see_role_landlord_fieldcolumn' ),
'items' => array( 'simple_grid_field26' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field26' => array( 'cols' => array( 26 ),
'rows' => array( 1 ),
'tags' => array( 'can_see_role_tenant_fieldcolumn' ),
'items' => array( 'simple_grid_field27' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field27' => array( 'cols' => array( 27 ),
'rows' => array( 1 ),
'tags' => array( 'is_public_fieldcolumn' ),
'items' => array( 'simple_grid_field28' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field28' => array( 'cols' => array( 28 ),
'rows' => array( 1 ),
'tags' => array( 'is_item_moved_fieldcolumn' ),
'items' => array( 'simple_grid_field29' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field29' => array( 'cols' => array( 29 ),
'rows' => array( 1 ),
'tags' => array( 'is_item_removed_fieldcolumn' ),
'items' => array( 'simple_grid_field30' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field30' => array( 'cols' => array( 30 ),
'rows' => array( 1 ),
'tags' => array( 'is_new_item_fieldcolumn' ),
'items' => array( 'simple_grid_field31' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field31' => array( 'cols' => array( 31 ),
'rows' => array( 1 ),
'tags' => array( 'is_new_ir_fieldcolumn' ),
'items' => array( 'simple_grid_field32' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field32' => array( 'cols' => array( 32 ),
'rows' => array( 1 ),
'tags' => array( 'is_message_from_contractor_fieldcolumn' ),
'items' => array( 'simple_grid_field33' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field33' => array( 'cols' => array( 33 ),
'rows' => array( 1 ),
'tags' => array( 'is_message_from_mgt_cny_fieldcolumn' ),
'items' => array( 'simple_grid_field34' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field34' => array( 'cols' => array( 34 ),
'rows' => array( 1 ),
'tags' => array( 'is_message_from_agent_fieldcolumn' ),
'items' => array( 'simple_grid_field35' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field35' => array( 'cols' => array( 35 ),
'rows' => array( 1 ),
'tags' => array( 'is_message_from_occupant_fieldcolumn' ),
'items' => array( 'simple_grid_field36' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field36' => array( 'cols' => array( 36 ),
'rows' => array( 1 ),
'tags' => array( 'is_message_from_ll_fieldcolumn' ),
'items' => array( 'simple_grid_field37' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field37' => array( 'cols' => array( 37 ),
'rows' => array( 1 ),
'tags' => array( 'is_message_from_tenant_fieldcolumn' ),
'items' => array( 'simple_grid_field38' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field38' => array( 'cols' => array( 38 ),
'rows' => array( 1 ),
'tags' => array( 'is_any_new_message_fieldcolumn' ),
'items' => array( 'simple_grid_field39' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field39' => array( 'cols' => array( 39 ),
'rows' => array( 1 ),
'tags' => array( 'is_case_critical_fieldcolumn' ),
'items' => array( 'simple_grid_field40' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field40' => array( 'cols' => array( 40 ),
'rows' => array( 1 ),
'tags' => array( 'is_case_blocker_fieldcolumn' ),
'items' => array( 'simple_grid_field41' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field41' => array( 'cols' => array( 41 ),
'rows' => array( 1 ),
'tags' => array( 'is_case_resolved_fieldcolumn' ),
'items' => array( 'simple_grid_field42' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field42' => array( 'cols' => array( 42 ),
'rows' => array( 1 ),
'tags' => array( 'is_solution_updated_fieldcolumn' ),
'items' => array( 'simple_grid_field43' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field43' => array( 'cols' => array( 43 ),
'rows' => array( 1 ),
'tags' => array( 'is_new_inventory_fieldcolumn' ),
'items' => array( 'simple_grid_field44' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field44' => array( 'cols' => array( 44 ),
'rows' => array( 1 ),
'tags' => array( 'is_occupant_fieldcolumn' ),
'items' => array( 'simple_grid_field45' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field45' => array( 'cols' => array( 45 ),
'rows' => array( 1 ),
'tags' => array( 'is_unit_owner_fieldcolumn' ),
'items' => array( 'simple_grid_field46' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field46' => array( 'cols' => array( 46 ),
'rows' => array( 1 ),
'tags' => array( 'is_default_invited_fieldcolumn' ),
'items' => array( 'simple_grid_field20' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field47' => array( 'cols' => array( 47 ),
'rows' => array( 1 ),
'tags' => array( 'is_all_unit_fieldcolumn' ),
'items' => array( 'simple_grid_field47' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field48' => array( 'cols' => array( 48 ),
'rows' => array( 1 ),
'tags' => array( 'is_all_units_in_country_fieldcolumn' ),
'items' => array( 'simple_grid_field48' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field49' => array( 'cols' => array( 49 ),
'rows' => array( 1 ),
'tags' => array( 'is_all_units_in_area_fieldcolumn' ),
'items' => array( 'simple_grid_field49' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field50' => array( 'cols' => array( 50 ),
'rows' => array( 1 ),
'tags' => array( 'is_all_units_in_level_1_fieldcolumn' ),
'items' => array( 'simple_grid_field50' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field51' => array( 'cols' => array( 51 ),
'rows' => array( 1 ),
'tags' => array( 'is_all_units_in_level_2_fieldcolumn' ),
'items' => array( 'simple_grid_field51' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field1' => array( 'cols' => array( 1 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field2' => array( 'cols' => array( 2 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field3' => array( 'cols' => array( 3 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field4' => array( 'cols' => array( 4 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field5' => array( 'cols' => array( 5 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field6' => array( 'cols' => array( 6 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field7' => array( 'cols' => array( 7 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field8' => array( 'cols' => array( 8 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field9' => array( 'cols' => array( 9 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field10' => array( 'cols' => array( 10 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field11' => array( 'cols' => array( 11 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field12' => array( 'cols' => array( 12 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field13' => array( 'cols' => array( 13 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field14' => array( 'cols' => array( 14 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field15' => array( 'cols' => array( 15 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field16' => array( 'cols' => array( 16 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field17' => array( 'cols' => array( 17 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field18' => array( 'cols' => array( 18 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field19' => array( 'cols' => array( 19 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field20' => array( 'cols' => array( 20 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field21' => array( 'cols' => array( 21 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field22' => array( 'cols' => array( 22 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field23' => array( 'cols' => array( 23 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field24' => array( 'cols' => array( 24 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field25' => array( 'cols' => array( 25 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field26' => array( 'cols' => array( 26 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field27' => array( 'cols' => array( 27 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field28' => array( 'cols' => array( 28 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field29' => array( 'cols' => array( 29 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field30' => array( 'cols' => array( 30 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field31' => array( 'cols' => array( 31 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field32' => array( 'cols' => array( 32 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field33' => array( 'cols' => array( 33 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field34' => array( 'cols' => array( 34 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field35' => array( 'cols' => array( 35 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field36' => array( 'cols' => array( 36 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field37' => array( 'cols' => array( 37 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field38' => array( 'cols' => array( 38 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field39' => array( 'cols' => array( 39 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field40' => array( 'cols' => array( 40 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field41' => array( 'cols' => array( 41 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field42' => array( 'cols' => array( 42 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field43' => array( 'cols' => array( 43 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field44' => array( 'cols' => array( 44 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field45' => array( 'cols' => array( 45 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field46' => array( 'cols' => array( 46 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field47' => array( 'cols' => array( 47 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field48' => array( 'cols' => array( 48 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field49' => array( 'cols' => array( 49 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field50' => array( 'cols' => array( 50 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field51' => array( 'cols' => array( 51 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ) ),
'width' => 52,
'height' => 3 ) ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ) ),
'gridType' => 0 ),
'misc' => array( 'type' => 'masterprint',
'breadcrumb' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'masterprint',
'type' => 'masterprint',
'layoutId' => 'masterprint',
'disabled' => 0,
'default' => 0,
'forms' => array( 'top' => array( 'modelId' => 'masterlist-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'masterprint_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'above-grid' => array( 'modelId' => 'empty-above-grid',
'grid' => array(  ),
'cells' => array(  ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'empty-above-grid',
'grid' => array(  ),
'cells' => array(  ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'horizontal-grid',
'grid' => array( array( 'section' => 'head',
'cells' => array( array( 'cell' => 'headcell_field' ),
array( 'cell' => 'headcell_field1' ),
array( 'cell' => 'headcell_field2' ),
array( 'cell' => 'headcell_field3' ),
array( 'cell' => 'headcell_field4' ),
array( 'cell' => 'headcell_field5' ),
array( 'cell' => 'headcell_field6' ),
array( 'cell' => 'headcell_field7' ),
array( 'cell' => 'headcell_field8' ),
array( 'cell' => 'headcell_field9' ),
array( 'cell' => 'headcell_field10' ),
array( 'cell' => 'headcell_field11' ),
array( 'cell' => 'headcell_field12' ),
array( 'cell' => 'headcell_field13' ),
array( 'cell' => 'headcell_field14' ),
array( 'cell' => 'headcell_field15' ),
array( 'cell' => 'headcell_field16' ),
array( 'cell' => 'headcell_field17' ),
array( 'cell' => 'headcell_field18' ),
array( 'cell' => 'headcell_field19' ),
array( 'cell' => 'headcell_field20' ),
array( 'cell' => 'headcell_field21' ),
array( 'cell' => 'headcell_field22' ),
array( 'cell' => 'headcell_field23' ),
array( 'cell' => 'headcell_field24' ),
array( 'cell' => 'headcell_field25' ),
array( 'cell' => 'headcell_field26' ),
array( 'cell' => 'headcell_field27' ),
array( 'cell' => 'headcell_field28' ),
array( 'cell' => 'headcell_field29' ),
array( 'cell' => 'headcell_field30' ),
array( 'cell' => 'headcell_field31' ),
array( 'cell' => 'headcell_field32' ),
array( 'cell' => 'headcell_field33' ),
array( 'cell' => 'headcell_field34' ),
array( 'cell' => 'headcell_field35' ),
array( 'cell' => 'headcell_field36' ),
array( 'cell' => 'headcell_field37' ),
array( 'cell' => 'headcell_field38' ),
array( 'cell' => 'headcell_field39' ),
array( 'cell' => 'headcell_field40' ),
array( 'cell' => 'headcell_field41' ),
array( 'cell' => 'headcell_field42' ),
array( 'cell' => 'headcell_field43' ),
array( 'cell' => 'headcell_field44' ),
array( 'cell' => 'headcell_field45' ),
array( 'cell' => 'headcell_field46' ),
array( 'cell' => 'headcell_field47' ),
array( 'cell' => 'headcell_field48' ),
array( 'cell' => 'headcell_field49' ),
array( 'cell' => 'headcell_field50' ),
array( 'cell' => 'headcell_field51' ) ) ),
array( 'section' => 'body',
'cells' => array( array( 'cell' => 'cell_field' ),
array( 'cell' => 'cell_field1' ),
array( 'cell' => 'cell_field2' ),
array( 'cell' => 'cell_field3' ),
array( 'cell' => 'cell_field4' ),
array( 'cell' => 'cell_field5' ),
array( 'cell' => 'cell_field6' ),
array( 'cell' => 'cell_field7' ),
array( 'cell' => 'cell_field8' ),
array( 'cell' => 'cell_field9' ),
array( 'cell' => 'cell_field10' ),
array( 'cell' => 'cell_field11' ),
array( 'cell' => 'cell_field12' ),
array( 'cell' => 'cell_field13' ),
array( 'cell' => 'cell_field14' ),
array( 'cell' => 'cell_field15' ),
array( 'cell' => 'cell_field16' ),
array( 'cell' => 'cell_field17' ),
array( 'cell' => 'cell_field18' ),
array( 'cell' => 'cell_field19' ),
array( 'cell' => 'cell_field20' ),
array( 'cell' => 'cell_field21' ),
array( 'cell' => 'cell_field22' ),
array( 'cell' => 'cell_field23' ),
array( 'cell' => 'cell_field24' ),
array( 'cell' => 'cell_field25' ),
array( 'cell' => 'cell_field26' ),
array( 'cell' => 'cell_field27' ),
array( 'cell' => 'cell_field28' ),
array( 'cell' => 'cell_field29' ),
array( 'cell' => 'cell_field30' ),
array( 'cell' => 'cell_field31' ),
array( 'cell' => 'cell_field32' ),
array( 'cell' => 'cell_field33' ),
array( 'cell' => 'cell_field34' ),
array( 'cell' => 'cell_field35' ),
array( 'cell' => 'cell_field36' ),
array( 'cell' => 'cell_field37' ),
array( 'cell' => 'cell_field38' ),
array( 'cell' => 'cell_field39' ),
array( 'cell' => 'cell_field40' ),
array( 'cell' => 'cell_field41' ),
array( 'cell' => 'cell_field42' ),
array( 'cell' => 'cell_field43' ),
array( 'cell' => 'cell_field44' ),
array( 'cell' => 'cell_field45' ),
array( 'cell' => 'cell_field46' ),
array( 'cell' => 'cell_field47' ),
array( 'cell' => 'cell_field48' ),
array( 'cell' => 'cell_field49' ),
array( 'cell' => 'cell_field50' ),
array( 'cell' => 'cell_field51' ) ) ),
array( 'section' => 'foot',
'cells' => array( array( 'cell' => 'footcell_field' ),
array( 'cell' => 'footcell_field1' ),
array( 'cell' => 'footcell_field2' ),
array( 'cell' => 'footcell_field3' ),
array( 'cell' => 'footcell_field4' ),
array( 'cell' => 'footcell_field5' ),
array( 'cell' => 'footcell_field6' ),
array( 'cell' => 'footcell_field7' ),
array( 'cell' => 'footcell_field8' ),
array( 'cell' => 'footcell_field9' ),
array( 'cell' => 'footcell_field10' ),
array( 'cell' => 'footcell_field11' ),
array( 'cell' => 'footcell_field12' ),
array( 'cell' => 'footcell_field13' ),
array( 'cell' => 'footcell_field14' ),
array( 'cell' => 'footcell_field15' ),
array( 'cell' => 'footcell_field16' ),
array( 'cell' => 'footcell_field17' ),
array( 'cell' => 'footcell_field18' ),
array( 'cell' => 'footcell_field19' ),
array( 'cell' => 'footcell_field20' ),
array( 'cell' => 'footcell_field21' ),
array( 'cell' => 'footcell_field22' ),
array( 'cell' => 'footcell_field23' ),
array( 'cell' => 'footcell_field24' ),
array( 'cell' => 'footcell_field25' ),
array( 'cell' => 'footcell_field26' ),
array( 'cell' => 'footcell_field27' ),
array( 'cell' => 'footcell_field28' ),
array( 'cell' => 'footcell_field29' ),
array( 'cell' => 'footcell_field30' ),
array( 'cell' => 'footcell_field31' ),
array( 'cell' => 'footcell_field32' ),
array( 'cell' => 'footcell_field33' ),
array( 'cell' => 'footcell_field34' ),
array( 'cell' => 'footcell_field35' ),
array( 'cell' => 'footcell_field36' ),
array( 'cell' => 'footcell_field37' ),
array( 'cell' => 'footcell_field38' ),
array( 'cell' => 'footcell_field39' ),
array( 'cell' => 'footcell_field40' ),
array( 'cell' => 'footcell_field41' ),
array( 'cell' => 'footcell_field42' ),
array( 'cell' => 'footcell_field43' ),
array( 'cell' => 'footcell_field44' ),
array( 'cell' => 'footcell_field45' ),
array( 'cell' => 'footcell_field46' ),
array( 'cell' => 'footcell_field47' ),
array( 'cell' => 'footcell_field48' ),
array( 'cell' => 'footcell_field49' ),
array( 'cell' => 'footcell_field50' ),
array( 'cell' => 'footcell_field51' ) ) ) ),
'cells' => array( 'headcell_field' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field52' ),
'field' => 'id_unee_t_user_type',
'columnName' => 'field' ),
'cell_field' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field' ),
'field' => 'id_unee_t_user_type',
'columnName' => 'field' ),
'footcell_field' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field1' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field53' ),
'field' => 'syst_created_datetime',
'columnName' => 'field' ),
'cell_field1' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field1' ),
'field' => 'syst_created_datetime',
'columnName' => 'field' ),
'footcell_field1' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field2' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field54' ),
'field' => 'creation_system_id',
'columnName' => 'field' ),
'cell_field2' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field2' ),
'field' => 'creation_system_id',
'columnName' => 'field' ),
'footcell_field2' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field3' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field55' ),
'field' => 'created_by_id',
'columnName' => 'field' ),
'cell_field3' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field3' ),
'field' => 'created_by_id',
'columnName' => 'field' ),
'footcell_field3' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field4' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field56' ),
'field' => 'creation_method',
'columnName' => 'field' ),
'cell_field4' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field4' ),
'field' => 'creation_method',
'columnName' => 'field' ),
'footcell_field4' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field5' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field57' ),
'field' => 'syst_updated_datetime',
'columnName' => 'field' ),
'cell_field5' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field5' ),
'field' => 'syst_updated_datetime',
'columnName' => 'field' ),
'footcell_field5' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field6' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field58' ),
'field' => 'update_system_id',
'columnName' => 'field' ),
'cell_field6' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field6' ),
'field' => 'update_system_id',
'columnName' => 'field' ),
'footcell_field6' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field7' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field59' ),
'field' => 'updated_by_id',
'columnName' => 'field' ),
'cell_field7' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field7' ),
'field' => 'updated_by_id',
'columnName' => 'field' ),
'footcell_field7' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field8' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field60' ),
'field' => 'update_method',
'columnName' => 'field' ),
'cell_field8' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field8' ),
'field' => 'update_method',
'columnName' => 'field' ),
'footcell_field8' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field9' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field61' ),
'field' => 'organization_id',
'columnName' => 'field' ),
'cell_field9' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field9' ),
'field' => 'organization_id',
'columnName' => 'field' ),
'footcell_field9' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field10' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field62' ),
'field' => 'order',
'columnName' => 'field' ),
'cell_field10' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field10' ),
'field' => 'order',
'columnName' => 'field' ),
'footcell_field10' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field11' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field63' ),
'field' => 'is_obsolete',
'columnName' => 'field' ),
'cell_field11' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field11' ),
'field' => 'is_obsolete',
'columnName' => 'field' ),
'footcell_field11' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field12' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field64' ),
'field' => 'description',
'columnName' => 'field' ),
'cell_field12' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field13' ),
'field' => 'description',
'columnName' => 'field' ),
'footcell_field12' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field13' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field65' ),
'field' => 'ut_user_role_type_id',
'columnName' => 'field' ),
'cell_field13' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field12' ),
'field' => 'ut_user_role_type_id',
'columnName' => 'field' ),
'footcell_field13' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field14' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field66' ),
'field' => 'designation',
'columnName' => 'field' ),
'cell_field14' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field14' ),
'field' => 'designation',
'columnName' => 'field' ),
'footcell_field14' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field15' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field67' ),
'field' => 'is_assigned_to_case',
'columnName' => 'field' ),
'cell_field15' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field15' ),
'field' => 'is_assigned_to_case',
'columnName' => 'field' ),
'footcell_field15' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field16' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field68' ),
'field' => 'is_invited_to_case',
'columnName' => 'field' ),
'cell_field16' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field16' ),
'field' => 'is_invited_to_case',
'columnName' => 'field' ),
'footcell_field16' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field17' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field69' ),
'field' => 'is_next_step_updated',
'columnName' => 'field' ),
'cell_field17' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field17' ),
'field' => 'is_next_step_updated',
'columnName' => 'field' ),
'footcell_field17' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field18' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field70' ),
'field' => 'is_deadline_updated',
'columnName' => 'field' ),
'cell_field18' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field18' ),
'field' => 'is_deadline_updated',
'columnName' => 'field' ),
'footcell_field18' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field19' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field71' ),
'field' => 'is_dashboard_access',
'columnName' => 'field' ),
'cell_field19' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field19' ),
'field' => 'is_dashboard_access',
'columnName' => 'field' ),
'footcell_field19' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field20' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field72' ),
'field' => 'is_default_assignee',
'columnName' => 'field' ),
'cell_field20' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field21' ),
'field' => 'is_default_assignee',
'columnName' => 'field' ),
'footcell_field20' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field21' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field73' ),
'field' => 'can_see_role_contractor',
'columnName' => 'field' ),
'cell_field21' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field22' ),
'field' => 'can_see_role_contractor',
'columnName' => 'field' ),
'footcell_field21' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field22' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field74' ),
'field' => 'can_see_role_mgt_cny',
'columnName' => 'field' ),
'cell_field22' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field23' ),
'field' => 'can_see_role_mgt_cny',
'columnName' => 'field' ),
'footcell_field22' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field23' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field75' ),
'field' => 'can_see_role_agent',
'columnName' => 'field' ),
'cell_field23' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field24' ),
'field' => 'can_see_role_agent',
'columnName' => 'field' ),
'footcell_field23' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field24' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field76' ),
'field' => 'can_see_occupant',
'columnName' => 'field' ),
'cell_field24' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field25' ),
'field' => 'can_see_occupant',
'columnName' => 'field' ),
'footcell_field24' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field25' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field77' ),
'field' => 'can_see_role_landlord',
'columnName' => 'field' ),
'cell_field25' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field26' ),
'field' => 'can_see_role_landlord',
'columnName' => 'field' ),
'footcell_field25' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field26' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field78' ),
'field' => 'can_see_role_tenant',
'columnName' => 'field' ),
'cell_field26' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field27' ),
'field' => 'can_see_role_tenant',
'columnName' => 'field' ),
'footcell_field26' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field27' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field79' ),
'field' => 'is_public',
'columnName' => 'field' ),
'cell_field27' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field28' ),
'field' => 'is_public',
'columnName' => 'field' ),
'footcell_field27' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field28' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field80' ),
'field' => 'is_item_moved',
'columnName' => 'field' ),
'cell_field28' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field29' ),
'field' => 'is_item_moved',
'columnName' => 'field' ),
'footcell_field28' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field29' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field81' ),
'field' => 'is_item_removed',
'columnName' => 'field' ),
'cell_field29' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field30' ),
'field' => 'is_item_removed',
'columnName' => 'field' ),
'footcell_field29' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field30' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field82' ),
'field' => 'is_new_item',
'columnName' => 'field' ),
'cell_field30' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field31' ),
'field' => 'is_new_item',
'columnName' => 'field' ),
'footcell_field30' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field31' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field83' ),
'field' => 'is_new_ir',
'columnName' => 'field' ),
'cell_field31' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field32' ),
'field' => 'is_new_ir',
'columnName' => 'field' ),
'footcell_field31' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field32' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field84' ),
'field' => 'is_message_from_contractor',
'columnName' => 'field' ),
'cell_field32' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field33' ),
'field' => 'is_message_from_contractor',
'columnName' => 'field' ),
'footcell_field32' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field33' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field85' ),
'field' => 'is_message_from_mgt_cny',
'columnName' => 'field' ),
'cell_field33' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field34' ),
'field' => 'is_message_from_mgt_cny',
'columnName' => 'field' ),
'footcell_field33' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field34' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field86' ),
'field' => 'is_message_from_agent',
'columnName' => 'field' ),
'cell_field34' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field35' ),
'field' => 'is_message_from_agent',
'columnName' => 'field' ),
'footcell_field34' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field35' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field87' ),
'field' => 'is_message_from_occupant',
'columnName' => 'field' ),
'cell_field35' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field36' ),
'field' => 'is_message_from_occupant',
'columnName' => 'field' ),
'footcell_field35' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field36' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field88' ),
'field' => 'is_message_from_ll',
'columnName' => 'field' ),
'cell_field36' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field37' ),
'field' => 'is_message_from_ll',
'columnName' => 'field' ),
'footcell_field36' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field37' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field89' ),
'field' => 'is_message_from_tenant',
'columnName' => 'field' ),
'cell_field37' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field38' ),
'field' => 'is_message_from_tenant',
'columnName' => 'field' ),
'footcell_field37' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field38' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field90' ),
'field' => 'is_any_new_message',
'columnName' => 'field' ),
'cell_field38' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field39' ),
'field' => 'is_any_new_message',
'columnName' => 'field' ),
'footcell_field38' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field39' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field91' ),
'field' => 'is_case_critical',
'columnName' => 'field' ),
'cell_field39' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field40' ),
'field' => 'is_case_critical',
'columnName' => 'field' ),
'footcell_field39' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field40' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field92' ),
'field' => 'is_case_blocker',
'columnName' => 'field' ),
'cell_field40' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field41' ),
'field' => 'is_case_blocker',
'columnName' => 'field' ),
'footcell_field40' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field41' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field93' ),
'field' => 'is_case_resolved',
'columnName' => 'field' ),
'cell_field41' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field42' ),
'field' => 'is_case_resolved',
'columnName' => 'field' ),
'footcell_field41' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field42' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field94' ),
'field' => 'is_solution_updated',
'columnName' => 'field' ),
'cell_field42' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field43' ),
'field' => 'is_solution_updated',
'columnName' => 'field' ),
'footcell_field42' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field43' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field95' ),
'field' => 'is_new_inventory',
'columnName' => 'field' ),
'cell_field43' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field44' ),
'field' => 'is_new_inventory',
'columnName' => 'field' ),
'footcell_field43' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field44' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field96' ),
'field' => 'is_occupant',
'columnName' => 'field' ),
'cell_field44' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field45' ),
'field' => 'is_occupant',
'columnName' => 'field' ),
'footcell_field44' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field45' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field97' ),
'field' => 'is_unit_owner',
'columnName' => 'field' ),
'cell_field45' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field46' ),
'field' => 'is_unit_owner',
'columnName' => 'field' ),
'footcell_field45' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field46' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field98' ),
'field' => 'is_default_invited',
'columnName' => 'field' ),
'cell_field46' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field20' ),
'field' => 'is_default_invited',
'columnName' => 'field' ),
'footcell_field46' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field47' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field99' ),
'field' => 'is_all_unit',
'columnName' => 'field' ),
'cell_field47' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field47' ),
'field' => 'is_all_unit',
'columnName' => 'field' ),
'footcell_field47' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field48' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field100' ),
'field' => 'is_all_units_in_country',
'columnName' => 'field' ),
'cell_field48' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field48' ),
'field' => 'is_all_units_in_country',
'columnName' => 'field' ),
'footcell_field48' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field49' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field101' ),
'field' => 'is_all_units_in_area',
'columnName' => 'field' ),
'cell_field49' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field49' ),
'field' => 'is_all_units_in_area',
'columnName' => 'field' ),
'footcell_field49' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field50' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field102' ),
'field' => 'is_all_units_in_level_1',
'columnName' => 'field' ),
'cell_field50' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field50' ),
'field' => 'is_all_units_in_level_1',
'columnName' => 'field' ),
'footcell_field50' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field51' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field103' ),
'field' => 'is_all_units_in_level_2',
'columnName' => 'field' ),
'cell_field51' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field51' ),
'field' => 'is_all_units_in_level_2',
'columnName' => 'field' ),
'footcell_field51' => array( 'model' => 'footcell_field',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'masterprint_header' => array( 'type' => 'masterprint_header' ),
'simple_grid_field' => array( 'field' => 'id_unee_t_user_type',
'type' => 'grid_field' ),
'simple_grid_field52' => array( 'type' => 'grid_field_label',
'field' => 'id_unee_t_user_type' ),
'simple_grid_field1' => array( 'field' => 'syst_created_datetime',
'type' => 'grid_field' ),
'simple_grid_field53' => array( 'type' => 'grid_field_label',
'field' => 'syst_created_datetime' ),
'simple_grid_field2' => array( 'field' => 'creation_system_id',
'type' => 'grid_field' ),
'simple_grid_field54' => array( 'type' => 'grid_field_label',
'field' => 'creation_system_id' ),
'simple_grid_field3' => array( 'field' => 'created_by_id',
'type' => 'grid_field' ),
'simple_grid_field55' => array( 'type' => 'grid_field_label',
'field' => 'created_by_id' ),
'simple_grid_field4' => array( 'field' => 'creation_method',
'type' => 'grid_field' ),
'simple_grid_field56' => array( 'type' => 'grid_field_label',
'field' => 'creation_method' ),
'simple_grid_field5' => array( 'field' => 'syst_updated_datetime',
'type' => 'grid_field' ),
'simple_grid_field57' => array( 'type' => 'grid_field_label',
'field' => 'syst_updated_datetime' ),
'simple_grid_field6' => array( 'field' => 'update_system_id',
'type' => 'grid_field' ),
'simple_grid_field58' => array( 'type' => 'grid_field_label',
'field' => 'update_system_id' ),
'simple_grid_field7' => array( 'field' => 'updated_by_id',
'type' => 'grid_field' ),
'simple_grid_field59' => array( 'type' => 'grid_field_label',
'field' => 'updated_by_id' ),
'simple_grid_field8' => array( 'field' => 'update_method',
'type' => 'grid_field' ),
'simple_grid_field60' => array( 'type' => 'grid_field_label',
'field' => 'update_method' ),
'simple_grid_field9' => array( 'field' => 'organization_id',
'type' => 'grid_field' ),
'simple_grid_field61' => array( 'type' => 'grid_field_label',
'field' => 'organization_id' ),
'simple_grid_field10' => array( 'field' => 'order',
'type' => 'grid_field' ),
'simple_grid_field62' => array( 'type' => 'grid_field_label',
'field' => 'order' ),
'simple_grid_field11' => array( 'field' => 'is_obsolete',
'type' => 'grid_field' ),
'simple_grid_field63' => array( 'type' => 'grid_field_label',
'field' => 'is_obsolete' ),
'simple_grid_field13' => array( 'field' => 'description',
'type' => 'grid_field' ),
'simple_grid_field64' => array( 'type' => 'grid_field_label',
'field' => 'description' ),
'simple_grid_field12' => array( 'field' => 'ut_user_role_type_id',
'type' => 'grid_field' ),
'simple_grid_field65' => array( 'type' => 'grid_field_label',
'field' => 'ut_user_role_type_id' ),
'simple_grid_field14' => array( 'field' => 'designation',
'type' => 'grid_field' ),
'simple_grid_field66' => array( 'type' => 'grid_field_label',
'field' => 'designation' ),
'simple_grid_field15' => array( 'field' => 'is_assigned_to_case',
'type' => 'grid_field' ),
'simple_grid_field67' => array( 'type' => 'grid_field_label',
'field' => 'is_assigned_to_case' ),
'simple_grid_field16' => array( 'field' => 'is_invited_to_case',
'type' => 'grid_field' ),
'simple_grid_field68' => array( 'type' => 'grid_field_label',
'field' => 'is_invited_to_case' ),
'simple_grid_field17' => array( 'field' => 'is_next_step_updated',
'type' => 'grid_field' ),
'simple_grid_field69' => array( 'type' => 'grid_field_label',
'field' => 'is_next_step_updated' ),
'simple_grid_field18' => array( 'field' => 'is_deadline_updated',
'type' => 'grid_field' ),
'simple_grid_field70' => array( 'type' => 'grid_field_label',
'field' => 'is_deadline_updated' ),
'simple_grid_field19' => array( 'field' => 'is_dashboard_access',
'type' => 'grid_field' ),
'simple_grid_field71' => array( 'type' => 'grid_field_label',
'field' => 'is_dashboard_access' ),
'simple_grid_field21' => array( 'field' => 'is_default_assignee',
'type' => 'grid_field' ),
'simple_grid_field72' => array( 'type' => 'grid_field_label',
'field' => 'is_default_assignee' ),
'simple_grid_field22' => array( 'field' => 'can_see_role_contractor',
'type' => 'grid_field' ),
'simple_grid_field73' => array( 'type' => 'grid_field_label',
'field' => 'can_see_role_contractor' ),
'simple_grid_field23' => array( 'field' => 'can_see_role_mgt_cny',
'type' => 'grid_field' ),
'simple_grid_field74' => array( 'type' => 'grid_field_label',
'field' => 'can_see_role_mgt_cny' ),
'simple_grid_field24' => array( 'field' => 'can_see_role_agent',
'type' => 'grid_field' ),
'simple_grid_field75' => array( 'type' => 'grid_field_label',
'field' => 'can_see_role_agent' ),
'simple_grid_field25' => array( 'field' => 'can_see_occupant',
'type' => 'grid_field' ),
'simple_grid_field76' => array( 'type' => 'grid_field_label',
'field' => 'can_see_occupant' ),
'simple_grid_field26' => array( 'field' => 'can_see_role_landlord',
'type' => 'grid_field' ),
'simple_grid_field77' => array( 'type' => 'grid_field_label',
'field' => 'can_see_role_landlord' ),
'simple_grid_field27' => array( 'field' => 'can_see_role_tenant',
'type' => 'grid_field' ),
'simple_grid_field78' => array( 'type' => 'grid_field_label',
'field' => 'can_see_role_tenant' ),
'simple_grid_field28' => array( 'field' => 'is_public',
'type' => 'grid_field' ),
'simple_grid_field79' => array( 'type' => 'grid_field_label',
'field' => 'is_public' ),
'simple_grid_field29' => array( 'field' => 'is_item_moved',
'type' => 'grid_field' ),
'simple_grid_field80' => array( 'type' => 'grid_field_label',
'field' => 'is_item_moved' ),
'simple_grid_field30' => array( 'field' => 'is_item_removed',
'type' => 'grid_field' ),
'simple_grid_field81' => array( 'type' => 'grid_field_label',
'field' => 'is_item_removed' ),
'simple_grid_field31' => array( 'field' => 'is_new_item',
'type' => 'grid_field' ),
'simple_grid_field82' => array( 'type' => 'grid_field_label',
'field' => 'is_new_item' ),
'simple_grid_field32' => array( 'field' => 'is_new_ir',
'type' => 'grid_field' ),
'simple_grid_field83' => array( 'type' => 'grid_field_label',
'field' => 'is_new_ir' ),
'simple_grid_field33' => array( 'field' => 'is_message_from_contractor',
'type' => 'grid_field' ),
'simple_grid_field84' => array( 'type' => 'grid_field_label',
'field' => 'is_message_from_contractor' ),
'simple_grid_field34' => array( 'field' => 'is_message_from_mgt_cny',
'type' => 'grid_field' ),
'simple_grid_field85' => array( 'type' => 'grid_field_label',
'field' => 'is_message_from_mgt_cny' ),
'simple_grid_field35' => array( 'field' => 'is_message_from_agent',
'type' => 'grid_field' ),
'simple_grid_field86' => array( 'type' => 'grid_field_label',
'field' => 'is_message_from_agent' ),
'simple_grid_field36' => array( 'field' => 'is_message_from_occupant',
'type' => 'grid_field' ),
'simple_grid_field87' => array( 'type' => 'grid_field_label',
'field' => 'is_message_from_occupant' ),
'simple_grid_field37' => array( 'field' => 'is_message_from_ll',
'type' => 'grid_field' ),
'simple_grid_field88' => array( 'type' => 'grid_field_label',
'field' => 'is_message_from_ll' ),
'simple_grid_field38' => array( 'field' => 'is_message_from_tenant',
'type' => 'grid_field' ),
'simple_grid_field89' => array( 'type' => 'grid_field_label',
'field' => 'is_message_from_tenant' ),
'simple_grid_field39' => array( 'field' => 'is_any_new_message',
'type' => 'grid_field' ),
'simple_grid_field90' => array( 'type' => 'grid_field_label',
'field' => 'is_any_new_message' ),
'simple_grid_field40' => array( 'field' => 'is_case_critical',
'type' => 'grid_field' ),
'simple_grid_field91' => array( 'type' => 'grid_field_label',
'field' => 'is_case_critical' ),
'simple_grid_field41' => array( 'field' => 'is_case_blocker',
'type' => 'grid_field' ),
'simple_grid_field92' => array( 'type' => 'grid_field_label',
'field' => 'is_case_blocker' ),
'simple_grid_field42' => array( 'field' => 'is_case_resolved',
'type' => 'grid_field' ),
'simple_grid_field93' => array( 'type' => 'grid_field_label',
'field' => 'is_case_resolved' ),
'simple_grid_field43' => array( 'field' => 'is_solution_updated',
'type' => 'grid_field' ),
'simple_grid_field94' => array( 'type' => 'grid_field_label',
'field' => 'is_solution_updated' ),
'simple_grid_field44' => array( 'field' => 'is_new_inventory',
'type' => 'grid_field' ),
'simple_grid_field95' => array( 'type' => 'grid_field_label',
'field' => 'is_new_inventory' ),
'simple_grid_field45' => array( 'field' => 'is_occupant',
'type' => 'grid_field' ),
'simple_grid_field96' => array( 'type' => 'grid_field_label',
'field' => 'is_occupant' ),
'simple_grid_field46' => array( 'field' => 'is_unit_owner',
'type' => 'grid_field' ),
'simple_grid_field97' => array( 'type' => 'grid_field_label',
'field' => 'is_unit_owner' ),
'simple_grid_field20' => array( 'field' => 'is_default_invited',
'type' => 'grid_field' ),
'simple_grid_field98' => array( 'type' => 'grid_field_label',
'field' => 'is_default_invited' ),
'simple_grid_field47' => array( 'field' => 'is_all_unit',
'type' => 'grid_field' ),
'simple_grid_field99' => array( 'type' => 'grid_field_label',
'field' => 'is_all_unit' ),
'simple_grid_field48' => array( 'field' => 'is_all_units_in_country',
'type' => 'grid_field' ),
'simple_grid_field100' => array( 'type' => 'grid_field_label',
'field' => 'is_all_units_in_country' ),
'simple_grid_field49' => array( 'field' => 'is_all_units_in_area',
'type' => 'grid_field' ),
'simple_grid_field101' => array( 'type' => 'grid_field_label',
'field' => 'is_all_units_in_area' ),
'simple_grid_field50' => array( 'field' => 'is_all_units_in_level_1',
'type' => 'grid_field' ),
'simple_grid_field102' => array( 'type' => 'grid_field_label',
'field' => 'is_all_units_in_level_1' ),
'simple_grid_field51' => array( 'field' => 'is_all_units_in_level_2',
'type' => 'grid_field' ),
'simple_grid_field103' => array( 'type' => 'grid_field_label',
'field' => 'is_all_units_in_level_2' ) ),
'dbProps' => array(  ),
'version' => 2 );
		?>