<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array( 'id_unee_t_user_type',
'syst_created_datetime',
'creation_system_id',
'created_by_id',
'syst_updated_datetime',
'update_system_id',
'updated_by_id',
'order',
'is_obsolete',
'ut_user_role_type_id',
'description',
'creation_method',
'update_method',
'organization_id',
'designation',
'is_assigned_to_case',
'is_invited_to_case',
'is_next_step_updated',
'is_deadline_updated',
'is_dashboard_access',
'is_default_invited',
'is_default_assignee',
'can_see_role_contractor',
'can_see_role_mgt_cny',
'can_see_role_agent',
'can_see_occupant',
'can_see_role_landlord',
'can_see_role_tenant',
'is_public',
'is_item_moved',
'is_item_removed',
'is_new_item',
'is_new_ir',
'is_message_from_contractor',
'is_message_from_mgt_cny',
'is_message_from_agent',
'is_message_from_occupant',
'is_message_from_ll',
'is_message_from_tenant',
'is_any_new_message',
'is_case_critical',
'is_case_blocker',
'is_case_resolved',
'is_solution_updated',
'is_new_inventory',
'is_occupant',
'is_unit_owner',
'is_all_unit',
'is_all_units_in_country',
'is_all_units_in_area',
'is_all_units_in_level_1',
'is_all_units_in_level_2' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'id_unee_t_user_type' => array( 'integrated_search_field' ),
'syst_created_datetime' => array( 'integrated_search_field1' ),
'creation_system_id' => array( 'integrated_search_field2' ),
'created_by_id' => array( 'integrated_search_field3' ),
'syst_updated_datetime' => array( 'integrated_search_field4' ),
'update_system_id' => array( 'integrated_search_field5' ),
'updated_by_id' => array( 'integrated_search_field6' ),
'order' => array( 'integrated_search_field7' ),
'is_obsolete' => array( 'integrated_search_field8' ),
'ut_user_role_type_id' => array( 'integrated_search_field9' ),
'description' => array( 'integrated_search_field10' ),
'creation_method' => array( 'integrated_search_field11' ),
'update_method' => array( 'integrated_search_field12' ),
'organization_id' => array( 'integrated_search_field13' ),
'designation' => array( 'integrated_search_field14' ),
'is_assigned_to_case' => array( 'integrated_search_field15' ),
'is_invited_to_case' => array( 'integrated_search_field16' ),
'is_next_step_updated' => array( 'integrated_search_field17' ),
'is_deadline_updated' => array( 'integrated_search_field18' ),
'is_dashboard_access' => array( 'integrated_search_field19' ),
'is_default_invited' => array( 'integrated_search_field20' ),
'is_default_assignee' => array( 'integrated_search_field21' ),
'can_see_role_contractor' => array( 'integrated_search_field22' ),
'can_see_role_mgt_cny' => array( 'integrated_search_field23' ),
'can_see_role_agent' => array( 'integrated_search_field24' ),
'can_see_occupant' => array( 'integrated_search_field25' ),
'can_see_role_landlord' => array( 'integrated_search_field26' ),
'can_see_role_tenant' => array( 'integrated_search_field27' ),
'is_public' => array( 'integrated_search_field28' ),
'is_item_moved' => array( 'integrated_search_field29' ),
'is_item_removed' => array( 'integrated_search_field30' ),
'is_new_item' => array( 'integrated_search_field31' ),
'is_new_ir' => array( 'integrated_search_field32' ),
'is_message_from_contractor' => array( 'integrated_search_field33' ),
'is_message_from_mgt_cny' => array( 'integrated_search_field34' ),
'is_message_from_agent' => array( 'integrated_search_field35' ),
'is_message_from_occupant' => array( 'integrated_search_field36' ),
'is_message_from_ll' => array( 'integrated_search_field37' ),
'is_message_from_tenant' => array( 'integrated_search_field38' ),
'is_any_new_message' => array( 'integrated_search_field39' ),
'is_case_critical' => array( 'integrated_search_field40' ),
'is_case_blocker' => array( 'integrated_search_field41' ),
'is_case_resolved' => array( 'integrated_search_field42' ),
'is_solution_updated' => array( 'integrated_search_field43' ),
'is_new_inventory' => array( 'integrated_search_field44' ),
'is_occupant' => array( 'integrated_search_field45' ),
'is_unit_owner' => array( 'integrated_search_field46' ),
'is_all_unit' => array( 'integrated_search_field47' ),
'is_all_units_in_country' => array( 'integrated_search_field48' ),
'is_all_units_in_area' => array( 'integrated_search_field49' ),
'is_all_units_in_level_1' => array( 'integrated_search_field50' ),
'is_all_units_in_level_2' => array( 'integrated_search_field51' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'top' => array( 'search_header' ),
'above-grid' => array(  ),
'below-grid' => array( 'search_search',
'search_reset',
'search_back_list' ),
'grid' => array( 'integrated_search_field',
'integrated_search_field1',
'integrated_search_field2',
'integrated_search_field3',
'integrated_search_field4',
'integrated_search_field5',
'integrated_search_field6',
'integrated_search_field7',
'integrated_search_field8',
'integrated_search_field10',
'integrated_search_field11',
'integrated_search_field12',
'integrated_search_field13',
'integrated_search_field9',
'integrated_search_field14',
'integrated_search_field15',
'integrated_search_field16',
'integrated_search_field17',
'integrated_search_field18',
'integrated_search_field19',
'integrated_search_field21',
'integrated_search_field22',
'integrated_search_field23',
'integrated_search_field24',
'integrated_search_field25',
'integrated_search_field26',
'integrated_search_field27',
'integrated_search_field28',
'integrated_search_field29',
'integrated_search_field30',
'integrated_search_field31',
'integrated_search_field32',
'integrated_search_field33',
'integrated_search_field34',
'integrated_search_field35',
'integrated_search_field36',
'integrated_search_field37',
'integrated_search_field38',
'integrated_search_field39',
'integrated_search_field40',
'integrated_search_field41',
'integrated_search_field42',
'integrated_search_field43',
'integrated_search_field44',
'integrated_search_field45',
'integrated_search_field46',
'integrated_search_field20',
'integrated_search_field47',
'integrated_search_field48',
'integrated_search_field49',
'integrated_search_field50',
'integrated_search_field51' ) ),
'formXtTags' => array( 'above-grid' => array(  ) ),
'itemForms' => array( 'search_header' => 'top',
'search_search' => 'below-grid',
'search_reset' => 'below-grid',
'search_back_list' => 'below-grid',
'integrated_search_field' => 'grid',
'integrated_search_field1' => 'grid',
'integrated_search_field2' => 'grid',
'integrated_search_field3' => 'grid',
'integrated_search_field4' => 'grid',
'integrated_search_field5' => 'grid',
'integrated_search_field6' => 'grid',
'integrated_search_field7' => 'grid',
'integrated_search_field8' => 'grid',
'integrated_search_field10' => 'grid',
'integrated_search_field11' => 'grid',
'integrated_search_field12' => 'grid',
'integrated_search_field13' => 'grid',
'integrated_search_field9' => 'grid',
'integrated_search_field14' => 'grid',
'integrated_search_field15' => 'grid',
'integrated_search_field16' => 'grid',
'integrated_search_field17' => 'grid',
'integrated_search_field18' => 'grid',
'integrated_search_field19' => 'grid',
'integrated_search_field21' => 'grid',
'integrated_search_field22' => 'grid',
'integrated_search_field23' => 'grid',
'integrated_search_field24' => 'grid',
'integrated_search_field25' => 'grid',
'integrated_search_field26' => 'grid',
'integrated_search_field27' => 'grid',
'integrated_search_field28' => 'grid',
'integrated_search_field29' => 'grid',
'integrated_search_field30' => 'grid',
'integrated_search_field31' => 'grid',
'integrated_search_field32' => 'grid',
'integrated_search_field33' => 'grid',
'integrated_search_field34' => 'grid',
'integrated_search_field35' => 'grid',
'integrated_search_field36' => 'grid',
'integrated_search_field37' => 'grid',
'integrated_search_field38' => 'grid',
'integrated_search_field39' => 'grid',
'integrated_search_field40' => 'grid',
'integrated_search_field41' => 'grid',
'integrated_search_field42' => 'grid',
'integrated_search_field43' => 'grid',
'integrated_search_field44' => 'grid',
'integrated_search_field45' => 'grid',
'integrated_search_field46' => 'grid',
'integrated_search_field20' => 'grid',
'integrated_search_field47' => 'grid',
'integrated_search_field48' => 'grid',
'integrated_search_field49' => 'grid',
'integrated_search_field50' => 'grid',
'integrated_search_field51' => 'grid' ),
'itemLocations' => array( 'integrated_search_field' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field1' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field2' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field3' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field4' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field5' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field6' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field7' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field8' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field10' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field11' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field12' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field13' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field9' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field14' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field15' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field16' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field17' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field18' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field19' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field21' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field22' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field23' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field24' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field25' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field26' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field27' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field28' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field29' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field30' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field31' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field32' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field33' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field34' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field35' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field36' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field37' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field38' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field39' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field40' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field41' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field42' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field43' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field44' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field45' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field46' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field20' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field47' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field48' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field49' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field50' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field51' => array( 'location' => 'grid',
'cellId' => 'c3' ) ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'search_header' => array( 'search_header' ),
'search_reset' => array( 'search_reset' ),
'search_back_list' => array( 'search_back_list' ),
'search_search' => array( 'search_search' ),
'integrated_search_field' => array( 'integrated_search_field',
'integrated_search_field1',
'integrated_search_field2',
'integrated_search_field3',
'integrated_search_field4',
'integrated_search_field5',
'integrated_search_field6',
'integrated_search_field7',
'integrated_search_field8',
'integrated_search_field9',
'integrated_search_field10',
'integrated_search_field11',
'integrated_search_field12',
'integrated_search_field13',
'integrated_search_field14',
'integrated_search_field15',
'integrated_search_field16',
'integrated_search_field17',
'integrated_search_field18',
'integrated_search_field19',
'integrated_search_field20',
'integrated_search_field21',
'integrated_search_field22',
'integrated_search_field23',
'integrated_search_field24',
'integrated_search_field25',
'integrated_search_field26',
'integrated_search_field27',
'integrated_search_field28',
'integrated_search_field29',
'integrated_search_field30',
'integrated_search_field31',
'integrated_search_field32',
'integrated_search_field33',
'integrated_search_field34',
'integrated_search_field35',
'integrated_search_field36',
'integrated_search_field37',
'integrated_search_field38',
'integrated_search_field39',
'integrated_search_field40',
'integrated_search_field41',
'integrated_search_field42',
'integrated_search_field43',
'integrated_search_field44',
'integrated_search_field45',
'integrated_search_field46',
'integrated_search_field47',
'integrated_search_field48',
'integrated_search_field49',
'integrated_search_field50',
'integrated_search_field51' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'c3' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_search_field',
'integrated_search_field1',
'integrated_search_field2',
'integrated_search_field3',
'integrated_search_field4',
'integrated_search_field5',
'integrated_search_field6',
'integrated_search_field7',
'integrated_search_field8',
'integrated_search_field10',
'integrated_search_field11',
'integrated_search_field12',
'integrated_search_field13',
'integrated_search_field9',
'integrated_search_field14',
'integrated_search_field15',
'integrated_search_field16',
'integrated_search_field17',
'integrated_search_field18',
'integrated_search_field19',
'integrated_search_field21',
'integrated_search_field22',
'integrated_search_field23',
'integrated_search_field24',
'integrated_search_field25',
'integrated_search_field26',
'integrated_search_field27',
'integrated_search_field28',
'integrated_search_field29',
'integrated_search_field30',
'integrated_search_field31',
'integrated_search_field32',
'integrated_search_field33',
'integrated_search_field34',
'integrated_search_field35',
'integrated_search_field36',
'integrated_search_field37',
'integrated_search_field38',
'integrated_search_field39',
'integrated_search_field40',
'integrated_search_field41',
'integrated_search_field42',
'integrated_search_field43',
'integrated_search_field44',
'integrated_search_field45',
'integrated_search_field46',
'integrated_search_field20',
'integrated_search_field47',
'integrated_search_field48',
'integrated_search_field49',
'integrated_search_field50',
'integrated_search_field51' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ) ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ) ),
'misc' => array( 'type' => 'search',
'breadcrumb' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'search',
'type' => 'search',
'layoutId' => 'nomenu',
'disabled' => 0,
'default' => 0,
'forms' => array( 'top' => array( 'modelId' => 'search-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'search_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'above-grid' => array( 'modelId' => 'search-above-grid',
'grid' => array(  ),
'cells' => array(  ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'search-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'search_search',
'search_reset',
'search_back_list' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'simple-search',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c3' ) ),
'section' => '' ) ),
'cells' => array( 'c3' => array( 'model' => 'c3',
'items' => array( 'integrated_search_field',
'integrated_search_field1',
'integrated_search_field2',
'integrated_search_field3',
'integrated_search_field4',
'integrated_search_field5',
'integrated_search_field6',
'integrated_search_field7',
'integrated_search_field8',
'integrated_search_field10',
'integrated_search_field11',
'integrated_search_field12',
'integrated_search_field13',
'integrated_search_field9',
'integrated_search_field14',
'integrated_search_field15',
'integrated_search_field16',
'integrated_search_field17',
'integrated_search_field18',
'integrated_search_field19',
'integrated_search_field21',
'integrated_search_field22',
'integrated_search_field23',
'integrated_search_field24',
'integrated_search_field25',
'integrated_search_field26',
'integrated_search_field27',
'integrated_search_field28',
'integrated_search_field29',
'integrated_search_field30',
'integrated_search_field31',
'integrated_search_field32',
'integrated_search_field33',
'integrated_search_field34',
'integrated_search_field35',
'integrated_search_field36',
'integrated_search_field37',
'integrated_search_field38',
'integrated_search_field39',
'integrated_search_field40',
'integrated_search_field41',
'integrated_search_field42',
'integrated_search_field43',
'integrated_search_field44',
'integrated_search_field45',
'integrated_search_field46',
'integrated_search_field20',
'integrated_search_field47',
'integrated_search_field48',
'integrated_search_field49',
'integrated_search_field50',
'integrated_search_field51' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'separateLabels' => false ) ),
'items' => array( 'search_header' => array( 'type' => 'search_header' ),
'search_reset' => array( 'type' => 'search_reset' ),
'search_back_list' => array( 'type' => 'search_back_list' ),
'search_search' => array( 'type' => 'search_search' ),
'integrated_search_field' => array( 'field' => 'id_unee_t_user_type',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field1' => array( 'field' => 'syst_created_datetime',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field2' => array( 'field' => 'creation_system_id',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field3' => array( 'field' => 'created_by_id',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field4' => array( 'field' => 'syst_updated_datetime',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field5' => array( 'field' => 'update_system_id',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field6' => array( 'field' => 'updated_by_id',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field7' => array( 'field' => 'order',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field8' => array( 'field' => 'is_obsolete',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field9' => array( 'field' => 'ut_user_role_type_id',
'type' => 'integrated_search_field',
'orientation' => 0 ),
'integrated_search_field10' => array( 'field' => 'description',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field11' => array( 'field' => 'creation_method',
'type' => 'integrated_search_field',
'orientation' => 0 ),
'integrated_search_field12' => array( 'field' => 'update_method',
'type' => 'integrated_search_field',
'orientation' => 0 ),
'integrated_search_field13' => array( 'field' => 'organization_id',
'type' => 'integrated_search_field',
'orientation' => 0 ),
'integrated_search_field14' => array( 'field' => 'designation',
'type' => 'integrated_search_field',
'orientation' => 0 ),
'integrated_search_field15' => array( 'field' => 'is_assigned_to_case',
'type' => 'integrated_search_field',
'orientation' => 0 ),
'integrated_search_field16' => array( 'field' => 'is_invited_to_case',
'type' => 'integrated_search_field',
'orientation' => 0 ),
'integrated_search_field17' => array( 'field' => 'is_next_step_updated',
'type' => 'integrated_search_field',
'orientation' => 0 ),
'integrated_search_field18' => array( 'field' => 'is_deadline_updated',
'type' => 'integrated_search_field',
'orientation' => 0 ),
'integrated_search_field19' => array( 'field' => 'is_dashboard_access',
'type' => 'integrated_search_field',
'orientation' => 0 ),
'integrated_search_field20' => array( 'field' => 'is_default_invited',
'type' => 'integrated_search_field',
'orientation' => 0 ),
'integrated_search_field21' => array( 'field' => 'is_default_assignee',
'type' => 'integrated_search_field',
'orientation' => 0 ),
'integrated_search_field22' => array( 'field' => 'can_see_role_contractor',
'type' => 'integrated_search_field',
'orientation' => 0 ),
'integrated_search_field23' => array( 'field' => 'can_see_role_mgt_cny',
'type' => 'integrated_search_field',
'orientation' => 0 ),
'integrated_search_field24' => array( 'field' => 'can_see_role_agent',
'type' => 'integrated_search_field',
'orientation' => 0 ),
'integrated_search_field25' => array( 'field' => 'can_see_occupant',
'type' => 'integrated_search_field',
'orientation' => 0 ),
'integrated_search_field26' => array( 'field' => 'can_see_role_landlord',
'type' => 'integrated_search_field',
'orientation' => 0 ),
'integrated_search_field27' => array( 'field' => 'can_see_role_tenant',
'type' => 'integrated_search_field',
'orientation' => 0 ),
'integrated_search_field28' => array( 'field' => 'is_public',
'type' => 'integrated_search_field',
'orientation' => 0 ),
'integrated_search_field29' => array( 'field' => 'is_item_moved',
'type' => 'integrated_search_field',
'orientation' => 0 ),
'integrated_search_field30' => array( 'field' => 'is_item_removed',
'type' => 'integrated_search_field',
'orientation' => 0 ),
'integrated_search_field31' => array( 'field' => 'is_new_item',
'type' => 'integrated_search_field',
'orientation' => 0 ),
'integrated_search_field32' => array( 'field' => 'is_new_ir',
'type' => 'integrated_search_field',
'orientation' => 0 ),
'integrated_search_field33' => array( 'field' => 'is_message_from_contractor',
'type' => 'integrated_search_field',
'orientation' => 0 ),
'integrated_search_field34' => array( 'field' => 'is_message_from_mgt_cny',
'type' => 'integrated_search_field',
'orientation' => 0 ),
'integrated_search_field35' => array( 'field' => 'is_message_from_agent',
'type' => 'integrated_search_field',
'orientation' => 0 ),
'integrated_search_field36' => array( 'field' => 'is_message_from_occupant',
'type' => 'integrated_search_field',
'orientation' => 0 ),
'integrated_search_field37' => array( 'field' => 'is_message_from_ll',
'type' => 'integrated_search_field',
'orientation' => 0 ),
'integrated_search_field38' => array( 'field' => 'is_message_from_tenant',
'type' => 'integrated_search_field',
'orientation' => 0 ),
'integrated_search_field39' => array( 'field' => 'is_any_new_message',
'type' => 'integrated_search_field',
'orientation' => 0 ),
'integrated_search_field40' => array( 'field' => 'is_case_critical',
'type' => 'integrated_search_field',
'orientation' => 0 ),
'integrated_search_field41' => array( 'field' => 'is_case_blocker',
'type' => 'integrated_search_field',
'orientation' => 0 ),
'integrated_search_field42' => array( 'field' => 'is_case_resolved',
'type' => 'integrated_search_field',
'orientation' => 0 ),
'integrated_search_field43' => array( 'field' => 'is_solution_updated',
'type' => 'integrated_search_field',
'orientation' => 0 ),
'integrated_search_field44' => array( 'field' => 'is_new_inventory',
'type' => 'integrated_search_field',
'orientation' => 0 ),
'integrated_search_field45' => array( 'field' => 'is_occupant',
'type' => 'integrated_search_field',
'orientation' => 0 ),
'integrated_search_field46' => array( 'field' => 'is_unit_owner',
'type' => 'integrated_search_field',
'orientation' => 0 ),
'integrated_search_field47' => array( 'field' => 'is_all_unit',
'type' => 'integrated_search_field',
'orientation' => 0 ),
'integrated_search_field48' => array( 'field' => 'is_all_units_in_country',
'type' => 'integrated_search_field',
'orientation' => 0 ),
'integrated_search_field49' => array( 'field' => 'is_all_units_in_area',
'type' => 'integrated_search_field',
'orientation' => 0 ),
'integrated_search_field50' => array( 'field' => 'is_all_units_in_level_1',
'type' => 'integrated_search_field',
'orientation' => 0 ),
'integrated_search_field51' => array( 'field' => 'is_all_units_in_level_2',
'type' => 'integrated_search_field',
'orientation' => 0 ) ),
'dbProps' => array(  ),
'version' => 4 );
		?>