<?php
$dalTableut_user_types = array();
$dalTableut_user_types["id_unee_t_user_type"] = array("type"=>3,"varname"=>"id_unee_t_user_type", "name" => "id_unee_t_user_type");
$dalTableut_user_types["syst_created_datetime"] = array("type"=>135,"varname"=>"syst_created_datetime", "name" => "syst_created_datetime");
$dalTableut_user_types["creation_system_id"] = array("type"=>200,"varname"=>"creation_system_id", "name" => "creation_system_id");
$dalTableut_user_types["created_by_id"] = array("type"=>3,"varname"=>"created_by_id", "name" => "created_by_id");
$dalTableut_user_types["creation_method"] = array("type"=>200,"varname"=>"creation_method", "name" => "creation_method");
$dalTableut_user_types["syst_updated_datetime"] = array("type"=>135,"varname"=>"syst_updated_datetime", "name" => "syst_updated_datetime");
$dalTableut_user_types["update_system_id"] = array("type"=>200,"varname"=>"update_system_id", "name" => "update_system_id");
$dalTableut_user_types["updated_by_id"] = array("type"=>3,"varname"=>"updated_by_id", "name" => "updated_by_id");
$dalTableut_user_types["update_method"] = array("type"=>200,"varname"=>"update_method", "name" => "update_method");
$dalTableut_user_types["organization_id"] = array("type"=>3,"varname"=>"organization_id", "name" => "organization_id");
$dalTableut_user_types["order"] = array("type"=>3,"varname"=>"order", "name" => "order");
$dalTableut_user_types["is_obsolete"] = array("type"=>16,"varname"=>"is_obsolete", "name" => "is_obsolete");
$dalTableut_user_types["designation"] = array("type"=>200,"varname"=>"designation", "name" => "designation");
$dalTableut_user_types["description"] = array("type"=>201,"varname"=>"description", "name" => "description");
$dalTableut_user_types["ut_user_role_type_id"] = array("type"=>3,"varname"=>"ut_user_role_type_id", "name" => "ut_user_role_type_id");
$dalTableut_user_types["is_occupant"] = array("type"=>16,"varname"=>"is_occupant", "name" => "is_occupant");
$dalTableut_user_types["is_public"] = array("type"=>16,"varname"=>"is_public", "name" => "is_public");
$dalTableut_user_types["is_default_assignee"] = array("type"=>16,"varname"=>"is_default_assignee", "name" => "is_default_assignee");
$dalTableut_user_types["is_invited_all_cases"] = array("type"=>16,"varname"=>"is_invited_all_cases", "name" => "is_invited_all_cases");
$dalTableut_user_types["is_unit_owner"] = array("type"=>16,"varname"=>"is_unit_owner", "name" => "is_unit_owner");
$dalTableut_user_types["is_dashboard_access"] = array("type"=>16,"varname"=>"is_dashboard_access", "name" => "is_dashboard_access");
$dalTableut_user_types["can_see_role_contractor"] = array("type"=>16,"varname"=>"can_see_role_contractor", "name" => "can_see_role_contractor");
$dalTableut_user_types["can_see_role_mgt_cny"] = array("type"=>16,"varname"=>"can_see_role_mgt_cny", "name" => "can_see_role_mgt_cny");
$dalTableut_user_types["can_see_occupant"] = array("type"=>16,"varname"=>"can_see_occupant", "name" => "can_see_occupant");
$dalTableut_user_types["can_see_role_landlord"] = array("type"=>16,"varname"=>"can_see_role_landlord", "name" => "can_see_role_landlord");
$dalTableut_user_types["can_see_role_agent"] = array("type"=>16,"varname"=>"can_see_role_agent", "name" => "can_see_role_agent");
$dalTableut_user_types["can_see_role_tenant"] = array("type"=>16,"varname"=>"can_see_role_tenant", "name" => "can_see_role_tenant");
$dalTableut_user_types["is_assigned_to_case"] = array("type"=>16,"varname"=>"is_assigned_to_case", "name" => "is_assigned_to_case");
$dalTableut_user_types["is_invited_to_case"] = array("type"=>16,"varname"=>"is_invited_to_case", "name" => "is_invited_to_case");
$dalTableut_user_types["is_solution_updated"] = array("type"=>16,"varname"=>"is_solution_updated", "name" => "is_solution_updated");
$dalTableut_user_types["is_next_step_updated"] = array("type"=>16,"varname"=>"is_next_step_updated", "name" => "is_next_step_updated");
$dalTableut_user_types["is_deadline_updated"] = array("type"=>16,"varname"=>"is_deadline_updated", "name" => "is_deadline_updated");
$dalTableut_user_types["is_case_resolved"] = array("type"=>16,"varname"=>"is_case_resolved", "name" => "is_case_resolved");
$dalTableut_user_types["is_case_critical"] = array("type"=>16,"varname"=>"is_case_critical", "name" => "is_case_critical");
$dalTableut_user_types["is_case_blocker"] = array("type"=>16,"varname"=>"is_case_blocker", "name" => "is_case_blocker");
$dalTableut_user_types["is_message_from_contractor"] = array("type"=>16,"varname"=>"is_message_from_contractor", "name" => "is_message_from_contractor");
$dalTableut_user_types["is_message_from_mgt_cny"] = array("type"=>16,"varname"=>"is_message_from_mgt_cny", "name" => "is_message_from_mgt_cny");
$dalTableut_user_types["is_message_from_agent"] = array("type"=>16,"varname"=>"is_message_from_agent", "name" => "is_message_from_agent");
$dalTableut_user_types["is_message_from_occupant"] = array("type"=>16,"varname"=>"is_message_from_occupant", "name" => "is_message_from_occupant");
$dalTableut_user_types["is_message_from_ll"] = array("type"=>16,"varname"=>"is_message_from_ll", "name" => "is_message_from_ll");
$dalTableut_user_types["is_message_from_tenant"] = array("type"=>16,"varname"=>"is_message_from_tenant", "name" => "is_message_from_tenant");
$dalTableut_user_types["is_any_new_message"] = array("type"=>16,"varname"=>"is_any_new_message", "name" => "is_any_new_message");
$dalTableut_user_types["is_new_ir"] = array("type"=>16,"varname"=>"is_new_ir", "name" => "is_new_ir");
$dalTableut_user_types["is_new_inventory"] = array("type"=>16,"varname"=>"is_new_inventory", "name" => "is_new_inventory");
$dalTableut_user_types["is_new_item"] = array("type"=>16,"varname"=>"is_new_item", "name" => "is_new_item");
$dalTableut_user_types["is_item_moved"] = array("type"=>16,"varname"=>"is_item_moved", "name" => "is_item_moved");
$dalTableut_user_types["is_item_removed"] = array("type"=>16,"varname"=>"is_item_removed", "name" => "is_item_removed");
	$dalTableut_user_types["id_unee_t_user_type"]["key"]=true;

$dal_info["unee_t_enterprise_v1_3_0_at_localhost__ut_user_types"] = &$dalTableut_user_types;
?>