<?php
$dalTablepersons = array();
$dalTablepersons["id_person"] = array("type"=>3,"varname"=>"id_person", "name" => "id_person");
$dalTablepersons["external_id"] = array("type"=>200,"varname"=>"external_id", "name" => "external_id");
$dalTablepersons["external_system"] = array("type"=>200,"varname"=>"external_system", "name" => "external_system");
$dalTablepersons["external_table"] = array("type"=>200,"varname"=>"external_table", "name" => "external_table");
$dalTablepersons["syst_created_datetime"] = array("type"=>135,"varname"=>"syst_created_datetime", "name" => "syst_created_datetime");
$dalTablepersons["creation_system_id"] = array("type"=>3,"varname"=>"creation_system_id", "name" => "creation_system_id");
$dalTablepersons["created_by_id"] = array("type"=>200,"varname"=>"created_by_id", "name" => "created_by_id");
$dalTablepersons["creation_method"] = array("type"=>200,"varname"=>"creation_method", "name" => "creation_method");
$dalTablepersons["syst_updated_datetime"] = array("type"=>135,"varname"=>"syst_updated_datetime", "name" => "syst_updated_datetime");
$dalTablepersons["update_system_id"] = array("type"=>3,"varname"=>"update_system_id", "name" => "update_system_id");
$dalTablepersons["updated_by_id"] = array("type"=>200,"varname"=>"updated_by_id", "name" => "updated_by_id");
$dalTablepersons["update_method"] = array("type"=>200,"varname"=>"update_method", "name" => "update_method");
$dalTablepersons["organization_id"] = array("type"=>3,"varname"=>"organization_id", "name" => "organization_id");
$dalTablepersons["person_status_id"] = array("type"=>3,"varname"=>"person_status_id", "name" => "person_status_id");
$dalTablepersons["dupe_id"] = array("type"=>3,"varname"=>"dupe_id", "name" => "dupe_id");
$dalTablepersons["handler_id"] = array("type"=>3,"varname"=>"handler_id", "name" => "handler_id");
$dalTablepersons["is_unee_t_account_needed"] = array("type"=>16,"varname"=>"is_unee_t_account_needed", "name" => "is_unee_t_account_needed");
$dalTablepersons["unee_t_user_type_id"] = array("type"=>3,"varname"=>"unee_t_user_type_id", "name" => "unee_t_user_type_id");
$dalTablepersons["country_code"] = array("type"=>200,"varname"=>"country_code", "name" => "country_code");
$dalTablepersons["gender"] = array("type"=>16,"varname"=>"gender", "name" => "gender");
$dalTablepersons["salutation_id"] = array("type"=>3,"varname"=>"salutation_id", "name" => "salutation_id");
$dalTablepersons["given_name"] = array("type"=>200,"varname"=>"given_name", "name" => "given_name");
$dalTablepersons["middle_name"] = array("type"=>200,"varname"=>"middle_name", "name" => "middle_name");
$dalTablepersons["family_name"] = array("type"=>200,"varname"=>"family_name", "name" => "family_name");
$dalTablepersons["date_of_birth"] = array("type"=>7,"varname"=>"date_of_birth", "name" => "date_of_birth");
$dalTablepersons["alias"] = array("type"=>200,"varname"=>"alias", "name" => "alias");
$dalTablepersons["job_title"] = array("type"=>200,"varname"=>"job_title", "name" => "job_title");
$dalTablepersons["organization"] = array("type"=>200,"varname"=>"organization", "name" => "organization");
$dalTablepersons["email"] = array("type"=>200,"varname"=>"email", "name" => "email");
$dalTablepersons["tel_1"] = array("type"=>200,"varname"=>"tel_1", "name" => "tel_1");
$dalTablepersons["tel_2"] = array("type"=>200,"varname"=>"tel_2", "name" => "tel_2");
$dalTablepersons["whatsapp"] = array("type"=>200,"varname"=>"whatsapp", "name" => "whatsapp");
$dalTablepersons["linkedin"] = array("type"=>200,"varname"=>"linkedin", "name" => "linkedin");
$dalTablepersons["facebook"] = array("type"=>200,"varname"=>"facebook", "name" => "facebook");
$dalTablepersons["adr1"] = array("type"=>200,"varname"=>"adr1", "name" => "adr1");
$dalTablepersons["adr2"] = array("type"=>200,"varname"=>"adr2", "name" => "adr2");
$dalTablepersons["adr3"] = array("type"=>200,"varname"=>"adr3", "name" => "adr3");
$dalTablepersons["City"] = array("type"=>200,"varname"=>"City", "name" => "City");
$dalTablepersons["zip_postcode"] = array("type"=>200,"varname"=>"zip_postcode", "name" => "zip_postcode");
$dalTablepersons["region_or_state"] = array("type"=>200,"varname"=>"region_or_state", "name" => "region_or_state");
$dalTablepersons["country"] = array("type"=>200,"varname"=>"country", "name" => "country");
	$dalTablepersons["external_id"]["key"]=true;
	$dalTablepersons["external_system"]["key"]=true;
	$dalTablepersons["external_table"]["key"]=true;
	$dalTablepersons["organization_id"]["key"]=true;

$dal_info["unee_t_enterprise_v1_3_0_at_localhost__persons"] = &$dalTablepersons;
?>