<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */
 
 class eventclass_Assign_Buildings_to_User  extends eventsBase
{
	function __construct()
	{
	// fill list of events
		$this->events["BeforeAdd"]=true;

		$this->events["BeforeEdit"]=true;

		$this->events["BeforeInsert"]=true;


	}

//	handlers

		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before record added
function BeforeAdd(&$values, &$message, $inline, &$pageObject)
{

			// we capture the organisation id of the user that created this record.

		$values['created_by_id'] = $_SESSION['organization_logged_in_user'];

		$values['organization_id'] = $_SESSION['organization_logged_in_user'];

	// When was the record created?

		$values['syst_created_datetime'] = NOW() ;

	// What is the system that we use to updat this record:

		$values['creation_system_id'] = 'Unee-T Enterprise portal';

	// What is the creation method

		$values['creation_method'] = 'Assign_Buildings_to_Users_Add_Page';

	// Mark the record as obsolete

		$values['is_obsolete'] = 0 ;

	// Mark the record as is_update_needed

		$values['is_update_needed'] = 1 ;

# We have enabled multiple select of user id there we need to get each individual records

# We establish the connection:

global $conn;

DB::SetConnection("");

# We prepare the records we need to insert

if ($values["unee_t_level_1_id"])
{
# We convert this field into an array, a list of records
 $arr_units = explode(",",$values["unee_t_level_1_id"]);
	for ($u=0 ;
			$u<count($arr_units);
			$u++)
	{
	
	# We  go through the list of records and make sure we add everything we need to the mapping table
		
		# We check if the record already exists in the table. This is to avoid an akward error message.

			$strSQLExists = "select * 
					from `external_map_user_unit_role_permissions_level_1` 
					where (`unee_t_level_1_id` = '" . $values['unee_t_level_1_id'] . "'
									AND `unee_t_mefe_user_id` = '" . $values['unee_t_mefe_user_id'] . "'
									AND `unee_t_user_type_id` = '" . $values['unee_t_user_type_id'] . "'
									AND `organization_id` = '" . $values['organization_id'] . "'
									)
					" ;

			$rsExists = db_query($strSQLExists,$conn);

			$data=db_fetch_array($rsExists);

			if($data)
				{
				# if record exists we do NOT create
						$message = 'This User has already been associated to this Property'; 
						return false;
				}
			else
				{
				# This record does not exist - OK to create it
					 DB::exec("
							INSERT INTO `external_map_user_unit_role_permissions_level_1` (
								`syst_created_datetime`
								, `creation_system_id`
								, `created_by_id`
								, `creation_method`
								, `organization_id`
								, `is_obsolete`
								, `is_update_needed`
								, `unee_t_mefe_user_id`
								, `unee_t_level_1_id`
								, `unee_t_user_type_id`
								, `unee_t_role_id`
								, `propagate_level_2`
								, `propagate_level_3`
								) 
								values (
									NOW()
									, '".$values['creation_system_id']."'
									, '".$values['created_by_id']."'
									, '".$values['creation_method']."'
									, '".$values['organization_id']."'
									, '".$values['is_obsolete']."'
									, '".$values['is_update_needed']."'
									, '".$values['unee_t_mefe_user_id']."'
									, '".$arr_units[$u]."'
									, '".$values['unee_t_user_type_id']."'
									, '".$values['unee_t_role_id']."'
									, '".$values['propagate_level_2']."'
									, '".$values['propagate_level_3']."'
									)
									ON DUPLICATE KEY UPDATE 
								  , `creation_system_id` = '".$values['creation_system_id']."'
								  , `created_by_id` = '".$values['created_by_id']."'
								  , `creation_method` = '".$values['creation_method']."'
								  , `organization_id` = '".$values['organization_id']."'
								  , `is_obsolete` = '".$values['is_obsolete']."'
								  , `is_update_needed` = '".$values['is_update_needed']."'
								  , `unee_t_mefe_user_id` = '".$values['unee_t_mefe_user_id']."'
								  , `unee_t_level_1_id` = '".$arr_units[$u]."'
								  , `unee_t_user_type_id` = '".$values['unee_t_user_type_id']."'
								  , `unee_t_role_id` = '".$values['unee_t_role_id']."'
								  , `propagate_level_2` = '".$values['propagate_level_2']."'
								  , `propagate_level_3` = '".$values['propagate_level_3']."'
							")
							;
					}
#					return true;
	}
}

// Place event code here.
// Use "Add Action" button to add code snippets.

return true;
;		
} // function BeforeAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before record updated
function BeforeEdit(&$values, $where, &$oldvalues, &$keys, &$message, $inline, &$pageObject)
{

			// we capture the organisation id of the user whi updated this record.

		$values['updated_by_id'] = $_SESSION['organization_logged_in_user'];

		$values['organization_id'] = $_SESSION['organization_logged_in_user'];

	// When was the record created?

		$values['syst_updated_datetime'] = NOW() ;

	// What is the system that we use to updat this record:

		$values['update_system_id'] = 'Unee-T Enterprise portal';

	// What is the creation method

		$values['update_method'] = 'Assign_Buildings_to_Users_Edit_Page';

// Place event code here.
// Use "Add Action" button to add code snippets.

return true;
;		
} // function BeforeEdit

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before Insert Record
function BeforeInsert(&$rawvalues, &$values, &$pageObject, &$message)
{

			// we capture the organisation id of the user that created this record.

		$values['created_by_id'] = $_SESSION['organizationLoggedInUser'];

	// When was the record created?

		$values['syst_created_datetime'] = NOW() ;

	// What is the system that we use to updat this record:

		$values['creation_system_id'] = 'Unee-T Enterprise portal';

	// What is the creation method

		$values['creation_method'] = 'Assign_Buildings_to_Users_Import_Page';

	// we capture the organisation id of the user whi updated this record.

		$values['updated_by_id'] = $_SESSION['organization_logged_in_user'];

	// When was the record created?

		$values['syst_updated_datetime'] = NOW() ;

	// What is the system that we use to updat this record:

		$values['update_system_id'] = 'Unee-T Enterprise portal';

	// What is the creation method

		$values['update_method'] = 'Assign_Buildings_to_Users_Import_Page';

// Place event code here.
// Use "Add Action" button to add code snippets.

return true;
;		
} // function BeforeInsert

		
		
		
		
		



}
?>
