<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */
 
 class eventclass_Manage_User_Default_Notifications  extends eventsBase
{
	function __construct()
	{
	// fill list of events
		$this->events["BeforeEdit"]=true;


	}

//	handlers

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before record updated
function BeforeEdit(&$values, $where, &$oldvalues, &$keys, &$message, $inline, &$pageObject)
{

			// We need to get ID of the organization associated with this user

		$values['updated_by_id'] = $_SESSION['organizationLoggedInUser'];

	// When was the record created?

		$values['syst_updated_datetime'] = NOW() ;

	// What is the system that we use to updat this record:
  // This should be an INT (default is 1 (unknown)

		$values['update_system_id'] = 'Unee-T Enterprise Portal' ;

	// What is the creation method

		$values['update_method'] = 'Manage_User_Default_Notification_Edit';

// Place event code here.
// Use "Add Action" button to add code snippets.

return true;
;		
} // function BeforeEdit

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		



}
?>
